### ISSUE TITLE
Please support .net framework v4.6.2 for the NuGet package

### ISSUE THREAD

**Issue by jangoffa** [ClosedXML/ClosedXML#768] opened 2018-04-05 12:47 UTC
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**Version of ClosedXML**
0.91.1

**What is the current behavior?**

Currently only .net framework v4.5.2 is supported. We are not able to upgrade whole solution to .net v4.6.2 as ClosedXML is blocking us.

**What is the expected behavior or new feature?**

We expect the support for .net v4.6.2.
Thanks.

**Did this work in previous versions of our tool?  Which versions?**

Yes/No/v0.XX

**Comment by igitur** [comment] 2018-04-05 12:47
Duplicate of #101

**Closed by igitur** 2018-04-05 12:47 UTC

**Comment by kenleese** [comment] 2018-04-05 14:01
@jangoffa I have been successfully using .NET 4.6.1 with ClosedXml for every release since 0.86.0, many releases using .NET 4.6.2, and recently with .NET 4.7.1. If you require assistance perhaps you could provide a project that reproduces the issue you are encountering ("Reproducibility" per the project template)
