### ISSUE TITLE
Issue with Evaluating formula : Unable to calculate the cell value when using MATCH and INDEX inside SUMIFS function

### ISSUE THREAD

**Issue by LokeshRajana** [ClosedXML/ClosedXML#1787] opened 2022-04-29 10:31 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**Did you test against the latest CI build?**
Yes

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4

**What is the current behavior?**
Unable to calculate the cell value when using MATCH and INDEX inside SUMIFS function
Complete this.

## Reproducibility
When cell having below formula, Unable to get the calculated value.

"IFERROR(SUMIFS(INDEX(Sheet10!$A$2:$AR$4298,,MATCH(AT$1,Sheet10!$A$1:$AR$1,0)),INDEX(Sheet10!$A$2:$AR$4298,,MATCH($B12,Sheet10!$A$1:$AR$1,0)),$C12,INDEX(Sheet10!$A$2:$AR$4298,,MATCH($D$1,Sheet10!$A$1:$AR$1,0)),$E$1)/1000000,"")"

**Code to reproduce problem:**
```c#
public void Main()
{
   using (var excelWorkbook = new XLWorkbook(item))
                        {
                            
                            var workSheetsAvailable = excelWorkbook.Worksheets;
                            for (var i = 1; i <= workSheetsAvailable.Count; i++)
                            {
                                var sheet = excelWorkbook.Worksheet(i);
                               
                                    var cellsUsedwithFormulas = sheet.CellsUsed(c => c.HasFormula);
                                    foreach (var cell in cellsUsedwithFormulas)
                                    {
                                        Object value = cell.Value; //// Please note we want to use re calculated value instead cached value.
                                        cell.Clear(XLClearOptions.Contents); 
                                        cell.Value = value; 
                                    }
                                }
                                
                            }
                            excelWorkbook.Save();
                           
                        }
}

Formula used in Excel:
"IFERROR(SUMIFS(INDEX(Sheet10!$A$2:$AR$4298,,MATCH(AT$1,Sheet10!$A$1:$AR$1,0)),INDEX(Sheet10!$A$2:$AR$4298,,MATCH($B12,Sheet10!$A$1:$AR$1,0)),$C12,INDEX(Sheet10!$A$2:$AR$4298,,MATCH($D$1,Sheet10!$A$1:$AR$1,0)),$E$1)/1000000,"")"

Kindly help on the same where closedXML unable to evaluate above formula and throwing null exception.

**Comment by jahav** [comment] 2024-11-20 00:39
Duplicate of #1788

**Closed by jahav** 2024-11-20 00:39 UTC
