### ISSUE TITLE
BackgroundColor of ConditionalFormat changes backgroundColor of Table with TableTheme

### ISSUE THREAD

**Issue by inamar** [ClosedXML/ClosedXML#747] opened 2018-03-19 18:43 UTC
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.91.0 - 0.92.0
**What is the current behavior?**

When I add ConditionalFormat (for example, set bold or set color) to Table with TableTheme (for example, TableStyleMedium11), backgroundColor (actually, absence of backgroundColor) of Cells with ConditionalFormat changes (covers) backgroundColor of Table with TableTheme:

![default](https://user-images.githubusercontent.com/37551288/37611851-958a8f18-2bb4-11e8-90b8-0f1f5762642b.png)

Remark: in Excel 2003 table is shown correct, but in Excel 2013 is not (the table is shown correct, when I click Conditional Formatting->Manage Rules->Edit Rule ->Format ->Fill -> Clear button).

Following methods do not solve this problem:
xlTable.AddConditionalFormat().WhenContains("row2").Font.SetFontColor(XLColor.Red).Fill.SetBackgroundColor(XLColor.Transparent)
or
xlTable.AddConditionalFormat().WhenContains("row2").Font.SetFontColor(XLColor.Red).Fill.SetBackgroundColor(XLColor.NoColor)

**What is the expected behavior or new feature?**

Behavior like  0.89 version. TableTheme's backroundColor is not changed by ConditionalFormat, if ConditionalFormat's  backroundColor is not set.
![default](https://user-images.githubusercontent.com/37551288/37613469-267730e0-2bb9-11e8-87c5-4136441b59db.png)

**Did this work in previous versions of our tool?  Which versions?**

In 0.89 version it worked correct.

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
     var listArr = new List<string[]>
            {
                new string[] { "row1", "row2", "row3" },
                new string[] { "row4", "row5", "row6" }
            };
            using (var wb = new XLWorkbook())
            {
                var ws = wb.AddWorksheet("Sheet1");

                var xlTable = ws.Cell(1, 1).InsertTable(listArr);
                xlTable.Theme = XLTableTheme.TableStyleMedium11;
                xlTable.AddConditionalFormat().WhenContains("row2")
                 .Font.SetFontColor(XLColor.Red);

                wb.SaveAs("cf90.xlsx");
            }
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[cf90.xlsx](https://github.com/ClosedXML/ClosedXML/files/1826173/cf90.xlsx)
[cf89.xlsx](https://github.com/ClosedXML/ClosedXML/files/1826175/cf89.xlsx)

**Comment by igitur** [comment] 2018-03-20 10:15
This was fixed in b00b6d462bfdc28b6235d7ace7f1005a46cc9a94 , but I think I'm going to create a separate PR for this.

**Comment by igitur** [comment] 2018-03-20 10:25
@Pankraty I'm stealing your commit. I tried merging it into the current `develop`, but due to merge conflicts the commit author will be be. Sorry about that.

**Comment by Pankraty** [comment] 2018-03-20 10:30
No worries, I've got plenty of them :-P

**Comment by igitur** [comment] 2018-03-20 10:50
@inamar Thanks for the good code sample to reproduce the issue. This should now be fixed in the latest development build.

**Closed** 2018-03-20 10:49 UTC

**Comment by inamar** [comment] 2018-03-20 17:08
Thanks for promt reaction and fixing issue
