### ISSUE TITLE
Cell with NumberFormat with thousand separator GetValue returns null

### ISSUE THREAD

**Issue by RuiRomano** [ClosedXML/ClosedXML#1271] opened 2019-08-12 22:03 UTC
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.0.0

**What is the current behavior?**

When reading from a cell with a number format with thousand separator the "GetValue<double?>()" returns null.

On debug I saw that if I inspect the cell with the debug and over RichText property is the cause of the issue. Seems like a locale issue with thousand separator.

Attached a code sample and Excel to reproduce.

**Did this work in previous versions of our tool?  Which versions?**

Not sure, but at least with the latest stable version 0.94.2 the issue persists.

## Reproducibility

Attached a code full code sample to debug.

[Sample.zip](https://github.com/ClosedXML/ClosedXML/files/3494504/Sample.zip)

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment] 2019-08-12 22:08
This is a duplicate of #1184 . The workaround, as you mention, is just not to evaluate the `RichText` property if you don't need to.

**Closed** 2021-02-21 12:09 UTC
Labels: bug
