### ISSUE TITLE
IXLWorksheet.RangeUsed() method breaking change

### ISSUE THREAD

**Issue by iulianmone16** [ClosedXML/ClosedXML#2087] opened 2023-05-17 14:12 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
I tested against latest stable release a.k.a 0.101.0 and against different versions. The problem seems to have appeared from 0.94.0 version.

**What is the current behavior?**
IXLWorksheet.RangeUsed() fails to return the expected address on pivot tables.

**What is the expected behavior or new feature?**
I expect to get the correct address when trying to get used range on a worksheet when the worksheet contains only a pivot table.

**Is this a regression from the previous version?**
Yes. As I said before in 0.93.1 is the last time the behaviour is the one desired. From 0.94.0 to 0.101.0 the RangeUsed() fails on given example.
Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{

   var workbook = new XLWorkbook("./Test.xlsx");
IXLWorksheet table, range, pivotTable;
workbook.TryGetWorksheet("Table", out table);
workbook.TryGetWorksheet("Range", out range);
workbook.TryGetWorksheet("PivotTable", out pivotTable);

//Notice that I have tried to use XLCellsUsedOptions on every option but still the same incorrect behaviour
Console.WriteLine("Table: " + table.RangeUsed().LastCellUsed().Address.ToString());
Console.WriteLine("Range: " + range.RangeUsed().LastCellUsed().Address.ToString());
Console.WriteLine("PivotTable: " + pivotTable.RangeUsed(XLCellsUsedOptions.All).LastCellUsed().Address.ToString());
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/11499036/Test.xlsx)

**Comment by iulianmone16** [comment] 2023-06-15 06:16
Hello. @igitur Any news on this issue?

**Comment by jahav** [comment] 2023-06-15 16:27
@iulianmone16 Pivot areas are cleared on load (see #903 and related for details). Since there are no other non-empty cells in the `PivotTable` sheet and the pivot table is cleared, no non-empty cells is found and nothing is used.

From practical point of view, this is a duplicate of #391.

**Comment by jahav** [comment] 2023-06-15 16:28
Duplicate of #391

**Closed as not planned** 2023-06-15 16:28 UTC
