### ISSUE TITLE
Excel crashes when adding cell comment to file with graphic in header and/or footer 

### ISSUE THREAD

**Issue by dontbyte** [ClosedXML/ClosedXML#1437] opened 2020-05-20 06:34 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.95.1

**What is the current behavior?**

Excel crashes when adding a cell comment to a file which contains a header and/or footer graphic.

**What is the expected behavior or new feature?**

Excel file can be opened after adding cell comment to sheet which also contains a graphic in header and/or footer.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

Input file: 
[Mappe1.xlsx](https://github.com/ClosedXML/ClosedXML/files/4655141/Mappe1.xlsx)

Broken output file: 
[NewMappe1.xlsx](https://github.com/ClosedXML/ClosedXML/files/4655149/NewMappe1.xlsx)

**Code to reproduce problem:**
```c#
public void Main()
{
 var _Workbook = new XLWorkbook(@"Mappe1.xlsx");
 var _Sheet = _Workbook.Worksheets.FirstOrDefault();
 _Sheet.Cell(1, 1).Comment.AddText("I'm a comment");
 _Workbook.SaveAs(@"NewMappe1.xlsx");
}
```

**Comment by dontbyte** [comment] 2020-05-20 06:55
File: NewMapp1.xlsx\xl\Worksheets\sheet1.xml

When I replace 
```
<x:legacyDrawingHF r:id="rId2" />
```
with 
```
<x:legacyDrawing r:id="rId2"/>
<x:legacyDrawingHF r:id="rId3"/>
```
It seems to be working again, so theres probably something wrong with the legacyDrawing elements.

**Comment by igitur** [comment] 2020-05-20 12:30
Images in headers and footers are not supported yet. Duplicate of #1336

**Closed by igitur** 2020-05-20 12:30 UTC
