### ISSUE TITLE
{"The identifier `ðæts` was not recognised."}

### ISSUE THREAD

**Issue by VinhPhanVN** [ClosedXML/ClosedXML#1909] opened 2022-11-04 14:17 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.96.0

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**
==> I'd like to read excel content that includes spec chars

Complete this.

**Is this a regression from the previous version?**
==> unknow

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main(string _path, int _sheetnum)
{
    try
         {
            using (XLWorkbook _wb = new XLWorkbook(_path))
            {
               if (_wb.Worksheets.Count < _sheetnum)
                  return _dt;

               IXLWorksheet _ws = _wb.Worksheet(_sheetnum);
               if (_ws.RangeUsed() != null)
                  _ws.RangeUsed().SetAutoFilter(false);
                    if (_ws.LastRowUsed() == null)
                        return _dt;
                    else
                        _dt = _ws.RangeUsed().AsTable().AsNativeDataTable();
            }
            return _dt;
         }
         catch (Exception _ex) { _ex.WriteLogError(); return _dt; }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment] 2022-11-04 14:23
Fix the issue to include the minimal reproducible example that demonstrates the problem.

**Comment by jahav** [comment] 2022-11-12 13:23
Closing due to insufficient info.

**Closed as not planned by jahav** 2022-11-12 13:23 UTC
