### ISSUE TITLE
Cannot open file with pivot table referencing named column that no longer exists

### ISSUE THREAD

**Issue by CraigRaelHarris** [ClosedXML/ClosedXML#1837] opened 2022-07-15 06:41 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.96.0

**What is the current behavior?**

Try to open file (attached) which has a pivot table field reference pointing to a column that no longer exists.
This throws an error: The column 'Asset Group' does not appear in the source range. (Parameter 'sourceName')

**What is the expected behavior or new feature?**

Should be able to open the file, though the pivot won't work since it references a non-existant field (opens like this in Microsoft Excel). Once open, the pivot can be fixed by removing defunct field references.

**Is this a regression from the previous version?**

Yes. Works in 0.85.0

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
          try
                {
                    using (XLWorkbook workBook = new XLWorkbook("fix.xlsx"))
                    {
                        Console.Writeline("All good");
                    }
                }
                catch (Exception ex)
                {
                    Console.Writeline($"Error!  :   {ex.Message}");
                }
}
```

RESULT:       
Error! :   The column 'Asset Group' does not appear in the source range. (Parameter 'sourceName')

- [x] I attached a sample spreadsheet.  
[fix.xlsx](https://github.com/ClosedXML/ClosedXML/files/9118498/fix.xlsx)

**Comment by CraigRaelHarris** [comment] 2022-07-21 06:42
Exception is thrown at;
XLWorkbook_Load.cs -> LoadSpreadsheetDocument -> line 802 ->    rf = pt.ReportFilters.Add(filterName);
XLPivotFields.cs -> Add -> line 27 -> checks 
![image](https://user-images.githubusercontent.com/5291055/180147882-2c258e48-69cc-41a9-96ef-ac9e589e3921.png)

**Comment by jahav** [comment] 2023-10-25 22:22
On one hand, pivot table no longer relies on source range in a worksheet, but keeps it's own copy of values (as it should), but xlsx still fails, because it contains calculated fields, so this time, the exception is that number of columns in pivot cache records is not same as number of cache fields in pivot cache definition.

![image](https://github.com/ClosedXML/ClosedXML/assets/7634052/636ce8c3-5af9-4432-8efb-29e6186ec118)

**Comment by jahav** [comment] 2023-10-25 22:23
Duplicate of #821

**Closed as not planned by jahav** 2023-10-25 22:23 UTC
