### ISSUE TITLE
Error in color of notes or comments when saving

### ISSUE THREAD

**Issue by mcastillob** [ClosedXML/ClosedXML#2496] opened 2024-11-13 13:50 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

**Version of ClosedXML**

 V0.87.0

**Code to reproduce problem:**
```c#

##Exception error

  en System.ThrowHelper.ThrowKeyNotFoundException()
   en System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   en ClosedXML.Excel.XLColor.get_Color() en C:\Users\mcastillo\OneDrive\Documentos\ClosedXML\ClosedXML\Excel\Style\Colors\XLColor_Public.cs:línea 53
   en ClosedXML.Excel.XLWorkbook.GenerateShape(XLCell c, String shapeTypeId) en C:\Users\mcastillo\OneDrive\Documentos\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:línea 2443
   en ClosedXML.Excel.XLWorkbook.GenerateVmlDrawingPartContent(VmlDrawingPart vmlDrawingPart, XLWorksheet xlWorksheet, SaveContext context) en C:\Users\mcastillo\OneDrive\Documentos\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:línea 2411
   en ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document) en C:\Users\mcastillo\OneDrive\Documentos\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:línea 311
   en ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, Boolean validate) en C:\Users\mcastillo\OneDrive\Documentos\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:línea 117
   en ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate) en C:\Users\mcastillo\OneDrive\Documentos\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:línea 486
   en ClosedXML.Excel.XLWorkbook.SaveAs(String file) en C:\Users\mcastillo\OneDrive\Documentos\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:línea 461

## error index 81 not found

      return IndexedColors[_indexed].Color;

## FIX append color index 81 XLColor_Static.cs

  eg.   {81, FromHtml("#FF333333")},

**Comment by igitur** [comment] 2024-11-14 10:58
Relevant thread: https://stackoverflow.com/questions/14710674/what-does-color-indexed-81-mean

I don't think the fix above is correct here. It's unclear whether index 81 is a real index or whether it is a magic number referring to automatic color for notes.

**Comment by mcastillob** [comment] 2024-11-14 13:37
Hi!

**The color number 81 is defined as a style in the Excel notes.**

![note](https://github.com/user-attachments/assets/fb1f106a-2327-4cb4-97e8-d94558470ee6)

![color index 81](https://github.com/user-attachments/assets/fe0427b3-8359-46eb-927a-fd628b40a74b)

**XLColor obtains index 81 of a substring**

![none 81](https://github.com/user-attachments/assets/7d259458-2d7b-4b9f-bb64-e8842ae885fc)

![index color error](https://github.com/user-attachments/assets/55e58fec-7de3-41ff-b2b5-aabe17e71886)



I remain attentive to recommendations or if a better solution can be generated.
#2497

**Comment by jahav** [comment] 2024-11-18 11:39
@mcastillob Missing repro. Please provide test file. When i create a file with a note (in Excel 2016 it was called Comment) it can be loaded and saved without error.

**Comment by jahav** [comment] 2024-11-18 12:01
Also, the report says version 0.87 which is ancient and code in screenshots display code that no longer exists.

I modified reading VML colors with index in 0.100, PR #1892, which looked similar IIRC.

**Comment by mcastillob** [comment] 2024-11-18 13:12
Thank you, yes it is correct in the latest version. my project uses version 0.87 since it works with .net framework 4.0

**Comment by igitur** [comment] 2024-11-18 13:13
> **Did you test against the latest CI build?**
> 
> * [ x] Yes
> * [ ]  No

Sigh.

**Comment by jahav** [comment] 2024-11-19 00:23
Duplicate of #1884

**Closed as completed by jahav** 2024-11-19 00:23 UTC
