### ISSUE TITLE
Reading cell style when conditional formatting is applied.

### ISSUE THREAD

**Issue by JajwalyaJ19** [ClosedXML/ClosedXML#2572] opened 2024-12-09 07:51 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.102.2.0

**What is the current behavior?**
I have crated an Excel file with one conditional format added in it. 
Conditional Format is applied over range A3 to A4. 
![image](https://github.com/user-attachments/assets/1c6e431b-7edc-4c4b-b7fa-e322b79aa337)

When we read cell style/info for cell A3 and A4, we always get default style.
How do we get correct style as we see in excel? Since cells A3, A4 are having conditional format applied and only A4 satisfies the conditional format rule.

**What is the expected behavior or new feature?**
When we read cell style/info for cell A3, it should get default style and cell A4 should get style applied in Conditional Formatting rule.
We are expecting same results what we see in Microsoft Excel.

**Is this a regression from the previous version?**
No.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
String filePath = @"<File Name>";
XLWorkbook workbook = new XLWorkbook(filePath);
var worksheet = workbook.Worksheet("Sheet1");
var cellA2 = worksheet.Cell("A2").Style;
Console.WriteLine("Cell A2 Default style = " + cellA2.ToString());

foreach (var cfItem in worksheet.ConditionalFormats)
	{
	foreach (var range in cfItem.Ranges)
		{
		var cellA3 = range.Cells("A3");
		var cellA4 = range.Cells("A4");
		IXLStyle cellA3Style = cellA3.Style;
		Console.WriteLine("Cell A3 style = " + cellA3Style.ToString());
		IXLStyle cellA4Style = cellA4.Style;
		Console.WriteLine("Cell A4 style = " + cellA4Style.ToString());
		IXLStyle cellCfStyle = cfItem.Style;
		Console.WriteLine("Conditional Formatting style = " + cellCfStyle.ToString());
		// Conditional Format is applied over range A3 to A4
		// Question: Cell A3 should get default style and cell A4 should get style applied in Conditional Formatting rule.
		// How do we identify which style to get for a cell in conditional formatting range scenario.
		}
	}
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[sampleCF.xlsx](https://github.com/user-attachments/files/18058025/sampleCF.xlsx)

**Comment by jahav** [comment] 2024-12-11 09:41
> How do we get correct style as we see in excel? 

There is no way to get that information. Conditional formatting is only stored, not evaluated. It's not something that has high priority ATM.

**Comment by jahav** [comment] 2024-12-11 09:42
Duplicate of #1718

**Closed as not planned by jahav** 2024-12-11 09:42 UTC
