### ISSUE TITLE
COUNTA (Statistical) CalcEngine function output not as expected

### ISSUE THREAD

**Issue by richard-hinton** [ClosedXML/ClosedXML#2276] opened 2024-01-31 18:59 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

---

**Version of ClosedXML**

0.102.2
0.104.999.3547

---

**What is the current behavior?**

The ClosedXML COUNTA method is not including "" (empty string) in the counts
- `D4` has an formula setting the cell to `"" `
- `D5` has a single quote that Excel picks up as text cell

![image](https://github.com/ClosedXML/ClosedXML/assets/113972151/367ce19a-5f2f-431e-bd6a-7d35d7c999f2)

---

**What is the expected behavior or new feature?**

https://support.microsoft.com/en-us/office/counta-function-7dc98875-d5c1-46f1-9a82-53f3219e2509

Excel counts these circled cells, so are not included in the 'incomplete' column count in the attached example.
- `D4` has an formula setting the cell to `"" `
- `D5` has a single quote that Excel picks up as text cell

![image](https://github.com/ClosedXML/ClosedXML/assets/113972151/925631c3-8adc-4f56-b95c-95b6dc74a53b)

---

## Reproducibility

[ClosedXml_COUNTA.xlsx](https://github.com/ClosedXML/ClosedXML/files/14115960/ClosedXml_COUNTA.xlsx)

**Code to reproduce problem:**
```c#
        static void Main(string[] args)
        {
            var templatePath = @"C:\_temp\ClosedXml\Calc_CountA\Calc_CountA\ClosedXml_COUNTA.xlsx";
            var outputPath = @"C:\_temp\ClosedXml\Calc_CountA\Calc_CountA\ClosedXml_COUNTA_output.xlsx";

            using var spreadsheet = new XLWorkbook(templatePath);

            spreadsheet.Worksheet(1).Cell("E4").InvalidateFormula();
            spreadsheet.Worksheet(1).Cell("E5").InvalidateFormula();

            spreadsheet.SaveAs(outputPath, new SaveOptions() { EvaluateFormulasBeforeSaving = true });
        }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by richard-hinton** [comment] 2024-02-01 10:09
Thank you for the very prompt fix on the above.
I see the 104 milestone is looking close, but if this is open ended, would it be possible to get an updated `104-preview` nuget release published? This build seems so much more usable (in our experience) than the `104-preview2` from Oct-2023.

**Comment by jahav** [comment] 2024-02-04 23:29
@richard-hinton I don't want to publish nuget, because I am in a middle of refactoring of pivot tables. As for the release, at best the release candidate is 10 days out. Need to finish pivot and ensure that calc engine won't throw too many exceptions because of recursive evaluation -> calculation chain change.

If you really need it, add your onw nuget server and use one of development snapshots (appveyor caches them in history https://ci.appveyor.com/project/ClosedXML/ClosedXML/history or just build it in release mode).

I am closing the issue, because I believe the root cause is resolved. Thanks for the issue, I fixed the empty string handling in shared string table that would cause a lot of problems for others.

**Closed as completed by jahav** 2024-02-04 23:29 UTC

**Comment by richard-hinton** [comment] 2024-02-05 09:11
Thank you for the response @jahav, much appreciated.
