### ISSUE TITLE
Calling the RichText property on a cell causes the underlying (OLE) date value to be lost and replaced with a locale specific date string

### ISSUE THREAD

**Issue by sprintstar** [ClosedXML/ClosedXML#1554] opened 2020-11-04 10:47 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

Calling the RichText property on a cell causes the underlying (OLE) date value to be lost and replaced with a locale specific date string, which causes issues for non-US (i'm assuming) users.

**What is the expected behavior or new feature?**

That the underlying value of a cell should not be changed, and repeated calls to GetDateTime should always return the same value.

**Is this a regression from the previous version?**

No, issue exists in both 0.87.1 and 0.95.3.

**Code to reproduce problem:**

The Excel file loaded has a date value in cell (1,1) of 43858 (formatted to a date using whatever format).  GetPropValue is a function that gets a property value using reflection.  As you can see, after calling RichText, GetDateTime fails to return the date correctly.

[datetimes.xlsx](https://github.com/ClosedXML/ClosedXML/files/5487272/datetimes.xlsx)

```c#
using ClosedXML.Excel;
using System;
using System.IO;
using System.Reflection;

namespace ClosedXmlTest
{
	class Program
	{
		static void Main(string[] args)
		{
			var path = Path.Combine(
				Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) ?? throw new InvalidOperationException(),
				@"DateTimeParsingTests\datetimes.xlsx");

			var workbook = new XLWorkbook(path);

			var dateCell = workbook.Worksheet(1).Cell(1, 1); // DateTime 43858 (2020-01-28)

			var innerText = GetPropValue(dateCell, "InnerText"); 
			// innerText = 43858

			var correctDateTime = dateCell.GetDateTime();
			// correctDateTime = 2020-01-28

			var richText = dateCell.RichText;

			var innerText2 = GetPropValue(dateCell, "InnerText");
			// innerText2 = 1/28/2020

			var v2 = dateCell.Value;

			var wrongDateTime = dateCell.GetDateTime();
			// dateTime = 0001-01-01
		}

		public static object GetPropValue(object src, string propName)
		{
			return src.GetType().GetProperty(propName).GetValue(src, null);
		}
	}
}

```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment] 2020-11-04 10:50
Duplicate of #1184  and will be fixed in #1396

**Closed by igitur** 2020-11-04 10:50 UTC
