### ISSUE TITLE
Using external link in formula

### ISSUE THREAD

**Issue by bhrz** [ClosedXML/ClosedXML#986] opened 2018-09-04 13:56 UTC
Hi everyone,
I am struggling to implement external source in my formula. More simplified version of what I am trying to achieve is as in below scenario:
I have 2 files, File1.xlsx and File2.xlsx. In File1.xlsx, I have a formula that sums A1:A3 range from File2.xlsx. My formula in File1 is "**=SUM('C:\Users\bb\Desktop\test\[File2.xlsx]Sheet1'!$A$1:$A$3)**"

```
var test1 = ws.Cell("E6").HasFormula;
```
returns True, which means there is a formula. I also see correct result of the formula when I open the file. But when I try to get the result value of the formula programmatically, using
```
var test2 = ws.Cell("E16").Value;
```
I am getting **System.Exception: 'Identifier expected.'** exception.
Thanks in advance.

**Comment by igitur** [comment] 2018-09-04 14:08
Sorry, links to external files are not supported yet.

Duplicate of #121

**Closed by igitur** 2018-09-04 14:08 UTC

**Comment by bhrz** [comment] 2018-09-05 15:46
@igitur Thank you for your quick response. One more question. I am getting the same error when I reference to another sheet of the same workbook. Can I also assume that it will not work even if I reference to another sheet of the same workbook? Something like below:
"**=SUM('C:\Users\bb\Desktop\test[File2.xlsx]Sheet1'!$A$1:$A$3)**"

**Comment by igitur** [comment] 2018-09-05 20:05
That reference is to an external workbook, even though that workbook is the same as the calling workbook. If you referenced the ithrt sheet directly, without the workbook path, it should work.

**Comment by haladamateusz** [comment] 2025-03-03 16:05
Any update on support for external files?
