### ISSUE TITLE
Maintaining namedrange when copying worksheet

### ISSUE THREAD

**Issue by pabian84** [ClosedXML/ClosedXML#468] opened 2017-09-07 03:56 UTC
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**Version of ClosedXML**
0.88.0

**What is the current behavior?**
When I inspected the target worksheet, the source's namedrange list itself was copied, but the target address was set to the source worksheet. For example, it should change from source!A15 to target!A15, but it's copied as source!A15. Is this because of what I didn't do, or becaused it's not supported? If it's not supported, is there any plans to support this?

**Comment by igitur** [comment] 2017-09-07 08:48
Duplicate of #416
Fixed in #418

Try 0.89.0-beta1

**Closed by igitur** 2017-09-07 08:48 UTC
