### ISSUE TITLE
Not returning all cells?

### ISSUE THREAD

**Issue by WinnetDev** [ClosedXML/ClosedXML#1291] opened 2019-10-03 17:29 UTC
ClosedXML Version: v0.94.2

**What is the current behavior?**

If you have multiple rows and one of them have 6 cells and *some* have 6 cells, but one cell in the middle is empty you would get 5 used cells.

**What is the expected behavior or new feature?**

Is this expected behavior? Basically is skipping one column

## Reproducibility

**Code to reproduce problem:**
```c#
using ClosedXML.Excel;
using System.Collections.Generic;
public void Main()
{
     using var workbook = new XLWorkbook("closedxml_test.xlsx");
     foreach (var sheet in workbook.Worksheets)
     {
         foreach (var row in sheet.RowsUsed())
         {
             var line = new List<string>();
             foreach (var cell in row.CellsUsed())
             {
                 line.Add(cell.GetValue<string>());
             }
         }
     }
}
```
[closedxml_test.xlsx](https://github.com/ClosedXML/ClosedXML/files/3687314/closedxml_test.xlsx)

**Comment by Pankraty** [comment] 2019-10-03 17:36
Yes, this is a correct behavior. If you want to include all cells use row.Cells(). CellUsed includes only cells which are not empty in some sense - either have contents, or styles, or conditional formats and so on.

**Comment by WinnetDev** [comment] 2019-10-03 17:52
In this case, It doesn't have content or style or format or anything. The cell content is *optional*, but it's position not. If that make sense. There is any workaround for that? Like fill previous cell if it's empty. Because If i'm not mistaken Row.Cells() would return all possible cells that's not what I want either

**Comment by igitur** [comment] 2019-10-03 18:06
Maybe try something with `sheet.FirstCellUsed().CurrentRegion.Cells()`.

**Comment by WinnetDev** [comment] 2019-10-03 18:36
This one `sheet.FirstCellUsed().CurrentRegion.Rows()` did the trick. At later stage I did `row.Cells()` and got the expected cells. But it's kind of slow?

**Comment by Pankraty** [comment] 2019-10-03 18:53
It depends on how large the region is. For larger ones this will cause lots of empty cells to be instantiated - only to see that they are empty and (probably) may be ignored. So CellsUsed() will be faster indeed but it's hard to say if it can be used for your task as we do not know what you are trying to achieve.

**Comment by WinnetDev** [comment] 2019-10-03 19:09
Here is my use case.

Let say I have sheet that contain: `Name`, `Email`, `Phone`. The user would be able to choose between these 3 column the data that he want. He/She may want them all or just some of them, but they can also choose them in the order that they want (`Email`, `Name`). So if one of the cell is skipped the wrong data would be extracted. 

Yeah, the data may vary in size (Big or Small). For now, since the data have header. I'm falling back to the header's cells count. But In my use case, the data may not have header. So, I'm trying to see if there is a better option.

**Comment by Pankraty** [comment] 2020-03-11 14:44
I am going to close the issue because 

> Is this expected behavior?

Yes, it is the expected behavior. 

In order to get all cells belonging to some range use `range.Cells()`; to get only those cells that are used call `range.CellsUsed()`, literally, but don't get surprised that _non-used_ cells are ommitted :)

There is also a useful method `worksheet.RangeUsed()` that returns a rectangular range containing all used cells from a worksheet. Therefore, enumerating `worksheet.RangeUsed().Cells()` will not skip empty cells in the middle and, on the other hand, will not instantiate too many useless cells (except such cases when some random cells somewhere far away have some contents...). This may be a good compromise.

**Closed by Pankraty** 2020-03-11 14:44 UTC
