### ISSUE TITLE
Any plan to support Core 2.0?

### ISSUE THREAD

**Issue by cbfrank** [ClosedXML/ClosedXML#711] opened 2018-03-05 09:06 UTC
Hello, Thanks for the greate project, do we have a plan to support dotnet core 2.0? As we are evaluating this library and would like to use it in a asp.net core 2.0 project.

**Comment by igitur** [comment] 2018-03-05 09:07
Duplicate of #101

**Comment by igitur** [comment] 2018-03-05 09:07
Please search before posting.

**Closed by igitur** 2018-03-05 09:07 UTC
