### ISSUE TITLE
Unable to resolve dependency 'SixLabors.Fonts' when nuget updates ClosedXML to 0.97.0

### ISSUE THREAD

**Issue by ajstadlin** [ClosedXML/ClosedXML#1931] opened 2022-12-02 15:14 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.97.0

**What is the current behavior?**

Failure log
Attempting to resolve dependencies for package 'ClosedXML.0.97.0' with DependencyBehavior 'Lowest'
Unable to resolve dependency 'SixLabors.Fonts'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.

**What is the expected behavior or new feature?**

Successfully installed log:

Resolving dependency information took 0 ms
Resolving actions to install package 'ClosedXML.0.96.0'
Resolved actions to install package 'ClosedXML.0.96.0'
Adding package 'ClosedXML.0.96.0' to folder 'C:\MySolution\MyProject\packages'
Added package 'ClosedXML.0.96.0' to folder 'C:\MySolution\MyProject\packages'
Added package 'ClosedXML.0.96.0' to 'packages.config'
Successfully installed 'ClosedXML 0.96.0' to MyApp

**Is this a regression from the previous version?**

Versions 0.95.4 and 0.96.0 work OK

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

This is repeatable.  It happens every time I use nuget to install ClosedXML 0.97.0 version

**Code to reproduce problem:**
```c#
public void Main()
{
  // Code works with 0.95.4 and 0.96.0 version nuget packages
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by ajstadlin** [comment] 2022-12-02 15:22
Package Manager Screenshot Attached

![ClosedXML-97-SixLaborsFonts-dependencyerror](https://user-images.githubusercontent.com/14024430/205326263-5f1a48e4-3408-4d6e-bdfe-c9034334d56e.png)

**Comment by jahav** [comment] 2022-12-02 15:25
Please use one of the solutions from https://github.com/ClosedXML/ClosedXML/issues/1883#issuecomment-1289521384
Duplicate of #1883

**Closed as not planned by jahav** 2022-12-02 15:25 UTC
