### ISSUE TITLE
Exporting Huge Records

### ISSUE THREAD

**Issue by adhip94** [ClosedXML/ClosedXML#611] opened 2017-11-30 06:25 UTC
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.87.0

**What is the current behavior?**

Lets say I have 20,00,000 to export at once, so in my C# application I am using a loop with which I am exporting lets say at around 50,000-60,000 records at a time from 20,00,000 records, so for 50,000 records per excel I will have 40 excels. In my application logs I can see only 7-8 excels generated out of 40. In my application logs there are no errors generated but I have added custom logs in my application to check where exactly it stops and I have noticed it stops at the SaveAs method. Also when I check event viewer to monitor if there is any error or warning I can notice that there is a warning for ASP .NET 4.0.30319.0. I can also notice high disk and cpu usage when the SaveAs method is triggered.

I have seen in issues that people use garbage collection, but instead of using that I am using the c# "using" method in the snippet shown below since garbage collection will close all the objects in the application.

Right now I have initiated an export for 20,000 records instead of 50,000, will monitor this, but is this something that can be resolved?

**Did this work in previous versions of our tool?  Which versions?**

Didn't try

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
using (XLWorkbook wb = new XLWorkbook())
                {
```

**Comment by igitur** [comment] 2017-11-30 12:59
Duplicate of #86

**Closed by igitur** 2017-11-30 12:59 UTC
