### ISSUE TITLE
Compatibility with linux

### ISSUE THREAD

**Issue by maxime-ducoroy** [ClosedXML/ClosedXML#1942] opened 2022-12-20 09:45 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.97.0

**What is the current behavior?**

I have a compatibility error with Linux when I use the AdjustToContents method.

**What is the expected behavior or new feature?**

This method calls System.Drawing which is not compatible with Linux as indicated in the Microsoft doc: [https://learn.microsoft.com/fr-fr/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only](https://learn.microsoft.com/fr-fr/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only)

Would it be possible to consider a compatibility please?

Complete this.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
            string path = ".\\test_export_excel";
            using XLWorkbook xLWorkbook = new XLWorkbook();
            IXLWorksheet iXLWorksheet = xLWorkbook.Worksheets.Add("Sheet");
            iXLWorksheet.Cell(1, 1).Value = "Test";
            iXLWorksheet.Cell(1, 2).Value = "Long Test for ajust column to contents";

            for (int i = 1; i <= 2; i++)
            {
                iXLWorksheet.Column(i).AdjustToContents();
            }

            xLWorkbook.SaveAs(path);
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment] 2022-12-20 10:33
System.Common.Drawing has already been removed in 0.97, see ticket #1805. I assume that is it, becase no error message has been provided in the report.

You will likely need to specify font, see 
https://github.com/ClosedXML/ClosedXML/issues/1902#issuecomment-1299196079

**Comment by jahav** [comment] 2022-12-20 10:34
Duplicate of #1805

**Closed as not planned by jahav** 2022-12-20 10:34 UTC
