### ISSUE TITLE
Array with a text throws NotImplementedException for legacy formulas

### ISSUE THREAD

**Issue by julienGrd** [ClosedXML/ClosedXML#2432] opened 2024-10-04 22:19 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.104.999.3773

**Version of OpenXml**
3.1.0

**What is the current behavior?**

I have a workbook with multiple sheet containing formulas. 
My goal is to edit the workbook to replace the formulas of the sheet by their calculated values and  then delete the intermediary sheet which i dont need.
When i try to read the CachedValue of a cell, it return me blank (whereas there is value computed when open the workbook with excel)
When i try to read the value of a cell, it take a lot of time finish with this Exception "The method or operation is not implemented.'"
When i try to call RecalculateAllFormulas on the sheet, it take so much time i stop after one hour

**What is the expected behavior or new feature?**

have the correct Value computed in the CachedValue property of the cell

**Is this a regression from the previous version?**

no, it was the same with 0.102 version and OpenXml 2.20 (i just migrate when i see this error, i check with old version and i had the same errors) 

## Reproducibility

- checkout the project https://github.com/julienGrd/ConsoleAppTestClosedXml
- copy the xlsx file StatdcK4-Trame_CAMSP_2023_VF_avec_fonctions-ORiGiNAL.xlsx which is at the root of the project in bin/debug/net8 folder
- run the app and wait it finish
- open  bin/debug/net8/StatdcK4-Trame_CAMSP_2023_VF_avec_fonctions-ORiGiNAL_clean.xlsx, compare the Enfants_accompagnes_AGR sheet with the one of the original file, you will see the values are not reported

For the investigation, take care that many sheets are hidden in the workbook thats why you don't see them in excel

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[StatdcK4-Trame_CAMSP_2023_VF_avec_fonctions-ORiGiNAL.xlsx](https://github.com/user-attachments/files/17264155/StatdcK4-Trame_CAMSP_2023_VF_avec_fonctions-ORiGiNAL.xlsx)

**Comment by jahav** [comment] 2024-10-05 00:02
I don't think ClosedXML is in a state to do what you want, nor will it be in a short term.

This has several problems, just to finish recalculation (who knows about correct result): 

#### SUMPRODUCT is slow
No surprise here. That is duplicate of #1202.

![image](https://github.com/user-attachments/assets/c9656127-19f5-4d42-bb73-863cfa20a696)

#### Array conversion for legacy formulas
This throws an exception. I don't even know what to stuff there, possibly just return error. In the end, legacy functions are not strongly typed, only some of them are barely capable of using array of numbers. All of them should be purged, but don't have time to reimplement.

#### COUNTIFS is slow
Legacy again

#### AVERAGE
Legacy again... am I starting to see a pattern here? 

And I stopped here to try to profile, because I know it's all of them. Nothing that uses cell area and is legacy is slow. Allocation is evil. Linq is evil. Boxing should be avoided. Materialization to a list is a crime.

I will leave this issue here with a scope of the exception (rough thinking what should be done about argument, because it has actual no solution because legacy never worked properly with arrays):
> When function gets an array as an argument and it's a legacy function, the method for converting array to legacy parameter should not throw an exception. Try to convert to a number or for empty values a 0 and if conversion is not possible for an element of an array, use an error as an argument value instead of array.
> Example: `AVERAGE({1, 2, "3", "4"})` (which BTW is 1.5, so I can't just convert)

The dependency tree build is also rather slow and doesn't scale (later entries are added slower than earlier), not exactly sure why... possibly bad hash key?
 
> Building dependency tree:
> Formula added: 10000 (       621 ms)
> Formula added: 20000 (      1157 ms)
> Formula added: 30000 (      1948 ms)
> Formula added: 40000 (      2953 ms)
> Formula added: 50000 (      3938 ms)
> Formula added: 60000 (      4983 ms)
> Formula added: 70000 (      6103 ms)
> Formula added: 80000 (      7302 ms)
> Formula added: 90000 (      9030 ms)
> Formula added: 100000 (     11255 ms)
> Formula added: 110000 (     13683 ms)
> Formula added: 120000 (     16326 ms)
> Formula added: 130000 (     18602 ms)
> Formula added: 140000 (     20795 ms)
> Formula added: 150000 (     23116 ms)
> Formula added: 160000 (     25699 ms)
> Formula added: 170000 (     28299 ms)
> Formula added: 180000 (     31018 ms)

**Comment by julienGrd** [comment] 2024-10-05 00:47
ok thanks for this detailed answer !

I would like to know what i can do now because i really need to implement that.

As i understand, the problem come from because we are using legacy excel function right ? so if i replace all these legacy functions with "modern" ones it should work ? im not even sure i can do that because its not me who produce the formula, we receive the file like that....


Or do you think, even by changing formulas, i would not be able to make this library works for this use case ?
 
In this case, do you know other .net library, even commercial, which would be able to compute this correctly ? (with the legacy formulas)

thanks for your help !

**Comment by igitur** [comment] 2024-10-05 09:20
> Allocation is evil. Linq is evil. Boxing should be avoided. Materialization to a list is a crime.

Geez, sorry!

**Comment by jahav** [comment] 2024-10-05 18:29
@igitur Please don't take it personally. I am generally dissatisfied with a code, including mine (or if you want a market speak, I have a drive for improvement :-D). I rewrote the `SUMPRODUCT` in #2433

**Comment by jahav** [comment] 2024-12-12 23:39
The official reason for this issue (the adapter) has been removed through PR #2583. 

Background is in this comment of issue https://github.com/ClosedXML/ClosedXML/issues/2482#issuecomment-2495619085

As far as the original description of the issue, it doesn't crash and project produces a workbook that can be opened by Excel.

It is even possible to recalculate it (just load and call `workbook.RecalculateAllFormulas()`) without exception (though it takes 2 minutes), but the original code doesn't require recalculation, so it's reasonably fast (Elapsed 4323 ms).

ClosedXML only recalculates when it is required (i.e. some asks for a value of a dirty cell or recalculation is called, recalculation of values during save is optional and must be required in `SaveOptions`), it seems it wasn't necessary....  Not really sure why. Quite possibly another bug ¯\\_(ツ)_/¯

**Closed as completed by jahav** 2024-12-12 23:39 UTC
