### ISSUE TITLE
ClosedXML throwing out of memory exception when exporting 73000 records

### ISSUE THREAD

**Issue by jk-2017** [ClosedXML/ClosedXML#183] opened 2017-01-31 19:15 UTC
Exception is coming at this particular line of code - 

`wb.Worksheets.Add(DynamicSource);`

dynamicsource is the datatable that has all the data to be exported

**Comment by vbjay** [comment] 2017-01-31 21:10
How many columns?

**Comment by jk-2017** [comment] 2017-01-31 21:16
53 columns and 73000 rows

**Comment by jk-2017** [comment] 2017-01-31 21:19
This is my complete code snippet....

using (XLWorkbook wb = new XLWorkbook())
                    {
                        Response.Clear();
                        Response.Buffer = true;
                        Response.Charset = "";
                        Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                        Response.AddHeader("content-disposition", "inline;filename=GridView.xlsx");
                        using (MemoryStream MyMemoryStream = new MemoryStream())
                        {
                            wb.Worksheets.Add(DynamicSource);
                            wb.SaveAs(MyMemoryStream);
                            MyMemoryStream.WriteTo(Response.OutputStream);
                            Response.Flush();
                            Response.End();
                        }
                    }

**Comment by igitur** [comment] 2017-02-01 09:03
Yes, memory use is a known issue for large data sets. There are no easy workarounds yet. I would appreciate it if you can populate a sample spreadsheet manually (if the information isn't sensitive) and upload the file here so that we have a reference test case.

**Comment by jk-2017** [comment] 2017-02-01 19:17
As a work around to out of memory problem, I am directly saving excel to physical location without doing anything with memory stream. I am getting a different exception now when saving data to excel. There is no NULL data in the dataset. I tried to loop through each and every row and column in dataset to replace hexadecimal value but that taking forever to run.

Exception: ' ', hexadecimal value 0x0B, is an invalid character

Code snippet –
using (XLWorkbook wb = new XLWorkbook())
{
wb.Worksheets.Add(DynamicSource);
wb.SaveAs(@"C:\Work\Grid1.xlsx");
}

**Comment by igitur** [comment] 2017-02-01 19:22
Paste full stack trace, please.

**Comment by jk-2017** [comment] 2017-02-01 19:29
Below is the stack trace and screenshot….


   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at DocumentFormat.OpenXml.OpenXmlLeafTextElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.SaveToPart(OpenXmlPart openXmlPart)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.Save()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.SavePartContent(OpenXmlPart part)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.TrySavePartContent(OpenXmlPart part)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.SavePartContents()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose(Boolean disposing)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose()
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)
   at IIRWebApplication.Reports.RMBWAReport_HTMLViewer.btnExport_Click(Object sender, EventArgs e) in C:\Work\TFS\EHSTracking-Performance\Main\SourceCode\IIRWebApplication\Reports\RMBWAReport_HTMLViewer.aspx.cs:line 452


[cid:image001.png@01D27C7E.775AAB40]

**Comment by jk-2017** [comment] 2017-02-01 21:02
Reg. out of memory exception, do we have stats on what is the max amount of data that can be exported without running into out of memory?

I got over the hexadecimal problem by using Regex with below code snippet...

foreach (DataRow row in DynamicSource.Rows)
                    {
                        for (int i = 0; i < DynamicSource.Columns.Count; i++)
                        {
                            if (DynamicSource.Columns[i].DataType == typeof(string))
                                row[i] = ReplaceHexadecimalSymbols((string)row[i]);
                        }
                    }

static string ReplaceHexadecimalSymbols(string txt)
        {
            string r = "[\x00-\x08\x0B\x0C\x0E-\x1F\x26]";
            return Regex.Replace(txt, r, "", RegexOptions.Compiled);
        }

**Comment by igitur** [comment] 2017-04-05 19:50
Duplicate of #86

**Closed by igitur** 2017-04-05 19:50 UTC

**Comment by iswaryaRengarajan** [comment] 2017-07-05 09:55
hi jk,
i too have same issue once u get the solution help me to do this
