### ISSUE TITLE
Duplicate Images on Workbook Save

### ISSUE THREAD

**Issue by Trickk** [ClosedXML/ClosedXML#731] opened 2018-03-14 13:00 UTC
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.89 - 0.90 - 0.91

**What is the current behavior?**

I add 99 pictures to a worksheet.
I save and dispose the workbook
Re-open the same workbook and get the pictures count from the worksheet and says 198

**What is the expected behavior or new feature?**

No duplicate images

**Did this work in previous versions of our tool?  Which versions?**

No, I try with versions 0.89 - 0.90 - 0.91 and same result
Yes, Works in 0.88

## Reproducibility
Add images and save. I will try to upload later the files

**Comment by igitur** [comment] 2018-03-14 13:01
Code sample? RTFM.

**Comment by Trickk** [comment] 2018-03-14 13:11
**Code to reproduce problem:*
[files.zip](https://github.com/ClosedXML/ClosedXML/files/1811161/files.zip)
[Images.zip](https://github.com/ClosedXML/ClosedXML/files/1811162/Images.zip)

*
```c#
using ClosedXML.Excel;
using ClosedXML.Excel.Drawings;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;


public void Main()
{

           string pathROOT = Directory.GetCurrentDirectory();
            string pathFILES = Directory.GetCurrentDirectory() + "\\files\\" ;
            string pathImages = Directory.GetCurrentDirectory() + "\\images\\";

            if (!Directory.Exists(pathFILES)) Directory.CreateDirectory(pathFILES);

            IDictionary<string, string> Categories = new Dictionary<string, string>();

            Categories.Add("Alergia", "F");
            Categories.Add("Alzheimer", "G");
            Categories.Add("Disfagia", "H");
            Categories.Add("DRM", "I");
            Categories.Add("Epilepsia", "J");
            Categories.Add("Faltering Growth", "K");
            Categories.Add("Metabolics", "L");
            Categories.Add("Oncología", "M");
            Categories.Add("RENAL", "N");

    using (XLWorkbook book = new XLWorkbook())
            {

                IXLWorksheet sheet = null;
                book.Worksheets.TryGetWorksheet("Cuadro de mando", out sheet);
                if (sheet == null) sheet = book.AddWorksheet("Cuadro de mando"); else sheet.Clear();
                book.SaveAs(pathFILES + "\\cuadrodemando.xlsx");

                sheet.Cell("A1").SetValue("Id");
                sheet.Cell("B1").SetValue("Entidad");
                sheet.Cell("C1").SetValue("Fecha");
                sheet.Cell("D1").SetValue("Contenido");
                sheet.Cell("E1").SetValue("Dominio");
                sheet.Cell("F1").SetValue("Alergia");
                sheet.Cell("G1").SetValue("Alzheimer");
                sheet.Cell("H1").SetValue("Disfagia");
                sheet.Cell("I1").SetValue("DRM");
                sheet.Cell("J1").SetValue("Epilepsia");
                sheet.Cell("K1").SetValue("Faltering Growth");
                sheet.Cell("L1").SetValue("Metabolics");
                sheet.Cell("M1").SetValue("Oncología");
                sheet.Cell("N1").SetValue("RENAL");

                sheet.Row(1).CellsUsed().Style.Font.SetFontColor(XLColor.Black);
                sheet.Row(1).CellsUsed().Style.Font.SetBold();
                sheet.Row(1).CellsUsed().Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                sheet.Row(1).CellsUsed().Style.Fill.SetBackgroundColor(XLColor.LightGray);

                sheet.Column("A").Width = 6.43; sheet.Column("B").Width = (130 - 12) / 7d + 1; sheet.Column("D").Width = (400 - 12) / 7d + 1;

                int currentRow = 2; book.SaveAs(pathFILES + "\\cuadrodemando.xlsx");

                while (currentPage >= 0)
                {
                    string currUrl = String.Format(formatURL, Project, Group, startDate.ToString("yyyy-MM-dd"), endDate.ToString("yyyy-MM-dd"), currentPage, Filter);
                    Console.Write(currUrl);

                    try
                    {
                        JObject json = JObject.Parse(File.ReadAllText(pathFILES + "\\menciones-page" + currentPage + ".json"));

                        totalResult = (int)json["resultsTotal"];
                        totalPages = Math.Round((double)totalResult / 5000, 0);
                        maximumIdInResult = (long)json["maximumIdInResult"];

                        if (totalResult < 5000) currentPage = -1;

                        JArray Results = (JArray)json["results"];

                        foreach (JObject mention in Results)
                        {
                            sheet.Cell(currentRow, "A").Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                            sheet.Cell(currentRow, "A").Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
                            sheet.Cell(currentRow, "A").SetValue(currentRow - 1);
                            sheet.Cell(currentRow, "A").Hyperlink = new XLHyperlink(mention["url"].ToString());

                            sheet.Cell(currentRow, "C").SetValue(mention["date"]);

                            sheet.Cell(currentRow, "D").RichText.AddText(mention["title"].ToString()).SetBold().SetUnderline();
                            sheet.Cell(currentRow, "D").RichText.AddNewLine();
                            sheet.Cell(currentRow, "D").RichText.AddText(mention["snippet"].ToString());
                            sheet.Cell(currentRow, "D").Style.Alignment.SetWrapText();

                            sheet.Cell(currentRow, "E").SetValue(mention["domain"]);

                            string imagename = mention["queryName"].ToString().ToLower().Replace(" ", "_");
                            imagename = imagename.Normalize(NormalizationForm.FormD);
                            Regex reg = new Regex("[^a-zA-Z0-9_ ]");
                            imagename = reg.Replace(imagename, "");

                            sheet.Cell(currentRow, "B").SetValue(mention["queryName"].ToString());
                            sheet.Cell(currentRow, "B").Style.Font.FontColor = XLColor.White;
                            sheet.Cell(currentRow, "B").Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Center);
                            sheet.Cell(currentRow, "B").Style.Alignment.SetVertical(XLAlignmentVerticalValues.Top);

                            string ImageLocation = pathImages + imagename + ".png";

                            IXLPicture preImage = null;
                            if (!sheet.Pictures.TryGetPicture(mention["queryName"].ToString(), out preImage))
                            {
                                var image = sheet.AddPicture(ImageLocation, mention["queryName"].ToString());
                                image.Placement = XLPicturePlacement.MoveAndSize;
                                image.MoveTo(sheet.Cell(currentRow, "B").Address, 2, 8);
                                image.Width = 128;
                                image.Height = 28;
                            }
                            else
                            {
                                var image = sheet.AddPicture(ImageLocation, mention["queryName"].ToString() + (sheet.Pictures.Count + 1));
                                image.Placement = XLPicturePlacement.MoveAndSize;
                                image.MoveTo(sheet.Cell(currentRow, "B").Address, 2, 8);
                                image.Width = 128;
                                image.Height = 28;
                            }

                            sheet.Cell(currentRow, "B").Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Center);
                            sheet.Cell(currentRow, "B").Style.Alignment.SetVertical(XLAlignmentVerticalValues.Top);

                            JArray _Categories = (JArray)mention["categoryDetails"];

                            foreach (JObject cat in _Categories)
                            {
                                if (cat["parentId"].ToString() == "4691069")
                                {
                                    if (sheet.Cell(currentRow, "B").Value.ToString() != "") continue;
                                }
                                else if (cat["parentId"].ToString() == "4691084")
                                {

                                    string colCat = Categories[cat["name"].ToString()];
                                    sheet.Cell(1, colCat).SetValue(cat["name"].ToString());
                                    sheet.Cell(currentRow, colCat).SetValue("X");
                                    sheet.Cell(currentRow, colCat).Style.Font.SetBold();
                                    sheet.Cell(currentRow, colCat).Style.Font.SetFontColor(XLColor.AirForceBlue);
                                    sheet.Cell(currentRow, colCat).Style.Font.SetFontSize(16);
                                    sheet.Cell(currentRow, colCat).Style.Fill.SetBackgroundColor(XLColor.BlizzardBlue);
                                    sheet.Cell(currentRow, colCat).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                                    sheet.Cell(currentRow, colCat).Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;

                                }
                            }

                            sheet.Row(currentRow).Height = (50 - 12) / 7d + 1; sheet.Row(currentRow).AdjustToContents();
                            currentRow++;

                            if (currentRow >= 101) { currentPage = -1; break; }
                        }
                    }
                    catch (Exception E)
                    {
                        throw E;
                    }

                    Console.WriteLine(" -> OK");
                    book.SaveAs(pathFILES + "\\cuadrodemando.xlsx");
                    if (currentPage == totalPages) currentPage = -1;
                    if (currentPage >= 0) currentPage++;
                }

                sheet.RangeUsed().SetAutoFilter();
                sheet.Columns("C").AdjustToContents();
                sheet.Columns("E", "T").AdjustToContents();
                book.SaveAs(pathFILES + "\\cuadrodemando.xlsx");
            }
}
```

**Comment by igitur** [comment] 2018-03-14 13:12
I need the simple possible code sample that reproduces the problem, not half of your codebase.

**Comment by igitur** [comment] 2018-03-14 13:13
From the issue template:

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```

**Comment by vbjay** [comment] 2018-03-14 13:15
Here's a tip. Base 64 encue 1 image. Store it in the code. Add 99 copies of
that image to the sheet. Provide the code.

**Comment by Trickk** [comment] 2018-03-14 13:27
**Code to reproduce problem:**
```c#
public void Main()
{
    string base64String = "iVBORw0KGgoAAAANSUhEUgAAAMgAAAAyCAIAAACWMwO2AAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAXEQAAFxEByibzPwAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC42/Ixj3wAAGxNJREFUeF7tnYdXW0e+x9//s8b2JptNdpOX3bSXt9mTrLM5OXED7LjFsR0ncYltehEyzWBCkQRICBCYYooBg+mmm2JjoV5Qp0gCAUIIAcLve3UvWAgEyDF5iZfvmaMjzcyd+pnf/ObqCv7r2a52tQPaBWtXO6JfCaxl5/LSonNpcWk1LC4uLS8vU8nrtLTkXA1Op9dsRLFuOanYZ89wzZp4rwVsUBEa5R65zYCW4FqPejcM3rqDePds3gaHSF1cnhizi/om+1vGe5vGBttNSsH0zKRj5UIiGy4nP5KBqHTj8gi55yQDRKW9qHYWrIX5RfusQy0a4SXURxzjfvfx7TPvJp55N+Hs35LC/DkTY9NUvrWaNjvY0SI2TYrXHLqskq2cnVmk0tZKK7Ny6TI2TZITIyu6LbNM2Mn4wU4zL05DXp4fL7VZN77cMjFfzlRwbyrYNDE7Rtr1YAyRetUsFYM2bCfQJLhWKZrBteJ+Sy6ujfZyLU3MiRFV5QxrpTNYV64mUFpaWu5pHEdriXrRHbrMNDZHpa1ocdEpHrDwkmWoLjNMmB40lHqNn3Z9KO3GECNkKDNSmBc7fC9neGpyAZkddmdZhpwoMFqEJtXmaWwzRPx6WacXC5OlOTHEaJONxPvmUh2V/KLaEbCwaOz2BWGfKvZc4fn3b596J/7o/uhDe6KO+NGO+sUgBOyN/e7jn40GC3XBWk0a7awQWVaoEq+ZofKMIFFzhQFDTyW7CSuVHa7KDFVkhw1nR4kspnkyvrdpPDd6BJdnh6syggS2aS9gmebzE6TsCDVqyQpTtpQbEKkGrNEGFEuUuRKQAaWtBLl7EjtczYnQSJ8QfeF3mfE+M4TKjDLdc2aFKpjBUqDApSmrctQ263O20LuHlSNoLSoiuhOuGtPPUmku2WaX6ngadpSCESRBAxBQFCNYwggSM4MRg4FS8GKMzeXUQM3ZFnJvirPDh5HEiVCXpsmtUxsPAuplBRPjjBIQkB99x9oY1axpgK96+WAtOJYa7vRf+Cj59Dvxh/ZE+u+lg6TDftGH90ThIxlA2OVP002GKeqatbIY7Rj9jBsiYjleHyKGL0Qw2GGkkt2kEs1gWNNvCDG+OXSxxUxZrL6WccwNeS0rTOjN4FnM84XJMmaINP2GAPhiiBGpU9pYYbL0YAFMwmpIu+6yDa4AO+GelB4sZISIFHwCrKHuCUxM+nUBmXNNNpeBQUVoLTl5TSWGpQVqtYCG9moDWktmwBujwUYmQTNTC9U5apaLS6Rm3BDCSnkUzgyRcKIlw2JqE7DPLfESJYxgMZrBCpGWMYZhmcgkd81MLXLoUnIEXH0kWph2XZAdpqxiq727KlvrZYIFP+Nh+eCPn6adfCvuKMmTG0zuwSewXEMjAzdauZXKsaKXDha6sLCwPD3pmJpAmCeDyWCryB52GRsBI0jES5IiZjWVyDnpWHAQTgl/BSzMPcqU86dWs02aHJ21BqwQlICGESYwXKiRUj3aBCy4Ox01I5lhSvQRFzIBZZRI0DOxWjIZFEPTgh7z4gLlG20TrNo8NYwfKoWhbSnXt1bo0DC0nxkkZgSLNlzM29RLA8tkmE65dPebd265kKJ5kOQRfAQLYy3IClPcZSmxdqlMLu0EWFSam+DcuCZA5gJLXJQiQwyVtlYeYI3pnlsdyDHvbLijdSUJ0TZOhPbxQ2rmNgFLP2xlhAhZBNZ8wM2JEetVVnK/cxe8dfdWbQcsrdSaGUGYT7DODBVJn0za7YtFqYqssGFclROhreFqqKy+6+WAJXykuvwJE8SAKneAvAWfwCKnARMPj6G1Qr/sNqe/DliYpJr852AV3pYhhkpbKw+wRlRrwILg/JF9QVE5kfqB1i3AcjiW4V9mhxF9wVUZwQJh/wR5yebaDlhNJTp4gWgJO1xTxlKAe0Q2lGrhaZEDkhejxeZOZvZVLwGshqL+8x+kBO6N87bxrYQoZCADdskf/5m2DbAEadeGStMUjDBiuLFe2RGKp51mKt9vHyy1p/9bk6ciy8FrdrRELSXOkpA3sKbM87mxhHtO9iUzSujtcOehLcEyKKw5MaLMEEVGkJgVKkbLyfhpy0JenBTnj9TrfByAHhRpXszR+qVgVTDbT70d77/35jqMngeKJ79oGCoi7I0+83ZC1Mm8yTFqWD20ChYx39dF0gFLUTJxbEFXifmIkmpW5uM3CxaahFf54NS0ZX7a7Jgcn8exEY4aK1xCGJ4gIc6SdYXaxa2c93G9LT2IT2KKqu9zhxdWvKjNtSVYPfVjWaHY8oQwWrxbEof9ebEVzGHS08IU5NFVw8KN7wptrl8EVlFK88k344/6bbL9ETwhw5E9NEZIlXRQiyDn6zXi0TH1xNLCxtPjDhZ8C6POpldYSXoQD0OdGyeGv4ycv1mwUDVCbqy0MEnGuyXlJUrZNBF1gyBYgrZVszXu/qI3sMa0NtRIYOpqYX+TccMWrtfmYOF9GVPJxg57Q4BWNZboqQSXDKrZzHAMqQQrOY826r5FbF8vDlb7vafHXqdvYqtgpQL2xl7/gtlZxRf3q6fN270vshYs2Zjrhkpf87hr7yf8raxQ4jCMydDKrL9lsGAM2BFquIbkPTn0iBUmaKsyaCSzU5PULTdS3sAa0c4yg2WrYA12bHeONwdL9tSSFUHcIARVmZFC48iam7EYAnIZ4FoMTkGSdNJILGOf9IJg6eTjV79gBHinyn8v/fgbMTWcbuSkrtm2PMAiXWCHw9lcbmBHaFxJBEkw5jiuY3S2BMs248U07iBYBFvcm+L8eGlGEOmtE6eQ9CDiHgSV201eLZZuNs114wplourV+59banOwcGjIidQhCX3PjhbqFLOwUjqlFWEErwprcSqBHSpFwCFRN+x5o2dLvSBYZYw22CrYJA+eyABDdfmzdMmAxttmt7k2BAuyzS7U5eo4LrYwylmRosYiPd6T8+0O1kCLyR0s6/TGDu/O+lg3BOJ+i8lgx2tWtAgXEhMZLClJl9tnPS/3BpZpdA5Gjrz1BUpyYqW2ddduqE3AskzOlzCJ++xIclXHB/35CRLideVNViSxM7iCAOaW3+XzbvgiYAn7VN99kIqTnQdPCEDtiF9M0sVSpYi4i/1i8gYWZB6fK00jvkUh+8wIoTYdD7CwZXAiXbYtSAyDserse2jnwCLdbaOe2mK660azQ4mDPaDBjKIiMn5V3sACRtVsNQkBWogx2eZuuAlYMEgZQUQLyaED61irHoFw3olb8K6xDRaDNofDNxvhM1gzFlvi90XH9yUc2hPhQRUC/HTaybwR9Yu4e6vaBCxII5/JiyW+2iPyuJYy0fm1YKlEU4wQTIPrMBUsvp+rJuM9tNNgrbZ82uIoTiW+0Ex17T7MEMGwYM1RyxtYy8vL4r5JHP4RT3aTEyNSrr12Q20CloJvIc05yky99hQjUJwmL05TuAX5nWTUSCxdZMNEoN55+w6DJRfov/5z/OE90R5IIRzxo1348LaoX0Vl9S7MX2laS0fV0IbPcmwOFiQcmMiKIL55RTYyeIBlsy6WMxVYeTjXgBhWmKShWLv6FfWqkK3o9q8BFiToNmeGEt8Zo5CsUMVd5ppvEbyBBdltS9U5am6UgfwiDwaGF694WGGwmNZ43Hqlta1KN7XSR29gLTicLZUGNIAYYSzLG3yYc6PBbhqxrQZUDd/uQaGGOBi5rCzabJ3yzX/3DSyncxneFVwoD6TIELgvroLVtslzP6tyLi3/9DmDQ6t5MbCczmc9D8YwatjpNgQLgkng0GTZYcrUa3wMEOa7NF0Jn6ztnqG3ydjfYnzUOFZ/R82KIAbuVwBr3rZYlU0cD8lCssOVnbXEwxSkNgELwqGsJFXNidTiWnQW1jqT6I6s/o52NfCSpPAQBttN5CXewMLqyomRIh4V4bWMpfD25JVaMoNakI2sVDHk290s38Cyzzm+fT8JlskDKQTQFn+ucGbCE4INBbDC/TkFCQ0vBhY0Z1t8wIMrQHz5sCFYxNNL/WYuXZYbbSCLgv3HUYg4RRMPMBFXAQJi1bo2hZ0GCzIMW9k0CXlTG69culIp2vpLaFKjmtmaHOLg4vK3YLqE6A43UrcaEJ8bPVLJVoFg5PcGltlgJ40QWYvw0aS3RxhGtbNEX1Y8rd4m3073voE1NztPPgPjQRUCvK7avG4q31baHKyJMTtGKi96FEwUxJhwGKYS1mp6wlHOVOXTxrhReryClQnjc7BIqSVTfc0mZshQXvRITqSW9EzxBoS5f8yN0ufRRptKNgYLU1XGUhbQTdxIAyrKiRWRk7deg20mZMuNNKA6NH59y7GFubpGNKY4biorSkgCBLCayw35MeO4CnzgzejaL7AhHFz4jyZKUpXIwI3SsSPUxINTCBFqlIaGYW30NRrJr/wAFjtamB8zhuoK6Eb4TOTzWBqpFTlzo6hadEqvNxcNw7NcVy9IcAcfbnwA8ibfwBrXT4Kh9XcZ/PfSrxxgaKSjVL6ttDlYGJTBLjO/awKnXEG3xTrtdXc3j9qHuolsQ10T4gGL3b7xfMv5U8g20GrqrBltrdA3legQmkt1rZV6xPQ3GQc7TahOP2zdsD2Li0vYF9AStAoVyQYnPZ7/XJVpdA7Z0B6y8etbPmWe53eb0Riigx3mgVYj6fnBbMC8kX3BtXhjm934Fsmo1ga7OPDQ1FEz0lKuB46d1Yb+5nFBj0XyeBKGnMwGgy0dmCQrEnRPKIemHa4HeywTDvdavN06hpBEZkMJCKiXStiefAPrSbvMRZInWIH74llh96hM29DmYO2clp3EsysA1z7nnLcvLjqoZ9V/j4KRc9id6I7Tt+ParyTfwKrO6QZD68Pp11J9AguKOsYt/rmF+rCrV04+Wqw2KSukcn3IDK3urh2iMrlJJRqp5HTU8no9Q96ji/+bQvs6ty6/xyOphtvVXvWUun5Xv1v5BpbFNKeRWtaHYZF50uj5qxKo8/7QpQPpoUfZ7iHMnx16JPv4m/Sz790KOZJNfHRLvfYlM+VKKXX9rn638g0s2dOpe9maymwVXt1DFdsAT5DK5CaTYWqwTS7oHvYI/A7F5X9lJP9QPLQ+qVMpG/ylvz3a1f+7fAPraZcpM1SRFUb8Tsgt4Chubqlc80zPloo8xr2T3ER92NUrJ9/A0imt5O1E8qbZauBEaB8Uabb/69lfeCrUiEcb7/Trh6m7zDun/mZJQ1Gffc7np5E8pBSN1PP6zSNTGunYg4JHE6Nb38XuaRA1FQ/Ybb+06lXZZuwNd/okA2u+Nl1aWHpQ0NdbL6I+vzz5BpZ12gGM0le+GF8NrBAZL0FpGN7uo3zbBEsyoGksGFz/BHNdXre/H72xeID6vGOKOs454kczjzz/Ye3E2HRzyZOuGuqkIuxTNRQMGnWT5EdvupfVdeb19P5mqahPFfxVpk629V3sq/9mHdoT6Y7gkzZ5Xf6j2SnClx1RmXDQMeo3/sVvf6u0obiP+rCimQkbXNuOav7y8jNhr6rt3qDDsQiw4OaWprZSmV6efANr3r7EdD0J6QEWQl70SF8j8RP17Wg7YE2bZ4MPZ539E7MopQVDQEbarPNPHsrSb5QHvEZrKXuiFOiVwpFFx+Kyc1klHtXJxydG4NXJumqHVELq0RSLcUbYM9xdKxjqUjpW7qCinMdt8qFOpd1O3IdUCg1gRad8Pt9jusneBtHVzzNO/CVuYvT5o3m9DeKjfjEn3opz2BdQSERgzrdvZD4sp46xMKIoB6WRH6Epo/VxqzT9WoX/3ptomGl0+m56G/m3BRxzC3BA0QzbzDw6O9guR7PRI/LCMH/Oib/EovHkRyj2XMHJP6YU3Sb8B/Q9YF8cSgZb4gEN0ZjZ+aFuJUAcU5vPvJsQsC8eBYIbndLY3yRBTiRVZLZjiIwjU5c/Sz+8J7Kzmo82VGZ1oBlkFSrRKAYK1JIfLUbrYCfRKji+ZMz25RtYCw4nL4l4cNuDKoSsMGVVlnbOy5doHtoOWF33h07+Ne7Y6zfPf5Q8PUnYQmwlufQHsecKMZ3HXo9pufukOKUp6GCWnK8fUZsjAjlNJQNP2+Ws0HspV8vop/L7WyQY2by4B5cOZMRfLAw9lF2Y3IQpxKLnJTRc/MfPnKgak8GC+U78vjj+u6L484XkuUHyRIePKVdLz3+QfPKvse5/YwLbU8BrMQGvx8ie6uRP9affTgjYe/M+t2d5eRnWK/VKWeKFothvCweaJE7nMrZsRmg1zijo7NE9tKedcgABCyEd1GJjKkxsvHIgHVWj8UCcFV6NZkcfz0WzUVHEMa4HWKlX7wbujwMQgA/QH94bhRorMzsuH0g3jViwrs5/kNJQ1I99LfCNmCN+MXnx9UAk5hTv+pfMwqQm0YCGdjKvjNGG4ULJR/ZGZkdUgfuo49yk70tQPhjCoNG+zr19qQQl22cX8uLqr37ORAuDvsoU9/v2G0PfwIIEPRM5EVoPqsjAjtC0VRmW3P7qizcBrE2eboCWnc/YtPuxZwtK01qBF3oFRApvNQb+MfZxi7S+oDfwT/TuWmFPneDYvoTG4n4gdegPkTAVWP2iXlVhUoP/fjrGaNI4893HKd+8f2tEY06/XobhFnQrsYce3BORm1CP5St/qkMGXnw9cl746HbwQRZW9vWvMn/8ZypmJf5cwfE36e4WqyT94dm/J/7wSWpxSjNclm/fu4WPhUmNNqv9xkFm/Pk7WOX0swUn34kb1U4kXiw+8VYsELzH7gzcG8fvVJQxH/q/ToNp6akVBOyNzY6sxuYIyMAuzCpOM0f30ejf8OzWedqJfA+wUn66e+LtuIv/m0I/nQuU/V+jiQfU7Og69AW9kz7Rfr0/CSsHl/z4z58P+0XKBQacso/vT2JFVNlnHSrp6PE/0xnB99DTkEPs0+/EA0H4cIGvRwcdzDQZpq9+xqSfzsfS+va9RLAIU3f2/STsntjosZIrMrb7RTApn8Eyjc7lxVE/9/YI8L0ygkTix1s4HBB2Lpj0topBb2ChMz/8I40RVAEbDsOO1UzujDBLziUn1iUsVk+9eEw98e3fbrNj7qcHlV/9nEHser2q+7ndKZdLLnyQeu0L5siw6coBBjhAmTWcriN+dICV+H0Rljs2MkTCRz70h6h7me0a2Rgr7B4CFi4cuNLUZqTGfss7/uZNd7AwSVc/T+PSa7//x8/x5+6wQitxvE39qRxTe/rt+PSgSvjpVZyuMH+2SjRy8eMUkIqr7nO7AvfFA6yKzA7srf1NYqAc8Fq08BH17Jq4X1vN6Uq5Unrhw1R0E5zRTvM8wEq+XALj3XL3Mdi6/m/W12/FEmDRao/+MXpMP4kVgjVWeKsBOUP82cAOb1Bs4L4ELE6818jHUCDAWlhYSr5UeuGjZNg5xIO2qBO52C5Pv5bWVNyPmCsH0s59mKSRjV/4n9uw3IiJ/YZXlt6BN9uXz2C5HvAYyXU9d+YBFgJ2ybx4uU7u6W77Kgw9ZhcYYSLR8+8/+RljHXsm77uPb1stcx1VQwCrveopIIPZu/hRKkaccGwtc9ikor7mogRWaPUPn/wMqwOwsOsh5l5WBywWrAXoObgnUsEnvBlBz/Ahv6jL/8p4WP4EQwl3DTPkvy+GEVqJ1MSLRajdHSwMNKZhqHsYJuHyp2nwY2in8rGg9cPGM+8mnnon7kFBL0qesdhgJC58mIx9Clc13unHrJNgHX8rFptvGbMNHSQPAbDxp99JuPYlE++zwqvRGBiVDcC6VHIOXoF5lkO7f3x/IogXD2iR//C+KHiE2HYJsJIbkTPoIAu04Q0JVnEK8dXZc7AcTpjSb/4eP+46c6CD2HZhL4/tT8QQIebyp6lYzDqlmQDrwh3ExJ7debAgvdKaH6uEU5W6AVsCePe8BPmGD1FtU3Co4W2AFXgS8M3hARzeEw1Ps6dOhGXKvVnPCKmCB91eOYjMXbXCr/ffOuRHgII9BROJGULOn75ggSeAhdk9898JyHk3rRX7Ao5mmOBTb8dFBuYCUIXAgLowl013HsNpgxuLmUu/XnH+o9v1d/qvfJYB27YK1oJjCYVjv8NBFXslCMMOCLCO/fmmUWfhxtZhW6zn9T68OwgDgAMH7Ae2QmxbKZfuYp+C/1ea1gKOcYyAPfvuvbSIo9yGoscGlRlHRZhVuJU3vsxCFwBW2FE2OuV+KoT5DHgjZmF+EbXDXmIEhnqUMGBH9kXBnSq81QSTQ7ityHmGB9e+v1EMp/sUIuOJSGyFKBCD6XQ6s6PuB+xDw7owYof2RFw+kAGCgVfwV1mNRQNoMyOoCjb4xF/j4U7gWqzwyoweohHb1ouABQl7zdxozYYbIkJ2mJITQ/x+fPUpDp80ZbLCu6rmUJs65sDlbLXhfV3eo4ijeeFHOfBDZYNaxBjUZhyXYNjg3OAjjAFGAQMUGZiH7QaRjOAKuL1I6rzPjz6eL3W552UZ7REBuSgE4OIgiYkPO5wTepgDHwWpmE44ZCEHOZH+uUiyTVPfVs1Z7fCKanK6gX4d79GD/F5EwvagHBzm4b9jK0QhKIpLqyW32uzw+4gJD+DA8VJJx2Bl8QZeP5Jay55E+xeEHGTDrYHBwJYafDA7KjCv8HYTeM1PbIC1gOUjKnbpbkYrjBZQwPsnrTI43eTxMyuyOuwIFxtozIlC4mlv4twjiDmRj44r+XpEYsEg0miYRIEVLMLwDHYqEI/WGg0W+OakeZbzDehI2EEOVg4+4sCUfOkueQiFE9lWwceb7esFwXLMO+t4muyw4fX3tMjACJYygyUPKwyjmllfn8Pf1SugFwQLAjGFSVJsiOtvxJMB8cTjvDeGOqpHx7VzYzob+azZrv4T9OJgQWrxDPHjRrDlet5+fSAfr8aOmRmqyAge6ms2Ai8Eo94+MW53bu9Hvbv6PeoXgQVpZdbceMkmdgsBScSdCNfNCDKwQuW8W3KrZeOnb3f1CuiXggWN6ue4cdKsUAX5m5BNAggj8HL9EU7eLdkuWK+wXgJYkGlkrihFxgwVAS9v7rx7YARLeEm7YL3KejlgQUtLz7rqRnlxqrTrAvdf/m8YdsF65fXSwIKWlwnTVZMznEeXEQ57iJz4xe1Gfv0uWK+8XiZYpHDWm5qYL0mVc4FXKPHTYddfuyf+RCJ2SdKS7YL1yuvlg0Vq0eG0WRf53abCZCmXrsiMFDJCiL9zn3aD+Dv6u2C98topsFZF/tOfGYtDLZkRPpp40m7saxrvazQ+7TLPb+/hrV39HrXjYO3qP1O7YO1qB/Ts2f8BxBp/clwIQwMAAAAASUVORK5CYII=";
    byte[] data = Convert.FromBase64String(base64String);
    using(var stream = new MemoryStream(data, 0, data.Length))
    {
        Image image = Image.FromStream(stream);

        using (XLWorkbook book = new XLWorkbook()){
            IXLWorksheet sheet = book.AddWorksheet("Sheet1");

            for(int x = 1; x < 100; x++){
                var image = sheet.AddPicture(image);
                image.Placement = XLPicturePlacement.MoveAndSize;
                image.MoveTo(sheet.Cell(x, "B").Address, 2, 8);
                image.Width = 128;
                image.Height = 28;
            }

            book.SaveAs("C:\\images.xlsx")
        }
    }
}
```

**Comment by vbjay** [comment] 2018-03-14 13:40
var image = sheet.AddPicture(image);

Use different variables.

**Comment by igitur** [comment] 2018-03-14 13:46
I can't reproduce the problem. Please try with the latest development build at https://ci.appveyor.com/project/Pyropace/ClosedXML/branch/develop/artifacts

**Comment by igitur** [comment] 2018-03-14 13:48
This might be a duplicate of #673

**Comment by vbjay** [comment] 2018-03-14 13:49
I'll bet you're right.

**Closed** 2018-04-27 14:14 UTC
