### ISSUE TITLE
Exception in ws.Columns().AdjustToContents();

### ISSUE THREAD

**Issue by sritipraz** [ClosedXML/ClosedXML#1412] opened 2020-04-28 13:48 UTC
**Version of ClosedXML**
0.95.2

**What is the current behavior?**
AdjustToContents()  works fine for a console Project but gives an exception in AWS Lambda Project.

**Message**: The type initializer for 'Gdip' threw an exception.
**InnerException**
{System.DllNotFoundException: Unable to load DLL 'libdl' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.Libdl.dlopen(String fileName, Int32 flag)
   at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233052
    HelpLink: null
    InnerException: null
    Message: "Unable to load DLL 'libdl' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)"
    Source: "System.Drawing.Common"
    StackTrace: "   at Interop.Libdl.dlopen(String fileName, Int32 flag)\r\n   at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()\r\n   at System.Drawing.SafeNativeMethods.Gdip..cctor()"
    TargetSite: {IntPtr dlopen(System.String, Int32)}
    TypeName: ""

**Comment by Pankraty** [comment] 2020-04-28 13:52
This is a duplicate of #1283. The reason is that `System.Drawing.Common` is not supported in AWS Lambda. Here are other people suffering from this: https://forums.aws.amazon.com/thread.jspa?threadID=292721.

**Closed by Pankraty** 2020-04-28 13:52 UTC
