### ISSUE TITLE
Cannot save workbooks

### ISSUE THREAD

**Issue by harrewarre** [ClosedXML/ClosedXML#162] opened 2017-01-19 12:41 UTC
When I try to call `SaveAs(...);` on any workbook I throw at it, it will throw an exception at me with the following text:

```
{"The attribute 'left' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]\r\nThe attribute 'right' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]\r\nThe attribute 'top' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]\r\nThe attribute 'footer' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]"}
```

It breaks on new workbooks created in code, existing workbooks from disk and blank workbooks.

I tried running the hello world sample code and that also crashes with the above error.

**Comment by vbjay** [comment] 2017-01-19 12:49
Please search issues before creating new ones.

**Comment by igitur** [comment] 2017-01-19 12:50
Duplicate of #152

**Closed by igitur** 2017-01-19 12:50 UTC

**Comment by igitur** [comment] 2017-01-20 09:34
Disable validation on save by using `SaveAs(..., false)` or set your thread to en-US as explained in #152.

**Comment by harrewarre** [comment] 2017-01-20 09:38
Aye, my bad, I should have look a little closer at the issues. Thanks for the quick feedback!
