### ISSUE TITLE
Different file size between ClosedXML.Excel.XLWorkbook.SaveAs() and Ctrl+S in Excel

### ISSUE THREAD

**Issue by SomePrettyUsername** [ClosedXML/ClosedXML#1903] opened 2022-11-02 17:05 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.97.0

**What is the expected behavior or new feature?**

The resulting file size of one of your simple examples is about 7 kb. If you open the result file in Excel and save it again, the file size will increase to 9 kb.
Some programs, such as adobe indesign, do not work with excel ClosedXML files, but start working after being saved again in Excel.
What is the difference between ClosedXML and Excel files? What information is stored in the 2 kb difference and what can be done to add this information manually?
I tried to compare workbook/worksheets objects that are obtained when reading 7 kb and 9 kb, but I did not see the difference.

## Reproducibility

1. Execute code
2. Look at the file size, it will be about 7 kb
3. Open result.xlsx in excel
4. Press ctrl+s
5. Close file
6. Look at the file size, it will be about 9 kb

**Code to reproduce problem:**
```c#
        public static void Main(string[] args)
        {
            var wb = new XLWorkbook();
            var ws = wb.Worksheets.Add("Contacts");
            ws.Cell("B2").Value = "Contacts";

            ws.Cell("B3").Value = "FName";
            ws.Cell("B4").Value = "John";
            ws.Cell("B5").Value = "Hank";
            ws.Cell("B6").Value = "Dagny";

            wb.SaveAs("Result.xlsx");
        }
```

- [x] I attached a sample spreadsheet. 
[Result.xlsx](https://github.com/ClosedXML/ClosedXML/files/9922614/Result.xlsx)
[Result9kb.xlsx](https://github.com/ClosedXML/ClosedXML/files/9922618/Result9kb.xlsx)

**Comment by jahav** [comment] 2022-11-02 22:48
xlsx files are basically zip files with a lot of XML inside. Feel free to compare the content through 
* TotalCommander and WinMerge https://github.com/ClosedXML/ClosedXML/blob/develop/CONTRIBUTING.md#comparing-the-internals-of-excel-files
* or through [SDK productivity tool](https://github.com/OfficeDev/Open-XML-SDK/releases/tag/v2.5) (it has compare two files option)

You can see the extent of differences.

Although there is an official standard (ECMA-376 or its ISO/IEC 29500 equivalent), it is rather inadequate and only a starting point, and the only real standard is what Excel does. Can it read file correctly? Rather dissatisfying definition of correct, but the best we have. In this case, Excel can read it correctly, so I believe it is written correctly.

Why do some programs don't read it correctly? No idea. I have seen various kinds of errors (e.g. one program refused to parse elements that used xml elements with a namespace prefix, only prefixless elements with xmlns worked).

Basically errors can be 
* At the producer (i.e. ClosedXML)
* At the consumer
* At both

It is likely an difference in assumptions of how should the format look like/be parsed/what should be present. I have no way to check the result since I don't have access to adobe indesign and it is not an authoritative source anyway.

You can try to pinpoint a difference by step by step modifying the xmls inside Result.xlsx with the XML files from Result9kb.xlsx (xl\worksheets\sheet1.xml being the first candidate). It will however likely cause a file corruption, because some xml parts rely on other xml parts and just modifying one can cause corruption (e.g. styles in both files are different).

I am closing it because 
* I believe file correct (the validation of Open XML sdk is called by default and Excel can read the file)
* there isn't a reproducible scenario
* programs other than excel are not an authoritative source. There is no conformity standard test suite and no idea how well they implement the standard.

**Closed as not planned by jahav** 2022-11-02 22:48 UTC
