### ISSUE TITLE
Range error on save of updated file

### ISSUE THREAD

**Issue by valkyrienc** [ClosedXML/ClosedXML#678] opened 2018-02-02 12:17 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.92.0.0

**What is the current behavior?**

Open an existing file and update specific cells with new data.  On Save, get the following error:

    Specified argument was out of the range of valid values. Parameter name: The cells A4 and X3 are outside the range 'Delinquency!A3:X3'.
    at ClosedXML.Excel.XLRangeBase.GetRange(XLAddress newFirstCellAddress, XLAddress newLastCellAddress)
    at ClosedXML.Excel.XLRangeBase.Range(IXLCell firstCell, IXLCell lastCell)
    at ClosedXML.Excel.XLRange.ClosedXML.Excel.IXLRange.Range(IXLCell firstCell, IXLCell lastCell)
    at ClosedXML.Excel.XLWorkbook.PopulateAutoFilter(XLAutoFilter xlAutoFilter, AutoFilter autoFilter)
    at ClosedXML.Excel.XLWorkbook.GenerateWorksheetPartContent(WorksheetPart worksheetPart, XLWorksheet xlWorksheet, Boolean evaluateFormulae, SaveContext context)
    at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
    at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
    at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
    at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)at ST_6bc5fa72e8174cd4a207b1b253d87b23.ScriptMain.Main() in c:\Users\jdoe\AppData\Local\Temp\Vsta\48f142323f754c1487ca867a1cf952c5\ScriptMain.cs:line 279

This code is run in a script task in SSIS using C#

**What is the expected behavior or new feature?**

Expect save without error or exception.

**Did this work in previous versions of our tool?  Which versions?**

Unknown

**Comment by valkyrienc** [comment] 2018-02-02 12:18
[Delinquency Report.Redacted.xlsx](https://github.com/ClosedXML/ClosedXML/files/1689286/Delinquency.Report.Redacted.xlsx)

**Comment by igitur** [comment] 2018-02-02 15:26
Issue template asks for a code sample that I can copy and paste into a console application and run as is.

**Comment by valkyrienc** [comment] 2018-02-02 18:38
[ClosedXMLCode.txt](https://github.com/ClosedXML/ClosedXML/files/1690424/ClosedXMLCode.txt)
Whoops!  Here's the full set.  You'll need to hard-code some values; it is run from SSIS and receives its values from the source component.

**Comment by igitur** [comment] 2018-02-02 19:15
Can't you produce a simple example that reproduces the problem?

**Comment by valkyrienc** [comment] 2018-02-02 19:39
[ClosedXMLTestCode.txt](https://github.com/ClosedXML/ClosedXML/files/1690602/ClosedXMLTestCode.txt)
How about this?

**Comment by igitur** [comment] 2018-02-03 08:03
Nope, you gave me code with dependencies on DTS. Try again, and paste it into a console application yourself before submitting it. If you want me to offer up my free time to help you, you have to put in some effort.

**Comment by valkyrienc** [comment] 2018-02-05 17:53
[ClosedXMLTestCode.txt](https://github.com/ClosedXML/ClosedXML/files/1696195/ClosedXMLTestCode.txt)

Sorry; it ran fine (as it were) in VSTA, where it was developed.  I've updated the code for a c# console app and it builds just fine now.  You'll still need to replace the values for file & path, at the top of the script.

**Comment by igitur** [comment] 2018-02-05 18:24
Thanks, I can run the code now.

I can't reproduce the exception that you mentioned above. Please try with the lastest source from the git repo.

I do however, get an unrelated exception, which I'll look at separately.

```
Unable to cast object of type 'System.Double' to type 'System.String'.:
   at System.Linq.Enumerable.<CastIterator>d__95`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ClosedXML.Excel.XLWorkbook.GeneratePivotTableCacheDefinitionPartContent(PivotTableCacheDefinitionPart pivotTableCacheDefinitionPart, IXLPivotTable pt, SaveContext context) in C:\dev\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 2110
   at ClosedXML.Excel.XLWorkbook.GeneratePivotTables(WorkbookPart workbookPart, WorksheetPart worksheetPart, XLWorksheet xlWorksheet, SaveContext context) in C:\dev\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 1954
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options) in C:\dev\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 313
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options) in C:\dev\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 122
   at ClosedXML.Excel.XLWorkbook.Save(SaveOptions options) in C:\dev\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 459
   at ClosedXML.Excel.XLWorkbook.Save(Boolean validate, Boolean evaluateFormulae) in C:\dev\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 440
   at ClosedXML.Excel.XLWorkbook.Save() in C:\dev\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 429
   at ClosedXML_Sandbox.Program.Main() in C:\dev\ClosedXML\ClosedXML_Sandbox\Program.cs:line 272
```

**Comment by valkyrienc** [comment] 2018-02-05 19:55
I've just attempted with 0.90.0 and 0.91.0; I get the same error.  If you cannot reproduce it, maybe it's something specific to VSTA?

**Comment by igitur** [comment] 2018-02-05 20:12
Try with the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.92.811/artifacts please

**Comment by valkyrienc** [comment] 2018-02-05 20:25
No dice; still throwing the same exception.

**Comment by valkyrienc** [comment] 2018-02-06 13:23
(I also tried with 0.89 jic; no diff)

**Comment by igitur** [comment] 2018-02-06 13:25
Are you 100% sure that the attached file in https://github.com/ClosedXML/ClosedXML/issues/678#issuecomment-362571620 is the correct file to load and that the code in https://github.com/ClosedXML/ClosedXML/issues/678#issuecomment-363165108 is the code that you're running?

**Comment by valkyrienc** [comment] 2018-02-06 13:25
With the caveat that the code is run via SSIS in VSTA, yes.  :(

**Comment by igitur** [comment] 2018-02-06 13:27
Reproduce the problem in a console application, please. smh

**Comment by valkyrienc** [comment] 2018-02-06 13:42
Probably easier just to say this may not work with VSTA.  What good to have it work in a console app, if that isn't the platform used?

**Comment by igitur** [comment] 2018-02-06 13:43
Because it will help narrow down the source of the problem.

**Comment by valkyrienc** [comment] 2018-02-06 13:46
In that case, I can with about 80% confidence say it's due to the VSTA environment or setup, since this is not reproducible in a console app.

**Comment by igitur** [comment] 2018-02-06 13:47
Are the regional settings under SSIS different to the user's regional settings when running the console app?

**Comment by valkyrienc** [comment] 2018-02-06 13:58
Negative.  Both are English (US).

**Comment by igitur** [comment] 2018-02-06 13:59
If you download the ClosedXML source, are you able to set breakpoints while it's being run from SSIS?

**Comment by valkyrienc** [comment] 2018-02-06 14:09
Good idea; let me try that and see if I can get anything useful out.  Are there any values you'd like me to focus on?

**Comment by igitur** [comment] 2018-02-06 14:48
No, just try to reproduce the problem and paste the stack trace again. It should have line numbers included - so will add some value.

**Comment by valkyrienc** [comment] 2018-02-06 18:22
It's easier to get my six-year-old to do his homework than it is to attach a debug process to VSTA and have it actually hit.  I've linked the reference directly to the source code and have thrown breakpoints on every method that could be possibly called, from GetRange to Save, but it won't hit.  From what I'm able to determine, this is not uncommon but every tweak I've tried has laughed in my face.

Poking through the code (recall that the first method in the stacktrace is for GetRange(address, address)), I found a call for Range that *might* be useful.  On XLCell.cs, line 1804, the line:

var toRange = Worksheet.Range(this, Worksheet.Cell(Address.RowNumber + rCnt - 1, Address.ColumnNumber + cCnt - 1));

Since I'm essentially using just one column, but I've pulled the range of all rowsUsed, could that be what's causing the issue?

**Comment by valkyrienc** [comment] 2018-02-06 19:05
I thought I'd try out my theory that more than one column was spoiling things, but no such luck.  I changed FindRow to this:

        private static int FindRow(cx.IXLWorksheet worksheet, string findText)
        {
            int result = -1;

            cx.IXLCell firstcellused = worksheet.Cell(3, 3);
            cx.IXLCell lastcellused = worksheet.LastCellUsed();
            cx.IXLCell lastcellincol = (cx.IXLCell)worksheet.Cell(lastcellused.Address.ColumnNumber, 3);

            //cx.IXLRows usedrange = (cx.IXLRows)worksheet.RowsUsed();
            cx.IXLRange usedrange = (cx.IXLRange)worksheet.Range(firstcellused, lastcellincol);
            cx.IXLRangeRows usedrows = (cx.IXLRangeRows)usedrange.Rows();
            string address = string.Empty;

            foreach (cx.IXLRangeRow row in usedrows)
            {
                int rowval = row.RangeAddress.FirstAddress.RowNumber;
                cx.IXLCell cell = worksheet.Cell(rowval, 3);
                if (cell.Value.ToString() == findText)
                {
                    result = rowval;
                    cell.Clear();
                    break;
                }
            }

            usedrows.Clear();
            usedrange.Clear();
            return result;
        }

But I get the exact same error as before.  I'm going to keep trying to (a) poke through the code and (b) get the attached-debugging-process to behave.

**Comment by valkyrienc** [comment] 2018-02-08 14:45
I've run the debug three times and I keep getting an unexpected break on the code in Extensions.cs where it's looking for Color.cs; I cannot find this file in the source code anywhere.  Makes it tough to find the 'true' error.  :(  Did I miss something somewhere?

**Comment by igitur** [comment] 2018-02-08 14:46
Can you paste a screenshot or something of where it's breaking?

**Comment by igitur** [comment] 2018-02-08 14:51
What is the exact exception and paste the full stack trace.

**Comment by valkyrienc** [comment] 2018-02-08 14:52
It's not giving me anything useful.  When it hits that line, I get a Browse dialog box:   

![image](https://user-images.githubusercontent.com/36073422/35979206-be33c8b2-0cb5-11e8-8b05-b60aba387e87.png)

And then this oh-so-useful page:

![image](https://user-images.githubusercontent.com/36073422/35979236-d11cb7e0-0cb5-11e8-86de-797545c61855.png)

**Comment by igitur** [comment] 2018-02-08 15:00
What is the exact exception and paste the full stack trace.

**Comment by valkyrienc** [comment] 2018-02-08 15:02
That IS the exact exception.  That's literally everything that shows up while stepping through the code.

**Comment by igitur** [comment] 2018-02-08 15:03
What's in the Locals window?

**Comment by valkyrienc** [comment] 2018-02-08 15:04
![image](https://user-images.githubusercontent.com/36073422/35979869-6b7fbdc2-0cb7-11e8-9e0e-f4af57229874.png)

**Comment by igitur** [comment] 2018-02-08 15:05
Any else besides the `this` entry in `Locals`?

**Comment by valkyrienc** [comment] 2018-02-08 15:06
Negative:

![image](https://user-images.githubusercontent.com/36073422/35980015-b07cf48a-0cb7-11e8-9249-f34195f2889b.png)

**Comment by valkyrienc** [comment] 2018-02-08 15:07
Call stack:

![image](https://user-images.githubusercontent.com/36073422/35980073-d2549e96-0cb7-11e8-91ae-b8a014a1f4e2.png)

**Comment by igitur** [comment] 2018-02-08 15:08
In https://github.com/ClosedXML/ClosedXML/issues/678#issuecomment-364135518, why does it look like you're referencing Microsoft's reference source? `ndp\fx\src`

**Comment by valkyrienc** [comment] 2018-02-08 15:09
I honestly have no idea.  I haven't made any changes to the code at all.  It's the latest download from GitHub.

**Comment by igitur** [comment] 2018-02-08 15:10
On what version of .NET is your SSIS thing running?

**Comment by valkyrienc** [comment] 2018-02-08 15:11
VS 2015

**Comment by igitur** [comment] 2018-02-08 15:12
What version of *.NET*, I'm not asking about your version of Visual Studio.

**Comment by valkyrienc** [comment] 2018-02-08 15:13
Oh. Sorry.  4.6.1

**Comment by igitur** [comment] 2018-02-08 15:30
Put a breakpoint on line 882 of  `XLWorkbook_Save.cs`. the line that says:
```c#
if (newRichStrings.ContainsKey(c.RichText))
```

Then give me the value of `c.Address` and `c.Worksheet.Name`

**Comment by valkyrienc** [comment] 2018-02-08 21:12
Dang.  It didn't make it there.  However, I slowed down the step-through and discovered some more details:

Break comes at ToHex in Extensions.cs.  Here's the stack frame (not that it's THAT much better):

![image](https://user-images.githubusercontent.com/36073422/35996730-46d0ba16-0ce5-11e8-956b-faf55b76f44a.png)

Additionally, I found the offending cell. It has a change midway through from standard text to a different font and color.  I've found these errors inside the Locals:

![image](https://user-images.githubusercontent.com/36073422/35998481-c4bd0cb8-0cea-11e8-9aa5-5fa4e6b51eee.png)
![image](https://user-images.githubusercontent.com/36073422/35998498-d0a50436-0cea-11e8-8a5d-6ab37173c692.png)

**Comment by igitur** [comment] 2018-02-12 09:37
This makes no sense. You say the breakpoint on line 882 of `XLWorkbook_Save.cs` isn't being hit. Yet you reached line 889. Also, according to your variables, `xlColor` is a theme colour, yet you're hitting line 3998, which is to get the hex code of an RGB color. That makes absolutely no sense.

Are you maybe running 2 processes in parallel? ClosedXML definitely isn't thread-safe and it's possible that overlapping threads are messing things up.

**Comment by igitur** [comment] 2018-03-14 20:46
Can't reproduce. Closing.

**Closed by igitur** 2018-03-14 20:46 UTC
