### ISSUE TITLE
Reading excel documents to datatable c# all space and special characters showing codes 

### ISSUE THREAD

**Issue by mclombaard** [ClosedXML/ClosedXML#2207] opened 2023-11-01 11:33 UTC
Reading excel documents to data table c# all space and special characters showing codes 

"/" showing as x002F etc.
"COMFRT_x0020_DIAPRS_x0020_VP_x0020_SZ2_x0020_44EA" 
Suppose to be "COMFRT DIAPRS VP   SZ2 44EA"

as seen on code below I have tried replacing where i can but there can be so many others

  public static DataTable ExtractSalesData(string salesDirectory)
        {
            DataTable salesDataTable = new DataTable();

            // Define the column names
            salesDataTable.Columns.Add("Month start");
            salesDataTable.Columns.Add("Barcode");
            salesDataTable.Columns.Add("PnPArticleNumber");
            salesDataTable.Columns.Add("Vendor Product Code");
            salesDataTable.Columns.Add("Product Description");
            salesDataTable.Columns.Add("Store Id");
            salesDataTable.Columns.Add("Store");
            salesDataTable.Columns.Add("Region");
            salesDataTable.Columns.Add("Major Region");
            salesDataTable.Columns.Add("Sales Units TY");
            salesDataTable.Columns.Add("Sales Units LY");
            salesDataTable.Columns.Add("Sales Units Growth %");
            salesDataTable.Columns.Add("Sales Value TY");
            salesDataTable.Columns.Add("Sales Value LY");
            salesDataTable.Columns.Add("Sales Value Growth %");
            salesDataTable.Columns.Add("Currency");
            salesDataTable.Columns.Add("Vendor Account");
            salesDataTable.Columns.Add("Brand");
            salesDataTable.Columns.Add("Category");

            try
            {
                string[] excelFiles = Directory.GetFiles(salesDirectory, "*.xlsx");

                foreach (string excelFile in excelFiles)
                {
                    using (var workbook = new XLWorkbook(excelFile))
                    {
                        var worksheet = workbook.Worksheet(1); // Assuming data is on the first worksheet

                        foreach (var row in worksheet.RowsUsed().Skip(1)) // Skip header row
                        {
                            DataRow dataRow = salesDataTable.NewRow();

                            for (int i = 0; i < salesDataTable.Columns.Count; i++)
                            {
                                string cellValue = row.Cell(i + 1).Value.ToString();
                                dataRow[salesDataTable.Columns[i].ColumnName] = CleanCellValue(cellValue);
                            }

                            salesDataTable.Rows.Add(dataRow);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                // Handle any exceptions that may occur during the extraction
                Log.Error($"Error occurred during data extraction: {ex.Message}");
            }

            return salesDataTable;
        }

      public static string CleanCellValue(string cellValue)
        {
            cellValue = Regex.Replace(cellValue, @"_x003", "");
            cellValue = Regex.Replace(cellValue, @"_x0020", " ");
            cellValue = Regex.Replace(cellValue, @" _", " ");
            cellValue = Regex.Replace(cellValue, @"_x0028_", "(");
            cellValue = Regex.Replace(cellValue, @"_x0029_", ")");
            cellValue = Regex.Replace(cellValue, @"0_", "");
            cellValue = Regex.Replace(cellValue, @"_", "");
            return cellValue;
        }

**Comment by jahav** [comment] 2023-11-01 20:52
Not using template. Closing.
Likely duplicate of #1820

**Closed as not planned by jahav** 2023-11-01 20:52 UTC
