### ISSUE TITLE
ClosedXML 0.104.2.0 - Not Signed - 

### ISSUE THREAD

**Issue by AndrewRDale** [ClosedXML/ClosedXML#2514] opened 2024-11-18 15:01 UTC
Hi, I'm trying to use your latest ClosedXML in my .NET project and Visual Studio keeps complaining.

A strongly-named assembly is required. 

Could you please sign the latest ClosedXML 0.104.2.0?

Cheers

**Comment by jahav** [comment] 2024-11-19 00:22
Duplicate of ##2423

**Closed as completed by jahav** 2024-11-19 00:22 UTC
