### ISSUE TITLE
Support for DocumentFormat.OpenXml 3.x

### ISSUE THREAD

**Issue by dluc** [ClosedXML/ClosedXML#2315] opened 2024-03-20 15:33 UTC
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

* 0.102.2
* 0.103.0-beta
* 0.104.0-preview2

**What is the current behavior?**

When using `ClosedXML` in combination with `DocumentFormat.OpenXml` version "3.0.2" the code fails to process Excel files, throwing an error:

```
Unhandled exception. System.MissingMethodException: Method not found: 'DocumentFormat.OpenXml.OpenXmlElementList DocumentFormat.OpenXml.OpenXmlElement.get_ChildElements()'.
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
   at ClosedXML.Excel.XLWorkbook.Load(Stream stream)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream, LoadOptions loadOptions)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream)
```

The same code works fine instead when using `DocumentFormat.OpenXml` version "2.20.0"

**What is the expected behavior or new feature?**

ClosedXML should work with newer versions of `DocumentFormat.OpenXml`. Version 2.20.0 is a year old, and the library has moved to version 3 since.

**Is this a regression from the previous version?**

No. ClosedXML is explicitly requiring DocumentFormat.OpenXml (>= 2.16.0 && < 3.0.0).

## Reproducibility

Project setup:
```xml
<PackageReference Include="ClosedXML" Version="0.102.2"/>
<PackageReference Include="DocumentFormat.OpenXml" Version="3.0.2"/>
```

```csharp
using XLWorkbook workbook = new XLWorkbook(GetXls());
```

full code: https://github.com/dluc/DocumentFormat.OpenXml-issue

**Comment by jahav** [comment] 2024-03-20 16:05
PR for that has been merged. https://github.com/ClosedXML/ClosedXML/pull/2248

**Comment by jahav** [comment] 2024-03-20 16:05
Duplicate of #2220

**Closed as completed by jahav** 2024-03-20 16:05 UTC

**Comment by dluc** [comment] 2024-03-20 16:08
@jahav I see the merge but we're still experiencing the problem with the latest version of ClosedXML. 
I tested versions 0.102.2, 0.103.0-beta and 0.104.0-preview2. Is there another version where that merge is included?

**Comment by jahav** [comment] 2024-03-20 16:10
There isn't, but issues are closed when they are resolved in dev branch, not when version is released.

**Comment by GusBeare** [comment] 2024-05-10 13:47
Has this version been released?

**Comment by barthamark** [comment] 2024-07-18 08:05
I'm still experiencing incompatibility issues with OpenXML 3.0.0+ with the latest 0.104.0-preview2. Can you confirm that it's already fixed but not yet released? If so, when is it expected to be released?
