### ISSUE TITLE
Spreadsheet copy throws exception with old metadata.

### ISSUE THREAD

**Issue by JaredKreft** [ClosedXML/ClosedXML#354] opened 2017-06-18 02:25 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

Copying a Spreadsheet from one workbook to another in Excel then causes an Exception if ClosedXML tries to copy that spreadsheet in code, due to inherited metadata.

STR:
Have a multi-sheet workbook with data on several sheets.
Create a new workbook.
Copy a sheet from the first workbook to the new one. Save the new one.

Create a C# program which loads the second workbook and tries to copy the sheets to a new workbook using ClosedXML.

Result: Because the metadata was inherited in Excel to the new workbook, including names of sheets that don't exist, when your copy code tries to copy the sheet from the second workbook in code, it tries to reference the sheets from the metadata (which don't exist in this workbook, existed in the original). So you get an exception about "Sheet_from_Original_Workbook" being an invalid sheet.

Now, I get that Excel shouldn't be dragging in the names from the original workbook's sheets into the new workbook. MS code is bad.

However, your code for copying a sheet should not be trying to reference sheets included in its metadata. I should be able to copy the sheet (which exists!) in code without throwing an exception about referencing a sheet that doesn't exist (because I don't reference it!).

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[break.xlsx](https://github.com/ClosedXML/ClosedXML/files/1082870/break.xlsx)

**Code to reproduce problem:**
```c#
public void Main()
{
    var fs = new FileStream("Break.xlsx", FileMode.Open, FileAccess.Read, FileShare.ReadWrite);

    {
        ClosedXML.Excel.XLWorkbook = new ClosedXML.Excel.XLWorkbook();

        ClosedXML.Excel.XLWorkbook xTemp = new ClosedXML.Excel.XLWorkbook(fs);
        for (int iLP = 1; iLP <= xTemp.Worksheets.Count; iLP++)
        {
            Settings.Workbook.AddWorksheet(xTemp.Worksheet(iLP));
        }
        xTemp.Dispose();
    }
}
```

**Comment by vbjay** [comment] 2017-06-18 15:05
Just a tip.

- [ ] unchecked
- [x] checked

NOT
- [x ]

**Comment by vbjay** [comment] 2017-06-18 15:11
When does it give you the error?  In the addworksheet call or when xTemp is disposed.

Also learn to use the using block
```
using (ClosedXML.Excel.XLWorkbook xTemp = new ClosedXML.Excel.XLWorkbook(fs))
{
//use xTemp here
}//xTemp disposed here

**Comment by JaredKreft** [comment] 2017-06-18 15:37
" when your copy code tries to copy "

**Comment by igitur** [comment] 2017-06-19 08:29
I don't think cross-workbook interaction has ever been tested. This might take a while to think through and fix.

**Comment by igitur** [comment] 2017-06-19 08:38
You have named ranges to external workbooks' contents. This is definitely not supported. You should remove them first before attempting to copy the worksheet. 

![image](https://user-images.githubusercontent.com/145854/27276331-3278ef9c-54db-11e7-92c0-0115168fd3c1.png)

**Comment by JaredKreft** [comment] 2017-06-19 15:58
Igitur: Those named ranges aren't referenced in the sheet, however. They were used in other sheets in the workbook that the sheet came from. The fact that they were copied over with the worksheet is Microsoft's failure.

The worksheet that won't copy is simple data, no external references. The fact that the worksheet copy code somehow tries to validate these unused external references is the failure in *this* code that needs to be looked at. Something in the copy method is trying to access the "monster lookup" worksheet which is mentioned in those above references, even though the sheet being copied *does not reference it*. That's the part that shouldn't be happening.

Copying "Locations" shouldn't need to open any of the named ranges above *or* open the "Monster Lookup" sheet.

(And yes, I know how to work around this, I'm going to copy and paste just the contents of the Locations sheet instead of copying the sheet. It doesn't change the fact that there's something buggy in the code if it is working the way described.)

**Comment by igitur** [comment] 2017-06-22 09:13
Duplicate of #355

**Comment by igitur** [comment] 2017-06-22 09:14
Also duplicate of #121

**Closed by igitur** 2017-06-22 09:13 UTC

**Comment by JaredKreft** [comment] 2017-06-22 15:46
Not a duplicate of either bug.

#121 is asking y'all to copy the external link instead of the worksheet ID in the formula.
#355 (which is after mine, by the way) is about how you copy ranges between worksheets.

I'm doing neither. My bug is that your code is chasing down a reference in metadata for a sheet that *does not have any references*. A sheet copy should not be trying to evaluate ANYTHING, especially not workbook metadata that isn't referenced by the sheet.

**Comment by igitur** [comment] 2017-06-22 16:29
No, #355 is about copying worksheets or ranges *across different workbooks*, not copying ranges across *worksheets*.
#121 is about references to external workbooks, which is clearly an issue here.

If I disable the exception which is bothering you, without fixing #121, you'll end up with a corrupt workbook, because the sheet will have half-baked external references. Once #121 is completed, with proper external reference support, then we can work on this.

If you still disagree, you're welcome to submit a PR to prove your point.

**Comment by JaredKreft** [comment] 2017-06-22 16:41
The sheet already has half-baked external references, thanks to MS. It's referring to sheets in its own workbook that don't exist. This doesn't cause a problem in excel because the references aren't being used. They were blindly copied from the old workbook's metadata without being checked by Excel. (That's an MS bug.)

When I'm copying the sheet using your code into memory, your code is trying to evaluate what are already dead references. Why? Why are they being evaluated on copy when nothing in the sheet references them? That's a bug in *this* code.

And no, it doesn't require external reference support to stop trying to evaluate workbook metadata which the sheet does not use in the *sheet* copying code.
