### ISSUE TITLE
Exception Thrown while evaluating "=Row()-2"

### ISSUE THREAD

**Issue by JaredKreft** [ClosedXML/ClosedXML#384] opened 2017-07-05 18:35 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**
Value.ToString() for a cell which has only a formula and an empty value throws a "syntax error" exception. Alternatively, evaluation of "Row()" bugged.

**If the current behavior is a bug, please provide the steps to reproduce and 
Create a spreadsheet which has a row of column headers and in its data rows has a formula cell of "=ROW()-2";
Try to get a String value out of that cell.

**What is the expected behavior or new feature?**
Cell evaluates and returns value.

**Did this work in previous versions of our tool?  Which versions?**
No idea.

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[BugReport.xlsx](https://github.com/ClosedXML/ClosedXML/files/1125651/BugReport.xlsx)

**Code to reproduce problem:**
```c#

     public static DataTable GetTableFromSpreadsheet(IXLWorksheet xInput)
     {
            DataTable tReturn = new DataTable();
            int iFirstColumn = xInput.FirstColumnUsed().ColumnNumber();
            int iNumColumns = xInput.LastColumnUsed().ColumnNumber()-iFirstColumn+1;
            for (int iLP =iFirstColumn ; iLP <= iFirstColumn+iNumColumns-1; iLP++)
            {
                tReturn.Columns.Add(new DataColumn(xInput.Cell(1, iLP).Value.ToString()));
            }
            int iRows = xInput.LastRowUsed().RowNumber();
            DataRow rowTemp;
            for (int iLQ = 2; iLQ <= iRows; iLQ++)
            {
                rowTemp = tReturn.NewRow();
                    for(int iLP=0;iLP<iNumColumns;iLP++)
                    {
                        string DEBUGSTRING;
                        IXLCell DEBUGCELL;
                        DEBUGCELL = xInput.Cell(iLQ, iLP + iFirstColumn);
                        DEBUGSTRING=DEBUGCELL.Value.ToString();//Exception Thrown Here "Syntax Error". Cell evaluates properly in Excel.
                        rowTemp[iLP] = DEBUGSTRING;
                    }
                    tReturn.Rows.Add(rowTemp);
            }
            return tReturn;
        }

public void Main()
{
sInputFile="BugReport.xlsx";
FileStream fs = new FileStream(sInputFile, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
ClosedXML.Excel.XLWorkbook xTemp = new ClosedXML.Excel.XLWorkbook(fs);
       GetTableFromSpreadsheet(xTemp.Worksheet(1));
}

**Comment by igitur** [comment] 2017-07-10 10:53
Duplicate of #187

**Closed by igitur** 2017-07-10 10:53 UTC
