### ISSUE TITLE
The type initializer for 'SixLabors.Fonts.Tables.TableLoader' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified

### ISSUE THREAD

**Issue by DaleMitchell** [ClosedXML/ClosedXML#2406] opened 2024-09-20 19:47 UTC
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**
0.102.3

**What is the current behavior?**

Crashes with this error:

The type initializer for 'SixLabors.Fonts.Tables.TableLoader' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified

**What is the expected behavior or new feature?**

Should copy from one column to the other and then delete the copied column when finished.

**Is this a regression from the previous version?**

Not sure.

## Reproducibility

**Code to reproduce problem:**
```c#
                                // Provide folder path from which you like to get latest file
                                string folderPath = Path.Combine(gPrjPath, "Project Outputs", "BOM");
                                var files = new DirectoryInfo(folderPath).GetFiles("*.xlsx");
                                string latestFile = "";
                                DateTime lastModified = DateTime.MinValue;

                                foreach (FileInfo file in files)
                                {
                                    if (file.LastWriteTime > lastModified)
                                    {
                                        lastModified = file.LastWriteTime;
                                        latestFile = file.Name;
                                    }
                                }

                                // Path to last modified xlsx file is the BOM file we need to edit
                                string fullPathForFileToEdit = Path.Combine(folderPath, latestFile);

                                // Load the Excel workbook
                                using (var workbook = new ClosedXML.Excel.XLWorkbook(fullPathForFileToEdit))
                                {
                                    // Get the specific worksheet by name
                                    var worksheet = workbook.Worksheet("899xxxxxx BOM");
                                    if (worksheet == null)
                                    {
                                        throw new Exception("Worksheet '899xxxxxx BOM' not found.");
                                    }

                                    // Determine the number of rows in the worksheet
                                    int rowCount = worksheet.LastRowUsed().RowNumber();

                                    // Loop through each row starting from the fourth row
                                    for (int row = 4; row <= rowCount; row++)
                                    {
                                        // Get the value from column AJ (36th column)
                                        var valueInAJ = worksheet.Cell(row, 36).GetString();

                                        // Get the current value in column H (8th column)
                                        var valueInH = worksheet.Cell(row, 8).GetString();

                                        // If column H is empty, move the value from column AJ to column H
                                        if (string.IsNullOrEmpty(valueInH) && !string.IsNullOrEmpty(valueInAJ))
                                        {
                                            worksheet.Cell(row, 8).Value = valueInAJ;
                                        }
                                    }

                                    // Delete column AJ (36th column)
                                    worksheet.Column(36).Delete();

                                    // Save the changes to the Excel file
                                    workbook.Save();
                                }
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by rominator1983** [comment] 2024-09-26 12:03
This is very likely to be an issue with your build environment @DaleMitchell 
I suppose you are using .net 4.8? If so, check the version of 'System.Numerics.Vectors' in your build output and add a binding redirect to your project, or (better yet) reference the latest version of the System.Numerics.Vectors package in your projects to resolve version conflicts.
A diagnostic build will very likely show some version conflicts in your build chain that lead to this exception.

**Comment by jahav** [comment] 2024-10-02 08:59
As written before me is highly unlikely to be closedxml bug. There are several possibilities (missing assemblyBinding, assembly unification), but the problem is in other dependencies of your project. Ms build generally writes a half-helpfully messages. 

Closing.

**Closed as not planned by jahav** 2024-10-02 08:59 UTC

**Comment by augusto-zefiro** [comment] 2025-09-10 17:07
On my computer in a development environment the application works perfectly but in a production environment this error occurs, could someone help ?

**Comment by umaryasin33** [comment] 2025-11-20 10:30
> On my computer in a development environment the application works perfectly but in a production environment this error occurs, could someone help ?

I had the same issue. I guess you recently updated this package and your server is still using the older dll files. Had to modify my web.config to avoid this issue.
