### ISSUE TITLE
IF formula calculates FALSE expression unnecessarily and causes 'Null object cannot be converted to a value type.'

### ISSUE THREAD

**Issue by georgheimltwat** [ClosedXML/ClosedXML#2175] opened 2023-09-28 12:50 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.102.1

**What is the current behavior?**

- The formula is '=IF(ISBLANK(A1),,YEAR(A1))'
- Although A1 is Blank the YEAR(A1) is evaluated and causes an exception

**What is the expected behavior or new feature?**

- FALSE-Expression must only be evaluated when the TEST-Expression is FALSE

**Is this a regression from the previous version?**

- No, 0.101.0 has same problem

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
        var wb = new XLWorkbook();
        var ws = wb.AddWorksheet();
        ws.Cell("A1").Value = Blank.Value;
        ws.Cell("A2").FormulaA1 = @"=IF(ISBLANK(A1),,YEAR(A1))";
        //Exception: 'Null object cannot be converted to a value type.'
        var valueA2 = ws.Cell("A2").Value;  
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by georgheimltwat** [comment] 2023-10-02 08:06
Probably solution https://github.com/ClosedXML/ClosedXML/issues/2179 is better

**Comment by jahav** [comment] 2023-10-20 22:08
Although Excel doesn't evaluate the non-used argument for `IF`, it would mean I have to wire it to the evaluation part of the engine which is not something I want to do at this time (especially because of two different functions legacy with adapters and typed functions). Having all functions evaluated same way is using same paradigm (evaluate arguments and pass them to function)  make everything simpler. 

Also, `_xlfn.IFS` does evaluate even arguments for non-used branches (test: make a VBA with `MsgBox` and check whether is is displayed)

The evaluation of non-used branch is only problem if it has side effects, which I Excel functions don't have (VBA do).

The problem in this case is that conversion of blank to datetime is buggy for legacy functions (#2179).

**Comment by jahav** [comment] 2023-10-20 22:08
Duplicate of #2179

**Closed as not planned by jahav** 2023-10-20 22:08 UTC
