### ISSUE TITLE
IsolatedStorageException {"Unable to determine the identity of domain."}

### ISSUE THREAD

**Issue by TreforE** [ClosedXML/ClosedXML#301] opened 2017-05-08 15:19 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**

I have an application which receives a spreadsheet as a stream [modifies it] and saves it as a stream. If the spreadsheet if less than 900KB then all is OK. But if the spreadsheet gets up to about 1000Kb, then the SaveAs generates an exception 

System.IO.IsolatedStorage.IsolatedStorageException {"Unable to determine the identity of domain."}

The code below (extracted from the application) also generates the exception.

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**
[The spreadsheet is very large and the problem appeatrs to be spreadsheet size related. Can't send you the spreadsheet as it is as it "confidential". I could try to make it sendable if you really need it.]

**What is the expected behavior or new feature?**

**Did this work in previous versions of our tool?  Which versions?** 
Only using one version.

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
public void Main()
{
                     using (var fileStream = new FileStream(@"C:\FRED.xlsx", FileMode.Open))
                    {
                        VirtualStream memStrm1 = new VirtualStream();
                        ClosedXML.Excel.XLWorkbook workbook1 = new ClosedXML.Excel.XLWorkbook(fileStream);
                        workbook1.SaveAs(memStrm1);
                    }
}
```

**Comment by igitur** [comment] 2017-05-09 08:27
Without the spreadsheet causing the problem I can't diagnose. But this is probably a duplicate of #264 .

**Comment by vbjay** [comment] 2017-05-09 11:53
Start here. https://msdn.microsoft.com/en-us/library/3ak841sy(v=vs.110).aspx

**Closed** 2017-07-18 10:00 UTC
Labels: duplicate, Sample file required
