### ISSUE TITLE
Empty rows and cells causes file bloat

### ISSUE THREAD

**Issue by Exergist** [ClosedXML/ClosedXML#457] opened 2017-08-25 22:00 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.88.0

**What is the current behavior?**

Whenever I use ClosedXML to grab the value from a cell that contains an Excel formula the Excel file size significantly grows after saving depending on the size of the range used in the Excel formula. Let me explain further. 

```c#
public void Main()
{
    XLWorkbook wb = new XLWorkbook(MyWorkbookFileName);
    IXLWorksheet Data = wb.Worksheet("myData");
    var myCell = Data.Cell("C1");
    int myValue = Convert.ToInt32(myCell.Value);
    wb.Save();
    wb.Dispose();
}
```

Only cells in Excel file with data, text, formulas, etc are those mentioned below. 
Case 1:
Cell C1 contains the formula: =MAX(C3:C70)
Result ==> file size is 9 kB

Case 2:
Cell C1 contains the formula: =Max(C3:C100000)
Result ==> file size is 266 kB

Case 3:
Cell C1 contains the formula: =Max(C3:C1000000)
Result ==> file size is 2597 kB

Case 4:
Cell C1 contains the formula: =MAX(C3:C70)
Cell D1 contains the formula: =MAX(C3:C1000000)
Result ==> file size is 10 kB

As you can see the Excel file's size increases as the range of the _read_ cell's formula increases. After running the code for all 4 cases I can then open the Excel file manually, make no changes, save it, and the file will be back to 9 kB. The big issue I have here is that I'm trying to perform multiple file saves as my code runs and the larger the file becomes the longer it takes ClosedXML to load and save the file. 

I'm going to make a wild guess here and hypothesize that by reading the value from a cell that has a formula that uses a large number of cells ClosedXML somehow saves the file as if there are actually values contained within those referenced cells. 

Am I doing something wrong? Am I missing some code to properly "clean up" so that the Excel file saves correctly?

**What is the expected behavior or new feature?**

Expected behavior is for ClosedXML to not cause file save bloat for the above-mentioned Cases.

**Comment by igitur** [comment] 2017-08-26 16:36
I recently did some work on the calculation chain. The improvements are included in 0.89.0-beta1. It's available on Nuget. Try using that and let me know.

**Comment by igitur** [comment] 2017-08-27 17:58
Also, after switching to 0.89.0-beta1, try disable the calculation chain generation, e.g. 
```c#
workbook.SaveAs(file, new SaveOptions { GenerateCalculationChain = false });
```

**Comment by Exergist** [comment] 2017-08-28 15:11
Thanks for the suggestions @igitur. I tried version 0.89.0-beta1 (the "version" info within the "properties" window in VS2017 for the ClosedXML library shows "0.89.0.0") and the issue still remained. I also tried the following (separate attempts for each save method of course) and the issue still remained:

```c# 
wb.SaveAs("filename", new SaveOptions { GenerateCalculationChain = false });

wb.Save(new SaveOptions { GenerateCalculationChain = false }); 
```
Any other suggestions? Do I need to do something different with disposing or could this be related to the [memory issue](https://github.com/ClosedXML/ClosedXML/issues/86)? I appreciate your (and the community's) help since I'm a novice when it comes to this kind of programming.

**Comment by igitur** [comment] 2017-08-28 15:15
Please attach your unmodified (by ClosedXML) input file.

**Comment by Exergist** [comment] 2017-08-28 15:41
Ok here's all the info:


```c#
// ClosedXML v0.89.0-beta1 from NuGet
// Project = Framework 4.5.2
// Output = Debug for Any CPU

using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ClosedXML.Excel;

namespace ClosedXML_Formula_Test
{
    class Program
    {
        static void Main(string[] args)
        {
            // Get path of Excel file
            string directoryPath = Directory.GetParent(Path.GetDirectoryName(Path.GetDirectoryName(System.IO.Directory.GetCurrentDirectory()))).ToString();
            string fileName = "Unmodified.xlsx";
            string filePath = Path.Combine(directoryPath, fileName);

            // Initialize workbook and sheet variables
            XLWorkbook wb = new XLWorkbook(filePath);
            IXLWorksheet sheet = wb.Worksheet("mySheet");

            // Initialize variable pointing to cell of interest
            var FormulaCell = sheet.Cell("C1");

            // Get and store information from cell of interest
            double myFormula = FormulaCell.GetDouble();

            // Create and save new Excel file
            // wb.Save(new SaveOptions { GenerateCalculationChain = false });
            wb.SaveAs("Modified.xlsx", new SaveOptions { GenerateCalculationChain = false });

            // Dispose workbook
            wb.Dispose();
        }
    }
}
```
[Unmodified.xlsx](https://github.com/ClosedXML/ClosedXML/files/1257329/Unmodified.xlsx)
[Unmodified - After Running Code.xlsx](https://github.com/ClosedXML/ClosedXML/files/1257332/Unmodified.-.After.Running.Code.xlsx)
[Modified.xlsx](https://github.com/ClosedXML/ClosedXML/files/1257333/Modified.xlsx)

**Comment by igitur** [comment] 2017-08-28 16:47
Please try the build artifacts at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.510/artifacts

Ensure you have the necessary dependencies (same as v0.89.0-beta1).

**Comment by Exergist** [comment] 2017-08-28 17:26
Success! I took those artifact files and overwrote the existing ClosedXML.dll and ClosedXML.xml in my solution's "packages" folder, and running the code now creates a "Modified.xlsx" file that is at 9 kB. 

Is this change something that can be added to the 0.89.0-beta1 version?

**Comment by igitur** [comment] 2017-08-28 17:42
No, sorry, it's too late for 89. This type of change needs extensive testing, so will be included in 90 at the soonest, provided that I get enough feedback.

**Comment by Exergist** [comment] 2017-08-28 20:02
That's cool I figured I'd ask. I'll leave it to you to decide if/when to close this issue. 

Thank you very much for your help :)

**Comment by Exergist** [comment] 2017-08-28 21:17
Sadly I spoke before testing further. It appears the bloat issue is also present for Excel conditional formatting. So if Excel conditional formatting uses a formula that has large cell ranges the save file bloats. I've done limited testing, but on the worksheet that my code references I can turn on/off the bloat by adding/removing conditional formatting that uses large cell ranges.

**Comment by igitur** [comment] 2017-08-28 21:33
Sample files...

**Comment by Exergist** [comment] 2017-08-29 15:57
Okay so using the same c# code I provided earlier and the artifacts previously shared by @igitur  here are the results of my testing:

_Case 1a:_
Cell C1 contains the formula: =MAX(C3:C70)
No conditional formatting in any cells
Result ==> File size is 9 kB

_Case 1b:_
Cell C1 contains the formula: =MAX(C3:C70000)
No conditional formatting in any cells
Result ==> File size is 9 kB (proving again that the previous changes appear to fix the issue with large formula ranges in cells)

For all "conditional formatting" cases the following formula will be used:
![image](https://user-images.githubusercontent.com/31357974/29829028-f9f7b3a0-8ca3-11e7-8e79-aad5019776e1.png)

_Case 2:_
Cell C1 contains the formula: =MAX(C3:C70000)
Conditional formatting applied to only cell C1
![image](https://user-images.githubusercontent.com/31357974/29829169-51989b74-8ca4-11e7-8804-63d773e16256.png)
Result ==> File size is 9 kB

_Case 3:_
Cell C1 contains the formula: =MAX(C3:C70000)
Conditional formatting applied to only cell C3
Result ==> File size is 9 kB

_Case 4:_
Cell C1 contains the formula: =MAX(C3:C70000)
Conditional formatting applied to only cell C70000
Result ==> File size is 9 kB

_Case 5:_
Cell C1 contains the formula: =MAX(C3:C70)
Conditional formatting applied to the range C3:C70000
![image](https://user-images.githubusercontent.com/31357974/29829413-fbc1d7b4-8ca4-11e7-840b-97117dac2cab.png)
**Result ==> File size is 10 kB (essentially negligible file size increase)**

_Case 6:_
Cell C1 contains the formula: =MAX(C3:C700)
Conditional formatting applied to the range C3:C70000
**Result ==> File size is 13 kB (a small file size increase)**

_Case 7:_
Cell C1 contains the formula: =MAX(C3:C7000)
Conditional formatting applied to the range C3:C70000
**Result ==> File size is 46 kB (file size increase by factor of 5)**

_Case 8:_
Cell C1 contains the formula: =MAX(C3:C70000)
Conditional formatting applied to the range C3:C70000
**Result ==> File size is 370 kB (file size increase by factor of ~40)**

Please see the attached Unmodified and Modified files corresponding to _Case 8_. 
[Unmodified.xlsx](https://github.com/ClosedXML/ClosedXML/files/1260873/Unmodified.xlsx)
[Unmodified - After Running Code.xlsx](https://github.com/ClosedXML/ClosedXML/files/1260877/Unmodified.-.After.Running.Code.xlsx)
[Modified.xlsx](https://github.com/ClosedXML/ClosedXML/files/1260878/Modified.xlsx)

**Comment by igitur** [comment] 2017-08-29 18:58
I can't reproduce this. Give me only the unmodified and the code to run on it that will result in the 370 kB file.

**Comment by igitur** [comment] 2017-08-29 19:03
Ok, I can reproduce it.

**Comment by Exergist** [comment] 2017-08-29 19:49
Good deal, step 1 done. Sorry to inundate you with test case info, but I figured I'd try to be thorough.

**Comment by igitur** [comment] 2017-08-30 09:15
PS: `=IF(ISBLANK(C3)=FALSE, TRUE, FALSE)` can be rewritten as `=NOT(ISBLANK(C3))`

**Comment by igitur** [comment] 2017-08-30 12:12
Try the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.514/artifacts

**Comment by Exergist** [comment] 2017-08-30 14:32
Looks like it resolves the issue shown in Cases 5-8! Well done :+1: 

It would be great if in the future the extra code `new SaveOptions { GenerateCalculationChain = false }` wasn't needed, but I'll let smarter people than me make those judgments.

Also thanks for the formula tip. In the past I tended to overlook NOT, so I should try to use it more. An even more efficient formula would be `=COUNTA(C3)<>0`

Thanks again :)

**Comment by igitur** [comment] 2017-08-30 14:33
The `GenerateCalculationChain = false` turns out to be irrelevant in these cases. You can leave it out if you want.

**Closed** 2017-09-12 10:29 UTC

**Comment by igitur** [comment] 2017-10-06 12:35
https://www.nuget.org/packages/ClosedXML/0.90.0-beta2 is released and should include the fix for this issue.
