### ISSUE TITLE
ClosedXML.Excel.CalcEngine.ExpressionParseException: "Syntax error: expected ')'"

### ISSUE THREAD

**Issue by rvkstudent** [ClosedXML/ClosedXML#492] opened 2017-09-19 12:57 UTC
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
Dont know
**Version of ClosedXML**

e.g. 0.89.00-beta1

**What is the current behavior?**
Throw exeption
**What is the expected behavior or new feature?**
Throw exeption

**Did this work in previous versions of our tool?  Which versions?**

No v0.89
## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Cant get result of evaluation VLOOKUP formula.

**Code to reproduce problem:**
```c#
  int row_num = 1;
                        
            var wb1 = new XLWorkbook("c:\\XLTest\\Test.xlsx");

            IXLWorksheet ws = wb1.Worksheet(1);
            
                    row_num = 6;
               
          
           
                for (int i = 2; i <= 10; i++)
                {
                    var cellWithFormulaA1 = ws.Cell(i, 2);

                cellWithFormulaA1.FormulaA1 = "=VLOOKUP(" + ws.Cell(i, 1).Address.ToString() + "," + "'c:\\XLTest\\[test2.xlsx]Лист1'!$A:$B, 2,0)";
                ws.Cell(i, 3).Value = wb1.Evaluate(cellWithFormulaA1.FormulaA1); //here got exeption: ClosedXML.Excel.CalcEngine.ExpressionParseException: "Syntax error: expected ')'"

            }
            wb1.Save();

            wb1.Dispose();
```
[Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1314292/Test.xlsx)
[Test2.xlsx](https://github.com/ClosedXML/ClosedXML/files/1314293/Test2.xlsx)

**Comment by igitur** [comment] 2017-09-19 16:00
Cross workbook evaluation is not supported yet.

**Comment by igitur** [comment] 2017-09-19 16:01
Duplicate of #121

**Closed by igitur** 2017-09-19 16:01 UTC
