### ISSUE TITLE
System.Drawing.Common is deprecated on non-Windows platforms

### ISSUE THREAD

**Issue by leotsarev** [ClosedXML/ClosedXML#1694] opened 2021-07-16 15:27 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [ ] No
- [x] n/a
If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.95.1

**What is the current behavior?**
https://github.com/dotnet/designs/blob/a15a8c7a324c482c5e38b73e46c2afe56f6bd504/accepted/2021/system-drawing-win-only/system-drawing-win-only.md
System.Drawing is officially deprecated everywhere but Windows.

**What is the expected behavior or new feature?**
Either:
Port to another crossplatform drawing library
Or:
Mark corresponding methods (like AdjustContents) with SupportedOSPlatformAttribute(Windows)  which requires adding net5+ TFM

**Is this a regression from the previous version?**
no

## Reproducibility
n/a

**Comment by igitur** [comment] 2021-07-16 16:35
Thanks. Good suggestions. Would you mind contributing to the project by logging a PR for this?

**Comment by igitur** [comment] 2021-07-16 16:40
Oh, sorry, does #1696 address this?

**Comment by leotsarev** [comment] 2021-07-16 17:42
@igitur  — not yet. If it's ok, I'll contribute PR on top of #1696 
Meanwhile, could you please review and push #1695  & #1696 ?

**Comment by steffi3011** [comment] 2021-09-01 11:54
Hello, has anything been done here yet? And if not, can you tell when adjustments are planned?

**Comment by leotsarev** [comment] 2021-09-15 13:39
@igitur what's the plan going forward for #1695 & #1696 ?

**Comment by fjmorel** [comment] 2021-12-09 16:12
In the meantime, at least users of this library would get warnings when using methods which depend on it.

**Comment by lazaromenezes** [comment] 2022-01-18 19:28
FYI: .Net 6 removed the System.Drawing.Common support for non-Windows systems: https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

Trying the runtime config flag hasn't been working for us so far. 

The suggested solution of installing **libgdlplus** works fine for our 3.1 environment tho.

**Comment by dgmoex** [comment] 2022-02-03 05:20
@igitur Hello! We migrated from epplus to closedxml by attempt to break free of System.Drawing.Common. It was random recomendation on SO) You can't trust everything on the Internet, ofcourse) So, is it realistic perspective that closedxml team would switch from System.Drawing.Common to another lib?
With great respect and thanks to you.

**Comment by 0xced** [comment] 2022-02-04 19:14
I could try to migrate from System.Drawing.Common to [SixLabors.ImageSharp](https://github.com/SixLabors/ImageSharp) but this project seems a bit stalled. I have opened an _easy_ pull request (#1761) to see if this project still has some momentum or not.

**Comment by 0xced** [comment] 2022-02-07 15:25
So I started to port ClosedXML to ImageSharp anyway because it was an interesting challenge. So far it's going great, only 7 tests do not pass (on macOS). You can have a look at my [ImageSharp](https://github.com/0xced/ClosedXML/tree/ImageSharp) branch if you are interested. I'm currently force-pushing a lot. I'll open a pull request soon when I feel it's more stable and I'll stop force-pushing too much.

**Comment by rominator1983** [comment] 2022-02-18 21:54
You could check out https://github.com/stesee/ClosedXML where SkiaSharp is used and things are already running with linux

**Comment by jasonlaw** [comment] 2022-03-24 11:03
> You could check out https://github.com/stesee/ClosedXML where SkiaSharp is used and things are already running with linux

Any idea why the changes is not pushed here?

**Comment by rominator1983** [comment] 2022-03-25 19:57
> Any idea why the changes is not pushed here?

No.
We tried to get a few things pulled to this repository that we needed for our product [Document Partner](https://www.rubicon.eu/en/products/document-partner/)
Since none of those were accepted/merged we had no choice but to build the thing for ourselves including the changes we needed.
So we won't do any more PRs to the original repository.
I did integrate the upstream develop and dragged some PRs of the original over too in order to have a reasonable state.
Last thing we did was .NET 6 and Linux compatibility.
If you think something is missing you can make a PR at https://github.com/stesee/ClosedXML
We will definitively look into them.

**Comment by rominator1983** [comment] 2022-03-26 20:41
Take a look at the authors comment here https://github.com/ClosedXML/ClosedXML/issues/1750

**Comment by ajkonkol** [comment] 2022-05-23 19:06
> So I started to port ClosedXML to ImageSharp anyway because it was an interesting challenge. So far it's going great, only 7 tests do not pass (on macOS). You can have a look at my [ImageSharp](https://github.com/0xced/ClosedXML/tree/ImageSharp) branch if you are interested. I'm currently force-pushing a lot. I'll open a pull request soon when I feel it's more stable and I'll stop force-pushing too much.

Hi @0xced .  We are very interested in ClosedXML supporting Linux, and your work to port it to ImageSharp seems to be the way forward.  Are you still thinking of opening a pull request with this, now that @AmirBosch is (at least temporarily) taking over as maintainer?

**Comment by 2mik** [comment] 2022-07-25 13:02
Related issue is #1805

**Comment by jahav** [comment] 2022-10-27 16:50
Dependency System.Drawing.Common has been removed (replaced mostly by SixLabors.Fonts + custom image reading) in 0.97.  Duplicate of #1805.

**Closed by jahav** 2022-10-27 16:50 UTC
