### ISSUE TITLE
0.86 Sequence contains more than one matching element

### ISSUE THREAD

**Issue by BenKmann** [ClosedXML/ClosedXML#230] opened 2017-03-06 13:53 UTC
After i upgrade ClosedXML from 0.85 to 0.86 i can't save my Workbooks anymore.
When i downgrade to 0.85 everything works again. 

Stacktrace:
```
System.InvalidOperationException
Sequence contains more than one matching element.
StackTrace:
   bei System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   bei ClosedXML.Excel.XLWorkbook.GenerateWorkbookStylesPartContent(WorkbookStylesPart workbookStylesPart, SaveContext context) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:Zeile 2610.
   bei ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:Zeile 252.
   bei ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, Boolean validate) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:Zeile 104.
   bei ClosedXML.Excel.XLWorkbook.Save(Boolean validate) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:Zeile 452.
   bei ClosedXML.Excel.XLWorkbook.Save() in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:Zeile 432.
```

And my Code
```c#
var wb = new XLWorkbook(FILEPATH);
wb.Save();   // Just Opening und Saving is Enough.
```
I hope the Stacktrace is enough. Happens with different Excel Files on my side. 
If you need more Information, just ask.

**Comment by igitur** [comment] 2017-03-06 13:56
Please attach a workbook that produces the problem.

**Comment by BenKmann** [comment] 2017-03-06 14:04
[Blanko_clean.xlsx](https://github.com/ClosedXML/ClosedXML/files/821345/Blanko_clean.xlsx)

**Comment by igitur** [comment] 2017-03-06 14:25
I can't reproduce the problem with the latest source code from the `develop` branch and with the file that you supplied.

**Comment by BenKmann** [comment] 2017-03-06 14:38
Can you reproduce it with the 0.86 Nuget Package? 
Maybe with this Document? 
[FehlendeSpalte.xlsx](https://github.com/ClosedXML/ClosedXML/files/821431/FehlendeSpalte.xlsx)
There i get a different Exception (that i sometimes also got with the first File and i only get in 0.86) so maybe they are connected?:
```
System.ApplicationException
The attribute 'left' has invalid value '0.787401575'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'right' has invalid value '0.787401575'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'top' has invalid value '0.984251969'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'bottom' has invalid value '0.984251969'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'header' has invalid value '0.4921259845'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'footer' has invalid value '0.4921259845'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'left' has invalid value '0.787401575'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'right' has invalid value '0.787401575'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'top' has invalid value '0.984251969'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'bottom' has invalid value '0.984251969'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'header' has invalid value '0.4921259845'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'footer' has invalid value '0.4921259845'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'defaultColWidth' has invalid value '11.425781'. The MaxInclusive constraint failed. The value must be less than or equal to 65535. in /x:worksheet[1]/x:sheetFormatPr[1]
The attribute 'width' has invalid value '18.425781'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[1]
The attribute 'width' has invalid value '10.285156'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[2]
The attribute 'width' has invalid value '10.855469'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[3]
The attribute 'width' has invalid value '29.140625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[4]
The attribute 'width' has invalid value '6.425781'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[5]
The attribute 'width' has invalid value '85.855469'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[6]
The attribute 'width' has invalid value '11.425781'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[8]
The attribute 'left' has invalid value '0.787401575'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'right' has invalid value '0.787401575'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'top' has invalid value '0.984251969'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'bottom' has invalid value '0.984251969'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'header' has invalid value '0.4921259845'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'footer' has invalid value '0.4921259845'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
StackTrace:
   bei ClosedXML.Excel.XLWorkbook.Validate(SpreadsheetDocument package) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:Zeile 90.
   bei ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, Boolean validate) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:Zeile 105.
   bei ClosedXML.Excel.XLWorkbook.Save(Boolean validate) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:Zeile 452.
   bei ClosedXML.Excel.XLWorkbook.Save() in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:Zeile 432.
```

**Comment by igitur** [comment] 2017-03-06 14:51
That error refers to #152 . Please see the workarounds described in there.

I still can't reproduce the other error. Try the latest code from the `develop` branch. Apply the fix for #152  if you wish.

**Comment by BenKmann** [comment] 2017-03-06 15:26
Thanks igitur, 

i have a German System, so that's why 
Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-US");
helped me with the Parsing Errors.

But even with the en-US Culture i get the original Exception from the Start.

I also tried disabling Validation, but still got the Exception.
```
var wb = new XLWorkbook(currentAddress.Clipping);
wb.SaveAs(@"C:\Temp\test.xlsx", false);
```

Here a little modified xlsx. I didn't got the Exception with a completely empty Template.
Please try again with this File. If it still doesn't crash, then i would wait for 0.87 and see if it persists there.
[Blanko.xlsx](https://github.com/ClosedXML/ClosedXML/files/821577/Blanko.xlsx)

**Comment by igitur** [comment] 2017-03-06 15:40
Thanks I can reproduce the issue with `Blanko.xlsx`. What is your default culture? `de-DE`?  And what is the usual name of the `Normal` cell style in that culture?

**Comment by BenKmann** [comment] 2017-03-06 16:53
Sorry for the long wait.
My Culture is "de-DE" and our Normal Cell Style is Named "Standard". 
At least that is what Excel is saying.

**Comment by igitur** [comment] 2017-03-06 20:04
Please attach a new, blank spreadsheet created in your culture. I want to check something in that.

**Comment by BenKmann** [comment] 2017-03-07 10:57
[Mappe1.xlsx](https://github.com/ClosedXML/ClosedXML/files/824145/Mappe1.xlsx)
Here it is :)

**Comment by igitur** [comment] 2017-03-07 11:22
So I don't know how you ended up with a file that contains multiple default IDs. I wasn't able to generate such a file, even starting off with `Mappe1.xlsx`. But anyway, PR233 should fix your issue.

**Comment by BenKmann** [comment] 2017-03-07 11:29
Thanks! Yes i know the template is strange. But Thank you anyway for the fix.

**Comment by igitur** [comment] 2017-03-20 10:37
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.

**Comment by BenKmann** [comment] 2017-03-20 10:46
Cloned it and yep, it works with the develop Branch 👍

**Closed** 2017-03-20 10:47 UTC
Labels: enhancement
