### ISSUE TITLE
Access to used range of a PivotTable

### ISSUE THREAD

**Issue by nefcanto** [ClosedXML/ClosedXML#432] opened 2017-08-09 06:11 UTC
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

**ClosedXML version 0.87.0.0**

**What is the current behavior?**
I can't access the used range of a PivotTable. I have data in sheet 1, a PivotTable that is created based on that data is in sheet2, now I want to copy the values of that pivot table from sheet 2, to sheet 3. To copy values, I need to use this technique as explained in #377 :

`targetsheet.Cell(1, 3).Value = sourceSheet.Cell(1, 3).Value;`

This means that I need to loop over rows and columns of a given PivotTable, and copy each cell's value from sheet 2 to sheet 3. But I fail to find a way to loop over PivotTable's rows and column, that is, the used range.

**What is the expected behavior or new feature?**
After getting a PivotTable reference, there should be a method or a property to give us UsedRange of the PivotTable, or Rows property that can be looped over, and for each Row, a collection of Columns property that can be looped over too.

- [x ] I attached a sample spreadsheet. 
[7ac86a6f-4407-43be-b4f2-ad29f45ed2ff.xlsx](https://github.com/ClosedXML/ClosedXML/files/1210478/7ac86a6f-4407-43be-b4f2-ad29f45ed2ff.xlsx)

I want to copy only values from PivotTable in the second sheet, to a new sheet.

**Comment by igitur** [comment] 2017-08-09 14:32
Duplicate of #391

**Closed by igitur** 2017-08-09 14:32 UTC
