### ISSUE TITLE
Bug with Column Location of Fields in a XLTable

### ISSUE THREAD

**Issue by gleesonger** [ClosedXML/ClosedXML#472] opened 2017-09-07 21:38 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.87.1

**What is the current behavior?**

Column location of Fields in a table are offset by -1.

**Correction**

XLTable.cs > FieldNames

Original:
_fieldNames.Add(name, new XLTableField(this, name) { Index = cellPos++ });

Corrected:
_fieldNames.Add(name, new XLTableField(this, name) { Index = ++cellPos });

**Comment by igitur** [comment] 2017-09-08 03:29
Field indices are 0 based by design and columns start at 1. This is by design. Or do you mean that there is some other bug?

**Comment by gleesonger** [comment] 2017-09-08 07:48
When accessing the Column of a Field the location of the column is one to the left, eg If a table spans B1:D3 and we try to get the first Field the associated column is A1:A3

Example code blow;
            var tbl_to_check = wrkbk.Worksheets.SelectMany(a => a.Tables.Where(t => String.Equals("Table1", t.Name))).FirstOrDefault();

            var field = tbl_to_check.Field("SecondColumnHeader");  
            var col = field.Column;  <-- This returns the column of the FirstColumnHeader

            var field = tbl_to_check.Field("FirstColumnHeader");
            var col = field.Column;  <-- This throws an IndexOutOfBounds Exception

Prehaps the correction is by increasing the Index in XLTableField.Column 

        public IXLRangeColumn Column
        {
             //get { return table.Column(this.Index); }     // throws an IndexOutOfBounds exception
            get { return table.Column(this.Index+1); }
        }

**Comment by igitur** [comment] 2017-09-08 09:51
Fixed in #463

**Closed by igitur** 2017-09-08 09:51 UTC
