### ISSUE TITLE
Cell formatting has stopped working in v 0.100.3

### ISSUE THREAD

**Issue by simonziegler** [ClosedXML/ClosedXML#1979] opened 2023-01-18 14:35 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.100.3

**What is the current behavior?**

Setting number formats with `[cell].Style.NumberFormat.Format` has stopped working.

**What is the expected behavior or new feature?**

Cells should format accordingly. This has been working well for the year or so that I have been using ClosedXML (a great package - thank you!). Everything was fine in 0.97.0. As of 0.100.3 (I skipped the previous 2 releases) cell formatting for numeric cells is not working.

**Is this a regression from the previous version?**

Yes.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

`worksheet.Cell(row, col).Style.NumberFormat.Format = numberFormat;`

`numberFormat` is a value such as "#,##0.00;[Red]-#,##0.00;-".

**Code to reproduce problem:**
I WILL ADD THIS IN THE COMING DAY OR SO.
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
WILL ATTACH A SPREADSHEET IN A DAY OR SO.

**Comment by jahav** [comment] 2023-01-19 09:52
I don't think I have changes something for numformat, so please post repro for regression.

But it is likely due to escaping. Please read https://closedxml.readthedocs.io/en/latest/features/cell-format.html#custom-number-format

EDIT: Deleted section, it was incorrect due to my culture setting

**Comment by igitur** [comment] 2023-01-19 10:04
It's possible that the data type guessing that was removed changed behaviour now. Are you sure the cell data type is still numeric?

**Comment by jahav** [comment] 2023-01-26 20:27
Closing due to lack of reproduction test code.

**Closed as not planned by jahav** 2023-01-26 20:27 UTC
