### ISSUE TITLE
Closed XML Export excel System out of memory

### ISSUE THREAD

**Issue by swloo618** [ClosedXML/ClosedXML#1873] opened 2022-10-13 02:19 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.96

**What is the current behavior?**

I try to export my datatable with 490k rows of records and 10 columns but it give me System out of memory or sometime it's success generate the excel but can't open the file because file format or file extension not valid.

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

In version 0.69, it show the system out of memory.  It can't generate the excel file

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```vb.net
public void Main()
{
    Using wb As New XLWorkbook()

                Dim ws = wb.Worksheets.Add(dataTable, "Transactions")
                wb.Worksheets.Worksheet("Transactions").Row(1).Style.Fill.SetBackgroundColor(XLColor.FromArgb(1, 145, 109))
                wb.Worksheets.Worksheet("Transactions").Row(1).Style.Font.SetFontColor(XLColor.White)


                Response.Clear()
                Response.Buffer = True
                Response.Charset = ""
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                Response.AddHeader("content-disposition", "attachment;filename=Transactions.xlsx")

                Using MyMemoryStream As MemoryStream = New MemoryStream()
                    wb.SaveAs(MyMemoryStream)
                    MyMemoryStream.WriteTo(Response.OutputStream)
                    Response.Flush()
                    Response.End()
                End Using
            End Using
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by swloo618** [comment] 2022-10-13 03:39
public void Main()
{
Dim dataTable as DataTable = new DataTable();
Dim dc1 As DataColumn = New DataColumn("A", GetType(String))
Dim dc2 As DataColumn = New DataColumn("B", GetType(String))
Dim dc3 As DataColumn = New DataColumn("C", GetType(String))
Dim dc4 As DataColumn = New DataColumn("D", GetType(String))
Dim dc5 As DataColumn = New DataColumn("E", GetType(String))
Dim dc6 As DataColumn = New DataColumn("F", GetType(String))
Dim dc7 As DataColumn = New DataColumn("G", GetType(String))
Dim dc8 As DataColumn = New DataColumn("H", GetType(String))
Dim dc9 As DataColumn = New DataColumn("I", GetType(String))
Dim dc10 As DataColumn = New DataColumn("J", GetType(String))

dataTable .Columns.Add(dc1)
dataTable .Columns.Add(dc2)
dataTable .Columns.Add(dc3)
dataTable .Columns.Add(dc4)
dataTable .Columns.Add(dc5)
dataTable .Columns.Add(dc6)
dataTable .Columns.Add(dc7)
dataTable .Columns.Add(dc8)
dataTable .Columns.Add(dc9)
dataTable .Columns.Add(dc10)

for i as integer = 0 To 500000
    Dim dataRow As DataRow = dataTable.NewRow
    dataRow(0) = "Sample data"
    dataRow(1) = "Sample data"
    dataRow(2)= "Sample data"
    dataRow(3) = "Sample data"
   dataRow(4) = "Sample data"
    dataRow(5)= "Sample data"
    dataRow(6) = "Sample data"
    dataRow(7) = "Sample data"
   dataRow(8) = "Sample data"
   dataRow(9) = "Sample data"
   dataRow(10)= "Sample data"
   dataTable.Rows.Add(dr)
Next

    Using wb As New XLWorkbook()

                Dim ws = wb.Worksheets.Add(dataTable, "Transactions")
                wb.Worksheets.Worksheet("Transactions").Row(1).Style.Fill.SetBackgroundColor(XLColor.FromArgb(1, 145, 109))
                wb.Worksheets.Worksheet("Transactions").Row(1).Style.Font.SetFontColor(XLColor.White)


                Response.Clear()
                Response.Buffer = True
                Response.Charset = ""
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                Response.AddHeader("content-disposition", "attachment;filename=Transactions.xlsx")

                Using MyMemoryStream As MemoryStream = New MemoryStream()
                    wb.SaveAs(MyMemoryStream)
                    MyMemoryStream.WriteTo(Response.OutputStream)
                    Response.Flush()
                    Response.End()
                End Using
            End Using
}

**Comment by jahav** [comment] 2022-10-13 08:19
Duplicate of #1753

**Closed as not planned by jahav** 2022-10-13 08:19 UTC
