### ISSUE TITLE
Duplicate key error when copying sheets from different workbooks

### ISSUE THREAD

**Issue by Gaurav-Puri101187** [ClosedXML/ClosedXML#1843] opened 2022-07-26 11:18 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

I have 2 excel files with some custom formatting
ExcelTarget has some number custom formats as:
**<numFmts count="5"><numFmt numFmtId="164" formatCode="_(* #,##0_);_(* \(#,##0\);_(* &quot;-&quot;??_);_(@_)"/><numFmt numFmtId="165" formatCode="#,##0.0"/><numFmt numFmtId="167" formatCode="0.0%"/><numFmt numFmtId="168" formatCode="0.000"/><numFmt numFmtId="169" formatCode="0.0"/>**

Excel Source has number custom format as 
**<numFmts count="5"><numFmt numFmtId="164" formatCode="#,##0.0"/><numFmt numFmtId="165" formatCode="0.0%"/><numFmt numFmtId="166" formatCode="0.0"/><numFmt numFmtId="167" formatCode="0.000"/><numFmt numFmtId="169" formatCode="dd\-mm\-yyyy"/></numFmts>**

Now after copying some sheets from source to destination we get Duplicate key 169 can't be inserted error while saving.

I went through the source code and i believe XLWorkBook_Save.cs -> ResolveNumberFormats method doesn't handle the gaps between the style ids. 

**What is the expected behavior or new feature?**

File should be saved successfully.

**Is this a regression from the previous version?**

No.

## Reproducibility
Mentioned above.

```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment] 2023-03-26 19:23
Duplicate of #1679

**Closed as not planned by jahav** 2023-03-26 19:23 UTC
