### ISSUE TITLE
Microsoft.VisualStudio.Web.CodeGeneration.Design 6.0.6 and 6.0.7 breaks ClosedXml 

### ISSUE THREAD

**Issue by DerAlbertCom** [ClosedXML/ClosedXML#1840] opened 2022-07-23 15:15 UTC
I have an ASP.NET Core 6 Application. Using Closed XML 0.96 (problem is also on 0.95.4), with that I generate some Excel files.

Suddenly I've got this exception (it's an API, sorry for the JSON format).

```
{"type":"TypeInitializationException","title":"The type initializer for 'Gdip' threw an exception.","status":500,"detail":"   at System.Drawing.SafeNativeMethods.Gdip.GdipGetGenericFontFamilySansSerif(IntPtr& fontfamily)\
  at System.Drawing.FontFamily.GetGdipGenericSansSerif()\n   at System.Drawing.FontFamily.get_GenericSansSerif()
  at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
  at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont) 
  at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style)
  at ClosedXML.Excel.FontBaseExtensions.GetCachedFont(IXLFontBase fontBase, Dictionary`2 fontCache)
  at ClosedXML.Excel.FontBaseExtensions.GetWidth(IXLFontBase fontBase, String text, Dictionary`2 fontCache) 
  at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow, Int32 endRow, Double minWidth, Double maxWidth)
  at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow, Int32 endRow)  
  at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow)
/// .... rest is application stackstrace. not relevant. .. //
```

I develop on macOS and the Application  is running on Linux, happens on both systems. The libgdiplus “workarounds” are installed. And it worked without greater difficulties. But suddenly the above error happened.

On tracking down the issue, I saw that I bumped the Version Number of `Microsoft.VisualStudio.Web.CodeGeneration.Design` from 6.0.3 to 6.0.7. And that was the issue. Going back to 6.0.3 the Application was functional again. After some more Versions, I found out that 6.0.6 introduces this issue.

I have no Idea what some scaffolding NuGet has to do with that, but there must be something. I also filed this issue on https://github.com/dotnet/Scaffolding/issues/1958

Don't know if you can or are willing to fix this bizarre problem, I filed this issue for reference and when others stumble on this problem.

**Comment by jahav** [comment] 2022-07-23 15:26
Very likely a problem with common.drawing. It just doesn't work on NET6. I am working on it and it will be replaced soon #1805

I am closing this issue because anything related to common.drawing is very likely caused by the runtime errors it throws. If it persists even after the library is replaced, please open a new issue.

**Closed as completed by jahav** 2022-07-23 15:26 UTC

**Comment by deepchoudhery** [comment] 2022-12-11 06:32
@DerAlbertCom has this been an issue for you recently? Let me know if you run into this at version 6.0.10.
