### ISSUE TITLE
Apply AddConditionalFormat to a set of IXLCells

### ISSUE THREAD

**Issue by AlirezaInGitHub** [ClosedXML/ClosedXML#1002] opened 2018-09-17 23:53 UTC
I need to apply `AddConditionalFormat` to a set of `IXLCell`s than to a `IXLRange`. Unfortunately, I couldn't find a way to do so. Is it possible at all?
An alternative approach would be excluding some cells from a range. No luck in this neither.

Any suggestion is more than welcome.

**Comment by chaporovag** [comment] 2018-09-18 07:36
@AlirezaInGitHub You can apply _AddConditionalFormat_ to a single cell 
`using (var book = new XLWorkbook())
{
          var sheet = book.Worksheets.Add("test");
          sheet.Cell(1, 1).AddConditionalFormat()...
}
`
So, in this way you can create a cycle and apply conditional format for each cell from your collection separately.

**Comment by AlirezaInGitHub** [comment] 2018-09-18 07:39
@chaporovag I don't think it works for some cases specifically `ColorScale` as it needs a spectrum of values to determine color of each cell.

**Comment by Pankraty** [comment] 2018-09-18 07:49
Try this:
```
                    var ws = wb.Worksheets.Add("Sheet1");

                    var cf = ws.Range("A1:A5").AddConditionalFormat();
                    cf.Ranges.Add(ws.Range("C1:C5"));
                    cf.Ranges.Add(ws.Range("E1:E5"));

                    cf.ColorScale()
                        .LowestValue(XLColor.Red)
                        .Midpoint(XLCFContentType.Percent, "50", XLColor.Yellow)
                        .HighestValue(XLColor.Green);
```
Note that due to #973 the ranges in the resulted file may be not quite right, but this will be fixed later.

**Comment by AlirezaInGitHub** [comment] 2018-09-23 10:54
Hey @Pankraty,
Considering your code, how is it possible to exclude a cell say _C3_ from the `ConditionalFormat`. I tried the following approach, but still no luck. The format is applied to the range C1:C5.

```
cf.Ranges.Add(ws.Range("C1:C2"));

cf.Ranges.Add(ws.Range("C4:C5"));
```

**Comment by Pankraty** [comment] 2018-10-13 16:43
@AlirezaInGitHub, try the artifacts from (this build)[https://ci.appveyor.com/project/ClosedXML/closedxml/builds/19452625/job/1c6xy0gkeudffkrf/artifacts]. This should solve your problem with conditional formats.

**Comment by AlirezaInGitHub** [comment] 2018-10-17 11:30
@Pankraty No luck! Same result.

**Comment by igitur** [comment] 2019-01-10 16:01
I can't reproduce this issue anymore. I'm pretty sure #973 solve this. If it is still a problem, submit a new issue and complete the full issue template with proper code sample.

**Closed by igitur** 2019-01-10 16:01 UTC
