### ISSUE TITLE
DocumentFormat.OpenXml 3.0.2 / 3.1.0 not supported

### ISSUE THREAD

**Issue by johnnyreilly** [ClosedXML/ClosedXML#2379] opened 2024-08-01 07:33 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. [0.102.3](https://github.com/ClosedXML/ClosedXML/releases/tag/0.102.3)

**What is the current behavior?**

`dotnet build` results in:

> warning NU1608: Detected package version outside of dependency constraint: ClosedXML 0.102.2 requires DocumentFormat.OpenXml (>= 2.16.0 && < 3.0.0) but version DocumentFormat.OpenXml 3.1.0 was resolved.

when using DocumentFormat.OpenXml 3.1.0.  It seems likely this is the cause: https://github.com/ClosedXML/ClosedXML/blob/bec5851f89af7920d133d130425ec4cac038dc5b/ClosedXML/ClosedXML.csproj#L35

Would a prospective fix look like this? 

```xml
 <PackageReference Include="DocumentFormat.OpenXml" Version="[3.0.1,3.0.2,3.1.0,4.0.0)" /> 
```

**What is the expected behavior or new feature?**

Compatibility with DocumentFormat.OpenXml 3.1.0 (and 3.x generally I guess?)

**Is this a regression from the previous version?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**

Consider the following excerpt from a csproj file:

```
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.1.0" />
    <PackageReference Include="Microsoft.KernelMemory.Core" Version="0.69.240727.1" />
```

Run `dotnet build`, see this in the output:

> warning NU1608: Detected package version outside of dependency constraint: ClosedXML 0.102.2 requires DocumentFormat.OpenXml (>= 2.16.0 && < 3.0.0) but version DocumentFormat.OpenXml 3.1.0 was resolved.

See also: https://github.com/microsoft/kernel-memory/issues/725

Kernel Memory depends on a slightly older version of ClosedXML, but even when they upgrade they'll hit a similar issue due to the explicit version dependency.

**Comment by dluc** [comment] 2024-09-07 17:28
A fix would be really appreciated :-)

Parsing an Excel file with ClosedXML 0.104.0-preview2 + OpenXml to 3.1.0:
```
Unhandled exception. System.MissingMethodException: Method not found: 'DocumentFormat.OpenXml.OpenXmlElementList DocumentFormat.OpenXml.OpenXmlElement.get_ChildElements()'.
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
   at ClosedXML.Excel.XLWorkbook.Load(Stream stream)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream, LoadOptions loadOptions)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream)
```

**Comment by johnnyreilly** [comment] 2024-09-07 20:09
To quote @dluc's other findings:

> I did one more test with the latest release, and `ClosedXML` nugets are still incompatible with `DocumentFormat.OpenXml` v3, breaking Excel docs import.
> 
> The code in `ClosedXML` main branch works fine, but for some reason they stopped releasing nugets last year.
> 
> * ClosedXML `0.102.3` + OpenXml to 3.1.0 => **Exception**
> * ClosedXML `0.103.0-beta`  + OpenXml to 3.1.0 => **Exception**
> * ClosedXML `0.104.0-preview2` + OpenXml to 3.1.0 => **Exception**
> * ClosedXML `ef915a5db05a0a57499e34e418096228f097ffee` + OpenXml to 3.1.0 => **OK**
> 
> Exception:
> 
> ```
> Unhandled exception. System.MissingMethodException: Method not found: 'DocumentFormat.OpenXml.OpenXmlElementList DocumentFormat.OpenXml.OpenXmlElement.get_ChildElements()'.
>    at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
>    at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
> ```

Is there any reason that recent releases don't appear to be up to date with main?

**Comment by alexandregravouille** [comment] 2024-09-18 15:27
This is starting to be a big problem for us as we simply cannot downgrade to OpenXml 2.2.0 (which fixes the _Method not found_ exception) as we use another important library that needs >= OpenXml 3.0.2

**Comment by jahav** [comment] 2024-09-18 15:36
Try [0.104.0-rc1](https://www.nuget.org/packages/ClosedXML/0.104.0-rc1), it uses OpenXML SDK 3.0.

**Comment by jahav** [comment] 2024-09-18 15:43
Duplicate of #2220

**Closed as completed by jahav** 2024-09-18 15:43 UTC
