### ISSUE TITLE
Opening Excel File with pivot table

### ISSUE THREAD

**Issue by clt1dpw** [ClosedXML/ClosedXML#1780] opened 2022-04-01 21:01 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug? Maybe?
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
e.g. 0.95.4

Will not open Excel file with pivot table in it

I am using VB.Net.
This works perfectly with other spreadsheets.
Have one spread sheet to import that has 9 worksheets on it.
I need the second sheet and the pivot table is on sheet #5.
If I remove the sheet with the pivot table, I can then import the file.
It will not let me continue past the using line below.
Below the code is the stacktrace information.
I get the following 'The identifier `'` was not recognised. '
The sheet name is 'pivot table'. 
I have tried renaming it, but that did not work.
All other sheets have proper names with no special characters.
Again, removing the worksheet allows me to complete my code.
I would like to not have the user modify the spreadsheet if possible.

public void Main()
Using workBook As New XLWorkbook(WorkingFileName)
                Dim intCount As Integer = 1
                For Each sheet In workBook.Worksheets
                    'lstWorksheets.Items.Add(intCount & " - " & sheet.Name)
                    'PickSpreadSheet.lstWorkSheets.Items.Add(intCount & " - " & sheet.Name)
                    Debug.Print(intCount & " - " & sheet.Name)
                    intCount += 1
                Next
End Using

ClosedXML.Excel.CalcEngine.Exceptions.NameNotRecognizedException: The identifier `'` was not recognised. 
 at ClosedXML.Excel.CalcEngine.CalcEngine.ParseAtom() 
 at ClosedXML.Excel.CalcEngine.CalcEngine.ParseMulDivUnary() 
 at ClosedXML.Excel.CalcEngine.CalcEngine.ParsePower() 
 at ClosedXML.Excel.CalcEngine.CalcEngine.ParseMulDiv() 
 at ClosedXML.Excel.CalcEngine.CalcEngine.ParseAddSub() 
 at ClosedXML.Excel.CalcEngine.CalcEngine.ParseCompare() 
 at ClosedXML.Excel.CalcEngine.CalcEngine.Parse(String expression) 
 at ClosedXML.Excel.CalcEngine.ExpressionCache.get_Item(String expression) 
 at ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) 
 at ClosedXML.Excel.XLWorksheet.Evaluate(String expression) 
 at ClosedXML.Excel.XLCell.RecalculateFormula(String fA1) 
 at ClosedXML.Excel.XLCell.Evaluate(Boolean force) 
 at ClosedXML.Excel.CalcEngine.CellRangeReference.GetValue(IXLCell cell) 
 at ClosedXML.Excel.CalcEngine.CellRangeReference.GetValue() 
 at ClosedXML.Excel.CalcEngine.XObjectExpression.Evaluate() 
 at ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) 
 at ClosedXML.Excel.XLWorksheet.Evaluate(String expression) 
 at ClosedXML.Excel.XLCell.RecalculateFormula(String fA1) 
 at ClosedXML.Excel.XLCell.Evaluate(Boolean force) 
 at ClosedXML.Excel.CalcEngine.CellRangeReference.GetValue(IXLCell cell) 
 at ClosedXML.Excel.CalcEngine.CellRangeReference.GetValue() 
 at ClosedXML.Excel.CalcEngine.XObjectExpression.Evaluate() 
 at ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) 
 at ClosedXML.Excel.XLWorksheet.Evaluate(String expression) 
 at ClosedXML.Excel.XLCell.RecalculateFormula(String fA1) 
 at ClosedXML.Excel.XLCell.Evaluate(Boolean force) 
 at ClosedXML.Excel.XLCell.get_Value() 
 at ClosedXML.Excel.XLWorkbook.<>c.<LoadSpreadsheetDocument>b__272_10(IXLCell c) 
 at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() 
 at System.Linq.Enumerable.EnumerablePartition`1.MoveNext() 
 at System.Linq.Set`1.UnionWith(IEnumerable`1 other) 
 at System.Linq.Enumerable.DistinctIterator`1.FillSet() 
 at System.Linq.Enumerable.DistinctIterator`1.ToList() 
 at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) 
 at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet) 
 at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName) 
 at ClosedXML.Excel.XLWorkbook.Load(String file) 
 at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking) 
 at ClosedXML.Excel.XLWorkbook..ctor(String file) 
 at Budget.Main.ImportLaborAllocationToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\perry.wright\source\repos\Budget\Main.vb:line 271

- [ ] Cannot attach spreadsheet as it has sensitive data in it

**Comment by ladida28** [comment] 2022-05-01 08:24
Have you checked the name of the PivotTable itself? Maybe there are special characters.

**Comment by jahav** [comment] 2024-12-12 23:43
Closing the issue, because it's not reproducible and the code in exception has been removed long time ago. It threw somewhere in the old parser of formulas.

The original one didn't even handle arrays. The parser has been replaced two times since the original one.

**Closed by jahav** 2024-12-12 23:43 UTC
