### ISSUE TITLE
Calling SaveAs fails with validation error

### ISSUE THREAD

**Issue by somnatic** [ClosedXML/ClosedXML#156] opened 2017-01-16 08:13 UTC
Hi

I just wanted to try ClosedXml on a new project (I have used it in other projects in the past as well and am pretty happy with it) but the current Nuget version (0.86.0.0) always yields one of the following exceptions depending on whether I call `ws.Columns().AdjustToContents();` or not:

`w/  ws.Columns().AdjustToContents(); The attribute 'width' has invalid value '12.460625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[1]`

`wo/ ws.Columns().AdjustToContents(); The attribute 'left' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]`

I uploaded a minimum sample for you to try. The code is actually quite simple and I see no reason why it should fail. Executing SaveAs with False for the validation parameter yields the expected Excel document (Excel doesn't complain when it opens the file). Yet, I have a feeling that something is wrong here.

[bugex01.zip](https://github.com/ClosedXML/ClosedXML/files/707588/bugex01.zip)

Code sample:
```
static void Main(string[] args)
{
	// Nuget package ClosedXML 0.86.0.0 is used

	var wb = new XLWorkbook();

	var ws = wb.Worksheets.Add("123456");

	List<string> sncs = new List<string> {"123456789", "987654321", "0123456789", "0987654321"};

	int rowIndex = 1;   // 1-based for Excel
	foreach (var snc in sncs)
	{
		ws.Cell(rowIndex, 1).Style.NumberFormat.Format = "@";
		ws.Cell(rowIndex, 1).Value = snc;

		rowIndex++;
	}

	// ws.Columns().AdjustToContents(); // This line modifies the exception message but in any case this code will fail

	string filename = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "out.xlsx");
	wb.SaveAs(filename);

	// Fails with:
	/*
	 * w/  ws.Columns().AdjustToContents(); The attribute 'width' has invalid value '12.460625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[1]
	 * wo/ ws.Columns().AdjustToContents(); The attribute 'left' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
	 */
}
```

**Comment by igitur** [comment] 2017-01-16 08:42
Thanks. Under which UI culture are you running this? If it's not en-US, try running under en-US and see if it solves the problem.

**Comment by somnatic** [comment] 2017-01-16 08:57
Francois,

You are correct. My application is running under "de-AT". Using the following code to switch the thread's culture solves the problem:
`CultureInfo.DefaultThreadCurrentCulture = CultureInfo.CreateSpecificCulture("en-US");
CultureInfo ci = CultureInfo.CurrentCulture;
Console.WriteLine(ci.ToString());`

Not quite sure what to think of that.

**Comment by igitur** [comment] 2017-01-16 09:01
I'll have to force the en-US culture into the code before validating and restore the culture afterwards. It's not really an approach that I like. I'll see if there are better workarounds. In the meantime, do the temporary en-US culture as your own workaround.

**Comment by igitur** [comment] 2017-01-16 09:02
Duplicate of #152

**Closed by igitur** 2017-01-16 09:02 UTC

**Comment by igitur** [comment] 2017-01-16 11:30
This was fixed upstream in https://github.com/OfficeDev/Open-XML-SDK/pull/141 .

**Comment by igitur** [comment] 2017-01-20 09:35
Another temporary workaround is just to disable validation on save by using `SaveAs(..., false)`.

**Comment by igitur** [comment] 2017-03-20 10:33
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.
