### ISSUE TITLE
Huge memory usage generating Excel files

### ISSUE THREAD

**Issue by kendallb** [ClosedXML/ClosedXML#571] opened 2017-10-30 20:24 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

e.g. 0.90.0

**What is the current behavior?**

The library works fine, but it gobbles up a ridiculous amount of memory. I am using this project for our ExcelHelper library which uses ClosedXML for writing Excel files. We also support the commercial C1.Excel library which I am trying to get rid of, but I had to switch back to it because we were getting out of memory exceptions using ClosedXML for generating relatively large files. The file being generated is a little over 65,000 rows and the final resulting .xslx file about 11MB in size. Using the C1.Excel library for writing the file it used up about 500MB of memory. Using the ClosedXML library it gobbled up almost 4GB of memory to write the same file! That's almost 8x as much memory.

**What is the expected behavior or new feature?**

The library needs to be using a whole lot less memory.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

At this point I have a project I can reproduce this with using our own tools and code, but I can probably build a sample program for testing this as part of our ExcelHelper library so we can memory profile it and find out what is taking so much memory.

**Comment by igitur** [comment] 2017-10-30 20:26
This is a known issue.

Duplicate of #86

**Closed by igitur** 2017-10-30 20:26 UTC
