### ISSUE TITLE
UWP and Xamarin Forms support

### ISSUE THREAD

**Issue by TonyHenrique** [ClosedXML/ClosedXML#143] opened 2017-01-05 01:45 UTC
Please enable UWP and Xamarin Forms support

**Comment by igitur** [comment] 2017-01-05 08:57
I'm not very familiar with those. I thought they were UI architecture platforms. Please explain a bit more about how this affects ClosedXML.

**Comment by thyams** [comment] 2017-01-09 15:15
If I had to guess, he is wanting NetCore support.

[OpenXML](https://github.com/OfficeDev/Open-XML-SDK) is almost finished with their 1.7.0 release and Nuget which supports NetCore. I am utilizing the preview @TonyHenrique

**Comment by TonyHenrique** [comment] 2017-01-09 15:27
```
Restoring packages for 'AppMigradorExcel'.
Restoring packages for C:\Users\Tony\Documents\Clientes\Nossa Senhora\Paróquia Nossa Senhora das Graças\dados\AppMigradorExcel\AppMigradorExcel\project.json...
Package ClosedXML 0.86.0 is not compatible with uap10.0 (UAP,Version=v10.0). Package ClosedXML 0.86.0 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0.
Package ClosedXML 0.86.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm. Package ClosedXML 0.86.0 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm).
Package ClosedXML 0.86.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm-aot. Package ClosedXML 0.86.0 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
Package ClosedXML 0.86.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64. Package ClosedXML 0.86.0 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64).
Package ClosedXML 0.86.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64-aot. Package ClosedXML 0.86.0 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
Package ClosedXML 0.86.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86. Package ClosedXML 0.86.0 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86).
Package ClosedXML 0.86.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package ClosedXML 0.86.0 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for 'AppMigradorExcel'.
Package restore failed. Rolling back package changes for 'AppMigradorExcel'.
========== Finished ==========
Time Elapsed: 00:00:00.8015729

```

**Comment by igitur** [comment] 2017-01-09 15:31
Duplicate of #101

**Closed by igitur** 2017-01-09 15:31 UTC
