### ISSUE TITLE
General discussion about 0.96 priorities

### ISSUE THREAD

**Issue by igitur** [ClosedXML/ClosedXML#1395] opened 2020-04-16 15:50 UTC
@Pankraty @b0bi79 

Firstly, let's wait for 0.95 to be adopted widely and wait for the first wave of regressions to be sorted out.

Then the big tasks I would like to focus on for 0.96 are:
- Pivot table formats: We need to explicitly list all the pivot table formats and have test files for each individual format, as well as combinations of them. At the moment I have only combinations and makes the reverse-engineering of them almost impossible.
- Calculation engine context, for evaluation of e.g. `=ROW()` #1415 
- Formula repository / caching: #1201 addresses this already.
- `XLLoadOptions` to set some stuff, e.g. user-specified locale (#1367). Discussion at #1407 
- Support for external references, even if only partial support. The workbooks at least should not break.
- Refactor pivot tables into pivot sources + pivot tables
- Support pivot table calculated formulas (dependent on previous point).
- Protection: Align workbook and worksheet protection. Implement newer protection methods. 
- Improve loading of cell data. At the moment we parse the OpenXML Cell's text value, and then `ToString()` it immediately. I think we should delay the parsing of the text value until the cell's value has to be recalculated. 

Before any of you just start writing code, let's just chat. I have some PRs and branches locally that already address some of these issues.

**Comment by igitur** [comment] 2020-04-16 15:51
Feel free to add other points or comment on the above ones.

**Comment by Pankraty** [comment] 2020-04-17 07:59
I was thinking about refactoring saving/loading logic.

1. First, detach saving/loading from `XLWorkbook` class into separate classes implementing `IXLWorkbookReader` and `IXLWorkbookWriter`.
2. Then, provide the alternative implementations
    * `XLInMemoryWorkbookReader`, `XLInMemoryWorkbookWriter` - basically, the current implementation, fully initializing the entire workbook in memory. Maybe it has to take care of #912 also.
    * `XLReadOnlyWorkbookReader` - a fast implementation with lazy loading of needed sections in a read-only mode. It may help with  #781, #1345, and many other scenarios where we only need to read some data and do not really care about formats, data validations, etc. This cannot work without accessing the original stream by design.
    * `XLStrictModeWorkbookReader`, `XLStrictModeWorkbookWriter` - to operate with workbooks using strict mode (#1378).

This would also open a window for supporting different formats, maybe sometime in the future.

**Comment by Pankraty** [comment] 2020-04-17 08:16
Other considerations are about providing some degree of extensibility.

For example, in #1389 I prepared the infrastructure that may let the user implement their own `IInsertDataReader` implementation if they need some custom logic: all they have to do is to implement the interface and override `InsertDataReaderFactory` so it would instantiate that custom reader when needed (at the current stage it is not possible, but can be easily adjusted).

Another application that came into my mind, is to get some extension point where the user can specify a custom mechanism for searching external references. For example, the default implementation may simply ignore them while the more comprehensive one would look for workbooks in a certain folder - and this will be up to the user to provide such implementation. I see this somewhat similar to how external files are searched for in AutoCAD (http://help.autodesk.com/view/OARX/2019/ENU/?guid=OREFNET-Autodesk_AutoCAD_DatabaseServices_HostApplicationServices_FindFile_string_Database_Autodesk_AutoCAD_DatabaseServices_FindFileHint).

So, first of all we have to decide how we will provide that extensibility and then add it where applicable.

**Comment by igitur** [comment] 2020-04-17 10:19
> I was thinking about refactoring saving/loading logic.
> 
> < /snip> 

I agree on this. I've been wanting to refactor those massive classes for a while now. However, I don't think I have the energy to deal with daily merge conflicts, so I think we should leave this to a later release, maybe 0.97, and then we agree that we don't touch `XLWorkbook*.cs` in any other branch until we've merged this refactoring. Then we release 0.97 with only this refactoring as the only change. What do you think?

**Comment by Pankraty** [comment] 2020-04-17 10:51
Yes, this sounds reasonable. We can, of course, prepare the internal API and maybe some parts of the implementation without touching `XLWorkbook*.cs` before the freeze; it will not cause merge conflicts and may be done at any time. And after it is ready we'll be able to start refactoring the existing code, freezing it from other changes, as you said.

**Comment by shaggygi** [comment] 2020-04-18 16:21
Any plans to add Power Query/Pivot features?  I don't have specifics, just curious if that is a possibility.  BTW... just started using this API and is pretty awesome 👍.  Thx

**Comment by igitur** [comment] 2020-04-18 16:43
> Any plans to add Power Query/Pivot features? I don't have specifics, just curious if that is a possibility. BTW... just started using this API and is pretty awesome . Thx

No, we're nowhere near that. Sorry.

**Comment by timunie** [comment] 2021-04-22 06:24
Hi ClosedXML Team, 

first of all this is a great library and it makes my life really easier 👍 . For me it would be a great enhancement if I could pick from named predefined styles. I read a template with custom `CellStyles` in it and want to apply those. I think there is already a ticket open for this #1290 .

Happy coding
Tim

**Comment by AjayChauhan1982** [comment] 2021-08-24 05:22
Hi,

Currently Shapes are supported while saving excel file using Save() or SaveAs() methods. Any plan to add this in 0.96, there is already a open ticket for this #1252

**Comment by jahav** [comment] 2022-10-07 16:46
I am closing this issue because the 0.96 has been released and project has been in stasis for about a year.
All are worthy goals and some will be done in reasonably near future (engine context, formula caching, culture in LoadOptions).

**Closed by jahav** 2022-10-07 16:46 UTC
