### ISSUE TITLE
Get "Identifier expected." when try to read a value

### ISSUE THREAD

**Issue by MarkusHiller** [ClosedXML/ClosedXML#239] opened 2017-03-09 19:45 UTC
If my formula references a value on another worksheet that has a space in the name, then an error is thrown.

After the rename, the formula is calculated correctly.

```
Message: Identifier expected.
StackTrace:    bei ClosedXML.Excel.CalcEngine.CalcEngine.Throw(String msg) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 681.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.GetToken() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 589.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.GetParameters() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 629.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParseAtom() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 353.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParseUnary() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 332.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParsePower() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 313.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParseMulDiv() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 303.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParseAddSub() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 293.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParseCompare() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 283.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParseExpression() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 280.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.GetParameters() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 637.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParseAtom() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 353.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParseUnary() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 332.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParsePower() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 313.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParseMulDiv() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 303.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParseAddSub() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 293.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParseCompare() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 283.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.ParseExpression() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 280.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.Parse(String expression) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 81.
   bei ClosedXML.Excel.CalcEngine.ExpressionCache.get_Item(String expression) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\ExpressionCache.cs:Zeile 47.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 108.
   bei ClosedXML.Excel.CalcEngine.CellRangeReference.GetValue(IXLCell cell) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\XLCalcEngine.cs:Zeile 82.
   bei ClosedXML.Excel.CalcEngine.CellRangeReference.GetValue() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\XLCalcEngine.cs:Zeile 57.
   bei ClosedXML.Excel.CalcEngine.XObjectExpression.Evaluate() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:Zeile 499.
   bei ClosedXML.Excel.CalcEngine.Expression.CompareTo(Expression other) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:Zeile 165.
   bei ClosedXML.Excel.CalcEngine.BinaryExpression.Evaluate() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:Zeile 262.
   bei ClosedXML.Excel.CalcEngine.Expression.op_Implicit(Expression x) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:Zeile 112.
   bei ClosedXML.Excel.CalcEngine.Logical.Or(List`1 p) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Functions\Logical.cs:Zeile 34.
   bei ClosedXML.Excel.CalcEngine.FunctionExpression.Evaluate() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:Zeile 335.
   bei ClosedXML.Excel.CalcEngine.Expression.op_Implicit(Expression x) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:Zeile 112.
   bei ClosedXML.Excel.CalcEngine.Logical.If(List`1 p) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Functions\Logical.cs:Zeile 46.
   bei ClosedXML.Excel.CalcEngine.FunctionExpression.Evaluate() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:Zeile 335.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 112.
   bei ClosedXML.Excel.CalcEngine.CellRangeReference.GetValue(IXLCell cell) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\XLCalcEngine.cs:Zeile 82.
   bei ClosedXML.Excel.CalcEngine.CellRangeReference.GetValue() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\XLCalcEngine.cs:Zeile 57.
   bei ClosedXML.Excel.CalcEngine.XObjectExpression.Evaluate() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:Zeile 499.
   bei ClosedXML.Excel.CalcEngine.Expression.CompareTo(Expression other) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:Zeile 166.
   bei ClosedXML.Excel.CalcEngine.Functions.Lookup.<>c__DisplayClass2_0.<Vlookup>b__0(IXLRangeRow r) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Functions\Lookup.cs:Zeile 98.
   bei ClosedXML.Excel.XLRange.FindRow(Func`2 predicate) in C:\Git\ClosedXML\ClosedXML\Excel\Ranges\XLRange.cs:Zeile 830.
   bei ClosedXML.Excel.CalcEngine.Functions.Lookup.Vlookup(List`1 p) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Functions\Lookup.cs:Zeile 98.
   bei ClosedXML.Excel.CalcEngine.FunctionExpression.Evaluate() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:Zeile 335.
   bei ClosedXML.Excel.CalcEngine.Logical.If(List`1 p) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Functions\Logical.cs:Zeile 50.
   bei ClosedXML.Excel.CalcEngine.FunctionExpression.Evaluate() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:Zeile 335.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 112.
   bei ClosedXML.Excel.XLWorksheet.Evaluate(String expression) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorksheet.cs:Zeile 1462.
   bei ClosedXML.Excel.XLCell.get_Value() in C:\Git\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:Zeile 406.
   bei ClosedXML.Excel.CalcEngine.Functions.Lookup.Vlookup(List`1 p) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Functions\Lookup.cs:Zeile 117.
   bei ClosedXML.Excel.CalcEngine.FunctionExpression.Evaluate() in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\Expression.cs:Zeile 335.
   bei ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) in C:\Git\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:Zeile 112.
   bei ClosedXML.Excel.XLWorksheet.Evaluate(String expression) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorksheet.cs:Zeile 1462.
   bei ClosedXML.Excel.XLCell.get_Value() in C:\Git\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:Zeile 406.
```

**Comment by igitur** [comment] 2017-03-13 08:58
I was under the impression that no references to external sheets are supported yet, whether there's a space in the external filename or not. Can you confirm that the calculation succeeds for an external file without a space? If so, is it possible to attach the 2 files to this issue?

**Comment by MarkusHiller** [comment] 2017-03-13 10:17
i can confirm that the calculation success for calculation inside one workbook with two worksheets, but only if the worksheet name dont contains a space.

Calculation with two different workbooks are not tested.

**Comment by igitur** [comment] 2017-03-13 10:38
Sorry, my bad. I misread. Yes, worksheets with a space in the name is a known issue. I'm closing this as a duplicate of #175 .

**Closed by igitur** 2017-03-13 10:38 UTC
