### ISSUE TITLE
STOCKHISTORY formula not evaluating after writing in the file

### ISSUE THREAD

**Issue by XJTLUmedia** [ClosedXML/ClosedXML#2034] opened 2023-03-20 07:04 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.100.3

**What is the current behavior?**

I'm getting an name error
![image](https://user-images.githubusercontent.com/102778070/226268812-76df260f-4868-4af9-8154-2fb0892e8f7f.png)

But the formula itself is not wrong, because when I click the formula and press "enter" the formula runs and works
![image](https://user-images.githubusercontent.com/102778070/226269007-1a3085b6-d39c-479c-974a-0826169dbf61.png)

You can test it by replace array[i] with string value "AA", "AAPL" and so on
**What is the expected behavior or new feature?**

it should be looking like second image screenshot. So I can read data from output excel directly.

**Is this a regression from the previous version?**

YES

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
static void Main(string[] args)
        {
            var workbook = new XLWorkbook($@"C:\Finance\SP500\output\dailyboard.xlsx");
            var worksheet = workbook.Worksheet("Sheet1");
            var range = worksheet.RangeUsed().Column(1);
            var array= new List<string>();
            foreach (var cell in range.CellsUsed())
            {
                array.Add(cell.Value.ToString());
            }
            using (var workbook2 = new XLWorkbook())
            {
                // Apply formula to each cell in column A
                for (int i = 2; i <= 10; i++)
                {   
                    var worksheet2 = workbook2.Worksheets.Add("Sheet1");
                    works
[dailyboard.xlsx](https://github.com/ClosedXML/ClosedXML/files/11015025/dailyboard.xlsx)
heet2.Range("A1").FormulaA1 = "{=STOCKHISTORY("+"\""+array[i]+"\""+",TODAY()-16,TODAY(),0,1,0,2,3,4,1,5)}";
                    SaveOptions? saveOptions = new SaveOptions()
                        {
                        EvaluateFormulasBeforeSaving = true
                        };
                    workbook2.SaveAs($@"C:\Finance\SP500\output\" +array[i]+".xlsx");
                    worksheet2.Delete();
                }
            }
            
        }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment] 2023-03-22 00:21
There are three things in this:
### Stock data type
Stock data type is O365 only type, implemented as an extension of metadata part. That is not described in the standard and unless MS provides a good spec, it will likely never be implemented (reverse engineering and all of other fun stuff).

### Function STOCKHISTORY is not implemented
STOCKHISTORY needs a server to provide data about stocks. The function itself needs at least Excel for O365 subscription (otherwise it provides #BLOCKED! error). 
ClosedXML doesn't have a server to provide such data and likely never will. This will could be supported only as a custom function through #1327.

### Array formulas not working
Duplicate of #1812

**Closed as not planned by jahav** 2023-03-22 00:21 UTC
