### ISSUE TITLE
'System.ApplicationException' 

### ISSUE THREAD

**Issue by ltlombardi** [ClosedXML/ClosedXML#178] opened 2017-01-29 10:59 UTC
_Additional information: The attribute 'left' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'right' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'top' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'footer' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]._

I'm running Visual Studio 2015 community fresh install. Target framework is .NET 4.5.6. ClosedXML from nuget version 0.86.0, and the program is the HelloWorld Example:

`        static void Main(string[] args)
        {
            var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Sample Sheet");
            worksheet.Cell("A1").Value = "Hello World!";
            workbook.SaveAs("HelloWorld.xlsx");
        }`

Even with the exception, the excel file (attached) is been created in bin/debug folder. This is my firs try with ClosedXml.
Hitting Continue on the debugger, just throws the same exception again and again.
Everything else you need just let me know. 😉 
[HelloWorld.xlsx](https://github.com/ClosedXML/ClosedXML/files/737448/HelloWorld.xlsx)

**Comment by igitur** [comment] 2017-01-29 12:30
Duplicate of #152

**Closed by igitur** 2017-01-29 12:30 UTC
