### ISSUE TITLE
UnaryExpression does not handle strings

### ISSUE THREAD

**Issue by mathlang** [ClosedXML/ClosedXML#1487] opened 2020-08-04 06:55 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

When placed inside an expression, +A1 or -A1 will return 0 if A1 is a string

**What is the expected behavior or new feature?**

The Excel behavior is as follows:

Leading + should be ignored. CalcEngine.Parse already does that:
            ```
// skip leading +'s
while (_len > _ptr && _expr[_ptr] == '+')
    _ptr++;
```

- String = #VALUE in Excel

**Is this a regression from the previous version?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    using (var wb = new ClosedXML.Excel.XLWorkbook())
    {
        var ws = wb.AddWorksheet("Sheet1");
        ws.Cell("A1").Value = "StringValue";

        // Must be within another expression (IF) because parser will strip + if by itself (eg: =+A1)
        var plusString = ws.Evaluate("=IF(1 = 1, +A1, +A1)");
        // plusString = 0                

        var minusString = ws.Evaluate("IF(1 = 1, -A1, -A1)");
        // minusTring = 0
    }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment] 2022-10-27 15:37
Duplicate of #1812, handling of various combinations of types should be fine.

**Closed by jahav** 2022-10-27 15:37 UTC
