### ISSUE TITLE
Table Convert to Range

### ISSUE THREAD

**Issue by edemircipg** [ClosedXML/ClosedXML#1593] opened 2021-01-13 21:41 UTC
Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3
0.95.4 nuget package

**What is the current behavior?**

It works awesome and I sincerely thank you for providing this to the world, for free nonetheless.  I have a question I cannot find an answer to in your documentation (new wiki), or examples, or on the web

I create a new worksheet like this 
// create a new workbook
wb = new XLWorkbook();

// create a new worksheet using the supplied datatable as an argument
ws = wb.Worksheets.Add(p_DT, "data");

It appears by default (and no other choice) DataTable used to create a worksheet comes in as a Table in Excel.  Excel has a button inside Table Design called Convert to Range, which essentially removes the 'table' but leaves the data untouched (so long as there are no references).  The theme is left behind, so you must remove the theme (banded rows) first before you convert to range.

The question is:
Does ClosedXML support the same thing as Excel's Convert to Range?  I understand there is a function that returns a range, but that is not my question.  I am asking if ClosedXML can convert a table to a range, just like Convert to Range does in excel.

**What is the expected behavior or new feature?**

Complete this.
Remove a table just as Excel's Convert to Range does.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

There are no issues to reproduce.  It is a question, or at best, a feature request if the feature does not exist.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Pitterling** [comment] 2021-01-14 13:47
looks like duplicate of #1559

**Comment by Pankraty** [comment] 2021-01-17 15:21
Thanks @Pitterling this looks like a duplicate indeed.

@edemircipg here is a detailed answer https://github.com/ClosedXML/ClosedXML/issues/1559#issuecomment-731725036. 
TL/DR: `ws.Tables.Remove(tableName);` to the rescue.

**Closed by Pankraty** 2021-01-17 15:21 UTC
