### ISSUE TITLE
System.InvalidOperationException: Dynamic operations can only be performed in homogenous AppDomain

### ISSUE THREAD

**Issue by Troi7** [ClosedXML/ClosedXML#1494] opened 2020-08-15 12:24 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [ ] Feature
- [x ] Question

**Did you test against the latest CI build?**
- [ x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

I've just switch all my SharePoint projects to .NET 4.8 from .NET 4.5.2 and I've updated ClosedXML from 0.88 to 0.95.3. 

Now I've problem with dynamic variables in IIS process of SharePoint. web.config contains settings "legacyCasModel=true" that is not compatible with dynamic used in ClosedXML and it throws InvalidOperationException. My question is:
	- What is the last version of ClosedXML without dynamic variables?
	- Would it be possible to not use "dynamic" in future versions of ClosedXML?

SharePoint Timer service has settings NetFx40_LegacySecurityPolicy enabled="false" that is compatible with dynamic.

_08/14/2020 19:39:02.47 	w3wp.exe (0x4C90)                       	0x1C64	SharePoint Foundation         	Runtime                       	tkau	Unexpected	System.InvalidOperationException: Dynamic operations can only be performed in homogenous AppDomain.    at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)     at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)     at ClosedXML.Utils.OpenXmlHelper.FillFromClosedXMLColor(Object openXMLColor, XLColor xlColor, Boolean isDifferential)     at ClosedXML.Excel.XLWorkbook.GetNewFont(FontInfo fontInfo, Boolean ignoreMod)     at ClosedXML.Excel.XLWorkbook.ResolveFonts(WorkbookStylesPart workbookStylesPart, SaveContext context)     at ClosedXML.Excel.XLWorkbook.GenerateWorkbookStylesPartContent(WorkbookStylesPart workbookStylesPart, SaveContext context)     at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocum...	a803709f-520f-0087-b163-a327a7adadbf
08/14/2020 19:39:02.47*	w3wp.exe (0x4C90)                       	0x1C64	SharePoint Foundation         	Runtime                       	tkau	Unexpected	...ent document, SaveOptions options)     at ClosedXML.Excel.XLWorkbook.CreatePackage(Stream stream, Boolean newStream, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)     at ClosedXML.Excel.XLWorkbook.SaveAs(Stream stream, SaveOptions options)_

**What is the expected behavior or new feature?**

Version of ClosedXML without dynamic fields, parameters and variables.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
using System;
using System.Data;
using System.IO;
using ClosedXML.Excel;

public void Main()
{
            DataTable resultTable = new DataTable();
            resultTable.Columns.Add("Title");
            DataRow row = resultTable.NewRow();
            row["Title"] = "My Title";
            resultTable.Rows.Add(row);

            using (XLWorkbook workbook = new XLWorkbook())
            {
                workbook.Worksheets.Add(resultTable, "My sheet");

                using (MemoryStream stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    byte[] excelData = stream.ToArray();
                }
            }
}
```

App.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8"/>
  </startup>
  <runtime>
    <NetFx40_LegacySecurityPolicy enabled="true" />
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="DocumentFormat.OpenXml" publicKeyToken="8fb06cb64d019a17" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.11.3.0" newVersion="2.11.3.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment] 2020-08-15 12:31
Duplicate of #1281 . We plan to remove the use of `dynamic`.

**Comment by Troi7** [comment] 2020-08-15 12:37
Thanks for the answer. I'll use older version of ClosedXML temporarily. Do you know what latest version doesn't use dynamics?

**Comment by igitur** [comment] 2020-08-15 12:51
The `dynamic` was introduced in #949, but I can't tell offhand in which version it was released. It seems we failed to tag the milestone for that PR.

**Comment by Troi7** [comment] 2020-08-15 14:12
I've performed some tests. It works fine with 0.93.1. Version 0.94.0 already uses `dynamic`.

**Closed** 2020-09-25 11:37 UTC
