### ISSUE TITLE
Checkbox name is not kept when loaded and saved

### ISSUE THREAD

**Issue by nathanQiu1** [ClosedXML/ClosedXML#777] opened 2018-04-12 12:15 UTC
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.102.1 ~0.93.0~

**What is the current behavior?**

When file is load and saved, the name of a checkbox is not kept. The original names are _dadawww_, _tttt_, _sss_, but after load/save cycle, they are _Check Box 2_, _Check Box 1_ and _Check_.

**What is the expected behavior or new feature?**

The checkbox text shoudl be kept.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    using (XLWorkbook workbook = new XLWorkbook(@"checkbox.xlsx"))
   {
       workbook.Save();
   }

}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[checkbox.xlsx](https://github.com/ClosedXML/ClosedXML/files/1903026/checkbox.xlsx)

**Comment by nathanQiu1** [comment] 2018-04-13 01:04
Strange!When this sheet has images, checkbox text is normal, and if there is no image, it will overlap.

**Comment by nathanQiu1** [comment] 2018-04-17 00:50
Updated the latest code, Office2010 will have this problem. Office2016 no.

**Comment by igitur** [comment] 2018-04-20 10:04
Sounds like a bug in Office 2010 then.

**Comment by nathanQiu1** [comment] 2018-05-08 05:36
@igitur  Sorry to bother you. Is there a solution for office2010?

**Comment by igitur** [comment] 2018-05-08 05:39
Unfortunately not. Time to upgrade.

**Comment by jahav** [comment] 2023-10-25 22:35
Duplicate of #2202

**Closed by jahav** 2023-10-25 22:35 UTC
Labels: bug, feature:controls, area:load/save, triaged
