### ISSUE TITLE
Pivot table broken from 0.95.0

### ISSUE THREAD

**Issue by Juakali** [ClosedXML/ClosedXML#1588] opened 2021-01-07 14:35 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4 (0.95.0 and higher)

**What is the current behavior?**

When creating an excel with the provided example for pivot table (from version 0.95.0) I got an error when opening the excel. 
Removed Part: /xl/pivotTables/pivotTable.xml part with XML error.  (PivotTable view) HRESULT 0x8000ffff Line 1, column 0.

**What is the expected behavior or new feature?**

The pivot table example (pivot table) should work like in version 0.94.2

**Is this a regression from the previous version?**

Version 0.94.2 is working, 0.95.0 and higher not.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Just use the pivot sample code in the Git repository.

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
- [x] broken 0.95.4 [pv.xlsx](https://github.com/ClosedXML/ClosedXML/files/5782151/pv.xlsx)
- [x] working 0.94.2 [pv_0-94-2.xlsx](https://github.com/ClosedXML/ClosedXML/files/5782155/pv_0-94-2.xlsx)

**Comment by igitur** [comment] 2021-01-10 14:37
This might be due to a bug in DocumentFormat.OpenXML v2.12.0. What version are you referencing?

**Comment by Juakali** [comment] 2021-01-10 16:49
> This might be due to a bug in DocumentFormat.OpenXML v2.12.0. What version are you referencing?

I'm indeed using v2.12.0.

**Comment by igitur** [comment] 2021-01-10 17:08
Try downgrading to 2.11.3

**Comment by igitur** [comment] 2021-01-11 07:34
Refer to https://github.com/OfficeDev/Open-XML-SDK/pull/774#issuecomment-757482273 for bug report.

**Comment by igitur** [comment] 2021-01-12 08:14
[OpenXML v2.12.1](https://www.nuget.org/packages/DocumentFormat.OpenXml/2.12.1) has been released. Please upgrade to that and confirm whether the problem is solved.

**Comment by jahav** [comment] 2024-12-15 17:06
Closing as fixed. Back then it was likely fixed by upgrade of OpenXML.

This was caused by extra `<format/>` tag in the `pivotTable{number}.xml`. When I manually removed `<format/>` tags from file, Excel loaded the file without problem.

The root cause was likely OpenXML dependency as mentioned in previous comments. OpenXML  was used then to write pivot table definition. The pivot table definition is now written manually by `PivotTableDefinitionPartWriter2` and there is no such element.

![image](https://github.com/user-attachments/assets/a0ca05c2-03c8-4edc-9ddc-098c1da4e8e6)

**Closed by jahav** 2024-12-15 17:06 UTC
