### ISSUE TITLE
The type initializer for 'Gdip' threw an exception

### ISSUE THREAD

**Issue by P9avel** [ClosedXML/ClosedXML#1853] opened 2022-08-18 11:02 UTC
Hello, i am used worksheet.Columns().AdjustToContents() and get exeption in docker image. Now i am did

RUN apt-get update && apt-get install -y libgdiplus in docker file
in running file
I think in next .Net 7 version MS not will support System.Drawing. Possible can you to rewrite code for crossplatforming drawing dll?

**Comment by jahav** [comment] 2022-09-06 19:12
Project has been on a hiatus for while. Working on it.
Duplicate of #1805

**Closed as completed by jahav** 2022-09-06 19:12 UTC
