### ISSUE TITLE
After deleting a range its "RangeAddress.IsValid" property is still "True"

### ISSUE THREAD

**Issue by traf72** [ClosedXML/ClosedXML#2429] opened 2024-10-03 14:43 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.104.1

**What is the current behavior?**

The `RangeAddress.IsValid` property returns `True` after deleting the range.

**What is the expected behavior?**

The `RangeAddress.IsValid` property should return `False` after deleting the range.

**Is this a regression from the previous version?**
- [x] Yes. It worked correctly in version 0.102.2

## Reproducibility

**Code to reproduce problem:**
```c#
private static void Main()
{
    var wb = new XLWorkbook();
    var ws = wb.AddWorksheet();

    var range1 = ws.Range(3, 3, 5, 5); // C3:E5
    var range2 = ws.Range(4, 7, 4, 8); // G4:H4

    var mergedRange = MergeRanges(range1, range2); // Expected Range is "C3:H5" and it's calculated correctly

    range1.Delete(XLShiftDeletedCells.ShiftCellsLeft); // Deleting "range1"

    Console.WriteLine(range1.RangeAddress.IsValid); // "IsValid" property is "True" though should be "False", because "range1" was deleted
}

private static IXLRange MergeRanges(IXLRange range1, IXLRange range2)
{
    var ws = range1.Worksheet;

    var newRangeFirstCell = ws.Cell(Math.Min(range1.FirstRow().RowNumber(), range2.FirstRow().RowNumber()),
        Math.Min(range1.FirstColumn().ColumnNumber(), range2.FirstColumn().ColumnNumber()));
    var newRangeLastCell = ws.Cell(Math.Max(range1.LastRow().RowNumber(), range2.LastRow().RowNumber()),
        Math.Max(range1.LastColumn().ColumnNumber(), range2.LastColumn().ColumnNumber()));

    return ws.Range(newRangeFirstCell, newRangeLastCell);
}
```
- [x] I attached a sample project where the issue exists.

[ClosedXmlBug.zip](https://github.com/user-attachments/files/17245902/ClosedXmlBug.zip)

**Comment by jahav** [comment] 2024-10-03 15:49
That is by design. The whole concept that ranges will somehow shift on their own is going away. `IXLCell` no longer shift, for ranges, it is going away. ClosedXML will keep track of workbook elements (e.g. merged cells or sparklines ect.) and modify them when workbook changes, not arbitrary ranges.

**Closed as not planned by jahav** 2024-10-03 15:49 UTC
