### ISSUE TITLE
ExpressionParseException on cell.GetValue with a formula using table headers

### ISSUE THREAD

**Issue by Stefan-Denner** [ClosedXML/ClosedXML#700] opened 2018-02-23 11:21 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.90.0.0

**What is the current behavior?**

When I define a table within a worksheet, I can use the header of the table as an identifier of a formula.
Here an example:

Header1|Header2|Header3
---------|----------|---------
Value1 | Value2 | `=[Header1]& " + " &[Header2]`

Excel evaluates this formula to become "Value1 + Value2". I attached a spreadsheet as an example: [TableWithColumnFormula.xlsx](https://github.com/ClosedXML/ClosedXML/files/1751419/TableWithColumnFormula.xlsx) (Excel version: Microsoft Office Professional Plus 2013).

But when I try to access the value of this cell (e.g. `cell.GetValue<string>();`), I get a "ClosedXML.Excel.CalcEngine.ExpressionParseException"
```
ClosedXML.Excel.CalcEngine.ExpressionParseException : Expected end of expression
   at ClosedXML.Excel.CalcEngine.CalcEngine.Throw(String msg) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 822
   at ClosedXML.Excel.CalcEngine.CalcEngine.Parse(String expression) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 93
   at ClosedXML.Excel.CalcEngine.ExpressionCache.get_Item(String expression) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\ExpressionCache.cs:line 47
   at ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 118
   at ClosedXML.Excel.XLCell.get_Value() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:line 386
   at ClosedXML.Excel.XLCell.TryGetValue[T](T& value) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:line 1336
   at ClosedXML.Excel.XLCell.GetValue[T]() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:line 274
...
```

**What is the expected behavior or new feature?**

When I access the cell (e.g. `cell.GetValue<string>();`) I should get a string that equals "Value1 + Value2".

**Did this work in previous versions of our tool?  Which versions?**

I don't know

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
      var filePath = "<pathToFile>";  // Define path to the attached file
      var workbook = new XLWorkbook (filePath);
      var worksheet = workbook.Worksheet (1);
      var table = worksheet.Table (0);
      var cell = table.DataRange.Row (1).Field ("Header3");
      var value = cell.GetValue<string>(); // throws ExpressionParseException
}
```

- [x] I attached a sample spreadsheet. [TableWithColumnFormula.xlsx](https://github.com/ClosedXML/ClosedXML/files/1751419/TableWithColumnFormula.xlsx)

**Comment by igitur** [comment] 2018-02-23 11:28
Duplicate of #271

**Closed by igitur** 2018-02-23 11:28 UTC
Labels: duplicate

**Comment by Stefan-Denner** [comment] 2018-02-23 11:31
Hi igitur!
Sry, I overlooked that other issue.
Thx for the fast response 👍

**Comment by igitur** [comment] 2018-02-23 11:33
No problem.

Francois Botha
