### ISSUE TITLE
Formatting issues with spreadsheet

### ISSUE THREAD

**Issue by kwshiraz** [ClosedXML/ClosedXML#1850] opened 2022-08-09 12:43 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Did you test against the latest CI build?**
- [x] Yes

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

 0.96

**What is the current behavior?**

I am using ClosedXML to set cell values in an existing spreadsheet. The VM i am using does not have Excel Installed.
The excel file produced has a size of 106KB.

When I take the 106 KB excel file to a different VM which has Excel Installed and try to upload it on a portal it complains about incorrect formatting.

However, when I open the  106KB excel file and Click Save, the size of the file increases to 120 KB.

The portal now accepts this same 120KB file without any formatting complaints. I dont know why the size increases to 120KB

I am using the SetValue<string> to set the values in cell.

**What is the expected behavior or new feature?**

No formating issues in spreadsheet.

**Is this a regression from the previous version?**
No.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
                          using(IXLWorkbook workbook = new XLWorkbook(@"c:\Temp.xlsx"))
                          {
                          IXLWorksheet Worksheet = workbook.Worksheet("Upload Sheet");
                          Worksheet.Cell("A1").SetValue<string>("abc123");
                          Worksheet.Cell("B1").SetValue<string>("def456");
                          workbook.SaveAs("FileToUpload.xlsx");
                          }
}
```

**Comment by kwshiraz** [comment] 2022-08-10 04:40
I just switched over to EPPLUS for excel updates and it worked like a charm. No file corruption issues with epplus

**Comment by jahav** [comment] 2022-08-11 07:46
Could you please be more specific and provide **minimal** reproducible example?
* The code is missing the Temp.xlsx (I guess it needs Upload Sheet and some other data)
* There is no file before (the) or after (the larger one) so we know the before and after. 
* What VM? Linux, Windows, Mac
* What portal? Your company, Azure?

**Comment by jahav** [comment] 2022-08-22 09:10
Closing due to insufficient information.

**Closed as completed by jahav** 2022-08-22 09:10 UTC
