### ISSUE TITLE
ArgumentOutOfRangeException in XLHelper.cs line 117

### ISSUE THREAD

**Issue by PenCoDK** [ClosedXML/ClosedXML#1477] opened 2020-07-17 08:08 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Did you test against the latest CI build?**
- [x ] Yes

**Version of ClosedXML**
0.95.3

**What is the current behavior?**
No data is read

**What is the expected behavior or new feature?**
To read the data.
I have just updated a working program to the new version 0.95.3
After that the data in one of the speadsheet (“Data”) is being read.
The first sheet (“Stamoplysninger”) is read prefect.

After a bit of research, I realised that ws2 in the following line of code did not contain any data but had thrown an exception.

Dim ws2 As IXLWorksheet = XL.Worksheet("Data")

| ColumnLetter | 'DirectCast(ws,   ClosedXML.Excel.XLWorksheet).InvalidAddress.ColumnLetter' threw an exception   of type 'System.ArgumentOutOfRangeException' | String   {System.ArgumentOutOfRangeException}

   at ClosedXML.Excel.XLHelper.GetColumnLetterFromNumber(Int32 columnNumber, Boolean trimToAllowed) in C:\projects\closedxml\ClosedXML\XLHelper.cs:line 117
   at ClosedXML.Excel.XLAddress.
[51303_s_langeland_herred_1802-1820_aurelia.xlsx](https://github.com/ClosedXML/ClosedXML/files/4936492/51303_s_langeland_herred_1802-1820_aurelia.xlsx)
get_ColumnLetter() in C:\projects\closedxml\ClosedXML\Excel\Coordinates\XLAddress.cs:line 198

- [x ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment] 2020-07-17 16:27
I can't reproduce this problem using the latest development version. 

This is my test code
```c#
public static void OpenTestFile()
{
    using var wb = new XLWorkbook("51303_s_langeland_herred_1802-1820_aurelia.xlsx");
    var ws = wb.Worksheet("Data");

    foreach (var cell in ws.CellsUsed())
    {
        Console.WriteLine($"{cell.Address}: {cell.Value}");
    }
}
```

And output:
![image](https://user-images.githubusercontent.com/145854/87809113-1cdc4c00-c85b-11ea-945d-a07c5050a4ef.png)


Please modify the test code to reproduce the error.

**Comment by PenCoDK** [comment] 2020-07-17 21:26
I am sorry but I am lost here.

I have done as you suggested, made a little example to reproduce the error. See picture TEST CODE. Everything works fine. 150 records read as expected.

 

But when I use the exact same code in the original program the result is 0 records. See PRODUCTION CODE. The code goes straight from line 143 to 147 without looping.

 

If the problem is not in the ClosedXml files, then what is going on?? Any suggestions?

**Comment by PenCoDK** [comment] 2020-07-18 08:39
I am still trying to figure out what is going on.

 

I have replaced 0.95.3 with 0.94.2 – and everything works as expected. See PNG

 

And

 

Back to 0.95.3 – and nothing happens. See PNG

 

Both cases is from the production code.

 

Kind regards

Poul Erik Nikolajsen

**Comment by igitur** [comment] 2020-07-18 09:17
Attachments are disposed if you reply to this Github thread via email, so I can't see your png files. Rather reply directly on the Github website. https://github.com/ClosedXML/ClosedXML/issues/1477

Anyway, I cannot help without a code sample that reproduces the problem.

**Comment by alfeg** [comment] 2020-07-20 11:38
Can confirm this issue, but I cannot isolate it. It's failing randomly on parallel unit tests run. Sometimes there are can be several days without build failing

**Comment by igitur** [comment] 2020-07-20 12:17
@alfeg  DocumentFormat.OpenXml isn't thread-safe, and therefore neither is ClosedXML. If you run your tests in parallel, there can be any kind of unexpected consequence. But additionally, the stack trace you pasted implies that your problem is not related to this issue, which is about an exception raised in `XLHelper.cs`.

**Comment by alfeg** [comment] 2020-07-20 12:47
> @alfeg  DocumentFormat.OpenXml isn't thread-safe, and therefore neither is ClosedXML. If you run your tests in parallel, there can be any kind of unexpected consequence. But additionally, the stack trace you pasted implies that your problem is not related to this issue, which is about an exception raised in `XLHelper.cs`.

Oh, yeah. Sorry. Just same exception.

We run tests in parallel, but test and tested code is not accessing XmlWorkbook from multiple threads. There is simple code that read data from excel file, and put it to db.

**Comment by PenCoDK** [comment] 2020-07-20 16:03
I am still trying to figure out what is going on.
I have done as you suggested, made a little example to reproduce the error. Everything works fine. 150 records read as expected.

![Test code](https://user-images.githubusercontent.com/37813430/87958255-9a00fe80-cab1-11ea-906e-ce38b113a41e.png)

But when I use the exact same code in the original program the result is 0 records. The code goes straight from line 143 to 147 without looping.
![Production code](https://user-images.githubusercontent.com/37813430/87958334-b13fec00-cab1-11ea-8aea-ef510a041587.png)

I have replaced 0.95.3 with 0.94.2 – and everything works as expected.
![P-Code 0-94-2](https://user-images.githubusercontent.com/37813430/87958726-2b707080-cab2-11ea-8a85-27d4574d0a4d.png)

And back to 0.95.3 – and nothing happens.
![P-Code 0-95-3](https://user-images.githubusercontent.com/37813430/87958792-4347f480-cab2-11ea-8d73-8206838dd6f3.png)

Both cases is from the production code.

I have done a bit experimenting and it looks like the problem started with the change from 0.94.2 to 0.95.0
If the problem is not in the ClosedXml files, then what is going on?? Any suggestions?

**Comment by igitur** [comment] 2020-07-20 16:13
I can just think that your input files differ in the 2 cases. Insert a `XL.SaveAs("output.xlsx")` (for both environments) and attach the resulting files here.

**Comment by igitur** [comment] 2020-07-20 16:14
PS: C# > VB.NET ;-)

**Comment by PenCoDK** [comment] 2020-07-20 20:14
Two from test and two from production. Same file imported and two different version of ClosedXML.
I tried to open the P_0953 but Excel complained about a error.
[output_T_0942.xlsx](https://github.com/ClosedXML/ClosedXML/files/4949845/output_T_0942.xlsx)
[output_T_0953.xlsx](https://github.com/ClosedXML/ClosedXML/files/4949846/output_T_0953.xlsx)
[output_P_0942.xlsx](https://github.com/ClosedXML/ClosedXML/files/4949847/output_P_0942.xlsx)
[output_P_0953.xlsx](https://github.com/ClosedXML/ClosedXML/files/4949848/output_P_0953.xlsx)

**Comment by PenCoDK** [comment] 2020-07-20 20:15
1: VB.NET
3: C#

**Comment by PenCoDK** [comment] 2020-07-21 08:02
When I first discovered that there was a problem, I investigated the IXLWorksheet-object.
And found the following error message.
This is from 0.95.3
![0953](https://user-images.githubusercontent.com/37813430/88028619-2e627400-cb39-11ea-844d-cfaf19aa8bc5.png)

The same information can be found in 0.94.2 but here the data get read anyway.

**Comment by igitur** [comment] 2020-07-21 11:04
`XLWorksheet.InvalidAddress` is an internal property and it is expected that an exception is thrown for  `.ColumnLetter`. Do you actually experience this exception or did you must see it in the watch window?

**Comment by PenCoDK** [comment] 2020-07-21 14:57
Just found it in the watch window

**Comment by igitur** [comment] 2020-07-21 15:27
Ok, then it's a completely false clue. Ignore it.

What input file did you use to produce `output_P_0953.xlsx`? The one you attached in the original post?

**Comment by PenCoDK** [comment] 2020-07-21 15:57
yes, the same input file in all the tests

**Comment by jahav** [comment] 2024-09-24 22:35
I took a look at the [output_P_0953.xlsx](https://github.com/ClosedXML/ClosedXML/files/4949848/output_P_0953.xlsx) and [output_T_0953.xlsx](https://github.com/ClosedXML/ClosedXML/files/4949846/output_T_0953.xlsx). The _output_P_0953.xlsx_ has empty xl\sharedStrings.xml while output_T_0953.xlsx  contains the shared strings (the sheet still references references the strings, that is why Excel indicated an error). That is likely the reason why the program found 0 cells in the loop: no strings = no cells.

Not sure how shared strings table got lost, but shared strings table and cell values storage has been completely revamped since 0.95.3.  

I am closing this. There is no clear repro, the issue is ancient and whatever code was causing problems has been completely changed.

**Closed by jahav** 2024-09-24 22:35 UTC
