### ISSUE TITLE
CLosedXml 0.92 won't load OpenXml 2.7.2

### ISSUE THREAD

**Issue by JaedenRuiner** [ClosedXML/ClosedXML#1043] opened 2018-10-24 23:28 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**0.92.1, 0.93.1**
**What is the current behavior?**

DocumentFormat.OpenXml 2.8.1 references 50 different nuget packages, most of which are .Net base assemblies.  This is a pain for distribution.  So, I want to stick with DocumentFormat.OpenXml 2.7.2 which only references 5 assemblies.  HOwever, when i reference ClosedXml 0.92.1 with DocumentFormat 2.7.2, the program tries and fails to load DocumentFormat.OpenXml 2.8.1.
The depencies say 2.7.2 and above, but the application will not load with 2.7.2 installed.

**What is the expected behavior or new feature?**

I expect it to load DocumentFormat.OpenXml 2.7.2 and work.

**Did this work in previous versions of our tool?  Which versions?**
Yes, sort of.  It was only a problem when we updated our systems to start using .Net 4.6.1.  

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

This isn't a code sample issue, this is a Project Reference issues.  Project add Nuget package DocumentFormat.OpenXml 2.7.2, and then add ClosedXml 0.92.1 or 0.93.1 both via NuGet, and then try to load a XLWorkbook.  The project will compile, but when run it will crash/complain about missing file DocumentFormat.OpenXml 2.8.1.

Thanks
Jaeden "Sifo Dyas" al'Raec Ruiner

**Comment by igitur** [comment] 2018-10-25 12:35
I cannot reproduce this. I could successfully generate a workbook.

`packages.config`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="ClosedXML" version="0.93.1" targetFramework="net461" />
  <package id="DocumentFormat.OpenXml" version="2.7.2" targetFramework="net461" />
  <package id="ExcelNumberFormat" version="1.0.3" targetFramework="net461" />
  <package id="FastMember.Signed" version="1.3.0" targetFramework="net461" />
  <package id="System.IO.FileSystem.Primitives" version="4.0.1" targetFramework="net461" />
  <package id="System.IO.Packaging" version="4.0.0" targetFramework="net461" />
</packages>
```
which was produced by 2 commands:
```
install-package documentformat.openxml -version 2.7.2
Install-Package closedxml -version 0.93.1
```

`Program.cs`:
```c#
namespace ConsoleApp1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            using (var wb = new ClosedXML.Excel.XLWorkbook())
            {
                var ws = wb.AddWorksheet("sheet1");
                ws.Cell("A1").Value = 100;

                wb.SaveAs(@"c:\temp\test.xlsx");
            }
        }
    }
}
```

By the way, I very deliberately asked for reproducibility code and the above is the level of detail that I expect.

**Comment by igitur** [comment] 2018-10-25 12:37
If you can reproduce this with a *REDUCED* test case (like mine code above), please upload it to a new github repo. Don't include unnecessary code that is not relevant to the issue.

Also, on what version of Visual Studio are you? Try the latest, if you're not already on it.

**Comment by JaedenRuiner** [comment] 2018-10-29 19:20
I"m on VS2017.  I have done this locally, and whenever I add the two, i get a "Failed to load ... 2.8.1" version of OpenXml.  Frustrating, because this now seems to be an issue within VS2017Enterprise with a manifest somewhere that is expecting 2.8.1 but I have no idea which assembly is doing that.  All reference assemblies were referencing 2.7.2 only, so in all the csproj files, the packages.xml, everywhere I'm referencing 2.7.2, but getting this darned load error.  I don't have time to deal with it, so i've updated everything to use 2.8.1 even though that explodes my references quite a bit.

**Comment by igitur** [comment] 2018-10-29 19:40
Try this extension. It should point you to any references that conflict. https://marketplace.visualstudio.com/items?itemName=MykolaTarasyuk.ReferenceConflictsAnalyser

Closing this as I can't reproduce.

**Closed by igitur** 2018-10-29 19:40 UTC

**Comment by MarkStega** [comment] 2019-09-11 18:14
In the csproj for the little sample app set AutoGenerateBindingRedirects to false. Use NuGet to update to the latest ClosedXML, OXML, FastMember, and ExcelNumberFormat. Delete the bin directory. The little sample app will now fail just as described. Resetting the AutoGenerateBR to true will solve the issue. It really appears that ClosedXML has a dependency that OXML version = 2.7.2 (not >=)

**Comment by igitur** [comment] 2020-05-15 20:40
This might help others with this problem. Note that this is _not_ a ClosedXML problem. https://github.com/ClosedXML/ClosedXML/issues/1433#issuecomment-629473662
