### ISSUE TITLE
Error Evaluating Formula in Excel Styled Table

### ISSUE THREAD

**Issue by thutch10** [ClosedXML/ClosedXML#827] opened 2018-05-01 14:45 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.92.1

**What is the current behavior?**

When getting the Value of a cell, the error "Expected end of expression" is thrown when trying to evaluate the formula (=+[@[Value 1]]/[@[Value 2]]) in an Excel table.

**What is the expected behavior or new feature?**

Calling Value on a cell should return the result of evaluating the formula in the cell.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
        XLWorkbook wb = new XLWorkbook(filepath);
        IXLWorksheet ws = wb.Worksheet(1);
        var value = ws.Cell(2, 1).Value;
}
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Formula Error Closed XML.xlsx](https://github.com/ClosedXML/ClosedXML/files/1964094/Formula.Error.Closed.XML.xlsx)

**Comment by igitur** [comment] 2018-05-01 15:06
Duplicate of #271

**Closed by igitur** 2018-05-01 15:06 UTC

**Comment by thutch10** [comment] 2018-05-01 17:29
@igitur Sorry about the extra issue, I missed seeing the duplicate.  Thanks!
