### ISSUE TITLE
Can't create an XLWorkbook with image(s) from a stream or byte[] coming from a web api controller (Blazor WASM)

### ISSUE THREAD

**Issue by aldvsmaximvs** [ClosedXML/ClosedXML#1782] opened 2022-04-13 05:38 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

If the excel file has no image, in the console app or blazor wasm app it works as expected.

If the excel file has images, in the console app it works as expected but in the blazor wasm it produces the error
The type initializer for 'ClosedXML.Excel.Drawings.XLPicture' threw an exception

**What is the expected behavior or new feature?**

I will be able to create a XLWorkbook with images from stream or base64string coming from a web api controller.

**Is this a regression from the previous version?**

No. Occurs in 0.95.3

## Reproducibility
I've attached a console app and blazor wasm app to reproduce.

from the controller (server) side

        [HttpGet("GetWorkbookStream/{templateName}")]
        public async Task<MemoryStream> GetWorkbookStream(string templateName)
        {
            try
            {
                var t = Task.Run(() =>
                {
                    var stream = new System.IO.MemoryStream();
                    using (var wbook = new XLWorkbook($"Templates/{templateName}"))
                    {
                        wbook.SaveAs(stream);
                        stream.Position = 0;

                        return stream;
                    }
                });

                return await t;
            }
            catch (System.Exception ex)
            {
                return null;
            }
        }

from the blazor client side

    private async Task OnClickViaStream()
    {
        var templateName = "Book.xlsx";
        try
        {

            var ms = await Http.GetStreamAsync($"api/ExcelFile/GetWorkbookStream/{templateName}");

            using (var wbook = new XLWorkbook(ms))
            {
                //add a new sheet, add data
                IXLWorksheet worksheet =
                wbook.Worksheets.Add($"Sheet_123");
                worksheet.Cell(1, 1).Value = "NAME";
                worksheet.Cell(1, 2).Value = "QTY";
                worksheet.Cell(1, 3).Value = "PRICE";
                for (int i = 1; i <= 2; i++)
                {
                    worksheet.Cell(1, i).Style.Font.Bold = true;
                }

                int index = 1;

                worksheet.Cell(index + 1, 1).Value = "APPLE";
                worksheet.Cell(index + 1, 2).Value = 1;
                worksheet.Cell(index + 1, 3).Value = 1;

                //download excel file 
                using (var stream = new MemoryStream())
                {
                    wbook.SaveAs(stream);
                    var content = stream.ToArray();

                    var fileName = $"{templateName}";
                    fileName = fileName.Replace(".xlsx", "-output.xlsx");

                    await JSRuntime.InvokeAsync<object>("saveAsFile", fileName, Convert.ToBase64String(content));
                }
            }
        } catch(SystemException ex)
        {
            Console.WriteLine(ex.Message);
        }
    }

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

[CloseXMLConsole.zip](https://github.com/ClosedXML/ClosedXML/files/8478519/CloseXMLConsole.zip)
[ClosedXMLBlazorWASM.zip](https://github.com/ClosedXML/ClosedXML/files/8478520/ClosedXMLBlazorWASM.zip)

**Comment by jahav** [comment] 2022-05-26 17:59
The issue is that ClosedXml is using System.Drawing.Common for working with images. [Since NET6.0](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only), the System.Drawing.Common is throwing a run-time exception on non-Windows operating systems. There is a config value as a workaround, but it didn't work for me.

To solve this, System.Drawing.Common will probably have to go (used for images + fonts), either replaces by some library or implement required functionality. ClosedXML mostly needs format and size information, not the image data themselves. It would also mean a breaking change of API.

> System.PlatformNotSupportedException: System.Drawing is not supported on this platform.
> at System.Drawing.Imaging.ImageFormat.get_Bmp()
> at System.Reflection.RuntimePropertyInfo.StaticGetterAdapterFrame[ImageFormat](StaticGetter`1 getter, Object obj)
> at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
> at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
> at ClosedXML.Excel.Drawings.XLPicture.<>c__DisplayClass6_0.<.cctor>b__2(XLPictureFormat pf)
> at System.Linq.Enumerable.ToDictionary[XLPictureFormat,XLPictureFormat,ImageFormat](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
> at System.Linq.Enumerable.ToDictionary[XLPictureFormat,XLPictureFormat,ImageFormat](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
> at ClosedXML.Excel.Drawings.XLPicture..cctor()

**Comment by jahav** [comment] 2022-10-27 16:55
Blazor should now work at least for images (that was the original issue here) through #1805 . For fonts, there was a problem with fonts, see #1879 for details.

Closing as duplicate of #1805

**Closed by jahav** 2022-10-27 16:55 UTC
