### ISSUE TITLE
Requesting support for working with Excel files with external data connections.

### ISSUE THREAD

**Issue by koorellasuresh** [ClosedXML/ClosedXML#802] opened 2018-04-20 22:58 UTC
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [X ] Feature

**Version of ClosedXML**

>0.92.*

**What is the current behavior?**

Support for working with Excel files with external data connections. 

**What is the expected behavior or new feature?**

New feature.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

Support for working with Excel files with external data connections. 

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment] 2018-04-21 06:42
Duplicate of #420

**Closed by igitur** 2018-04-21 06:42 UTC
