### ISSUE TITLE
error saving workbook on unity3d android

### ISSUE THREAD

**Issue by elfasito** [ClosedXML/ClosedXML#1880] opened 2022-10-22 00:08 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.97

**What is the current behavior?**

get unexpected error at saving the workbook.

**What is the expected behavior or new feature?**

save the workbook.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

**Code to reproduce problem:**
```c#

public void TaskWriteXLSXandroid()
    {
        using (var workbook = new XLWorkbook())
        {
            var worksheet = workbook.Worksheets.Add("Sample Sheet");
            //just some cell writing for testing
            worksheet.Cell("B3").Value = "added some text from closedxml";
            workbook.SaveAs(Application.persistentDataPath + "/xlsx/direct.xlsx");
            Debug.Log("xlsx file updated");
        }
    }
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

Hello, Im getting an  error at the line workbook.SaveAs().
only happens on the android build (works fine on windows).
im using unity3d with netstandard2.0

this is the debug from visual studio:

```
System.TypeInitializationException: The type initializer for 'DocumentFormat.OpenXml.Framework.ClassActivator.Utility<DocumentFormat.OpenXml.Packaging.ExtendedFilePropertiesPart>' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
  at System.Linq.Expressions.Interpreter.LightLambda.MakeRunDelegateCtor (System.Type delegateType) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.Interpreter.LightLambda.GetRunDelegateCtor (System.Type delegateType) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate (System.Type delegateType) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.Interpreter.LightDelegateCreator.CreateDelegate (System.Runtime.CompilerServices.IStrongBox[] closure) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.Interpreter.LightDelegateCreator.CreateDelegate () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.Expression`1[TDelegate].Compile (System.Boolean preferInterpretation) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.Expression`1[TDelegate].Compile () [0x00000] in <00000000000000000000000000000000>:0 
  at DocumentFormat.OpenXml.Framework.ClassActivator`1[T].CreateActivator (System.Type type) [0x00000] in <00000000000000000000000000000000>:0 
  at DocumentFormat.OpenXml.Framework.ClassActivator+Utility`1[T]..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at DocumentFormat.OpenXml.Framework.ClassActivator.CreateInstance[T] () [0x00000] in <00000000000000000000000000000000>:0 
  at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.AddNewPartInternal[T] (System.String contentType, System.String id) [0x00000] in <00000000000000000000000000000000>:0 
  at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.AddNewPart[T] (System.String id) [0x00000] in <00000000000000000000000000000000>:0 
  at ClosedXML.Excel.XLWorkbook.CreateParts (DocumentFormat.OpenXml.Packaging.SpreadsheetDocument document, ClosedXML.Excel.SaveOptions options) [0x00000] in <00000000000000000000000000000000>:0 
  at ClosedXML.Excel.XLWorkbook.CreatePackage (System.String filePath, DocumentFormat.OpenXml.SpreadsheetDocumentType spreadsheetDocumentType, ClosedXML.Excel.SaveOptions options) [0x00000] in <00000000000000000000000000000000>:0 
  at ClosedXML.Excel.XLWorkbook.SaveAs (System.String file, ClosedXML.Excel.SaveOptions options) [0x00000] in <00000000000000000000000000000000>:0 
  at ClosedXML.Excel.XLWorkbook.SaveAs (System.String file, System.Boolean validate, System.Boolean evaluateFormulae) [0x00000] in <00000000000000000000000000000000>:0 
  at ClosedXML.Excel.XLWorkbook.SaveAs (System.String file) [0x00000] in <00000000000000000000000000000000>:0 
  at WriteClosedXMLv3.TaskWriteXLSXandroid () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.InvokableCall.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Events.UnityEvent.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.Button.Press () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchPress (UnityEngine.EventSystems.PointerEventData pointerEvent, System.Boolean pressed, System.Boolean released) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchEvents () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.StandaloneInputModule.Process () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.EventSystems.EventSystem.Update () [0x00000] in <00000000000000000000000000000000>:0 
   --- End of inner exception stack trace ---
```

**Comment by jahav** [comment] 2022-10-24 23:44
Although I have never developed for android/Unity, it seems that there is a problem with the compilation of an expression to an IL on Unity, that is outside of the ClosedXML scope.

The exception throws [here in DocumentFormat.OpenXml](https://github.com/OfficeDev/Open-XML-SDK/blob/v2.16.0/src/DocumentFormat.OpenXml/Framework/ClassActivator%7BT%7D.cs#L17)). The ctor of ExtendedFilePropertiesPart is internal protected and is overall uninteresting. It just takes a ctor, creates an expression and compiles.

Google presented many pages with similar error messages ("MakeRunDelegateCtor NullReferenceException") related to unity. Maybe try different scripting backend(https://docs.unity3d.com/Manual/overview-of-dot-net-in-unity.html)?

I am pretty sure that the problem is not ClosedXML, but somewhere in Unity, please ask them.

In DocumentFormat.OpenXml 2.18.0 the activation was hidden behind a feature (https://github.com/OfficeDev/Open-XML-SDK/pull/1167), so it might be possible to switch out? Maybe not, I have no idea how features work there.

> You should only use third-party .NET libraries that have been extensively tested on a wide range of Unity configurations and platforms.
> The performance characteristics of JIT and AOT code paths in third-party libraries might be significantly different. 
> Compatibility: Third-party libraries might not be compatible with some Unity platforms and scripting backends.
>          -- [Overview of .NET in Unity](https://docs.unity3d.com/Manual/overview-of-dot-net-in-unity.html)

Closing the issue because it is not caused by ClosedXML and it is not possible to solve the underlaying issue here.

**Closed as not planned by jahav** 2022-10-24 23:44 UTC
