### ISSUE TITLE
All cells are given a style when saving a workbook

### ISSUE THREAD

**Issue by SmokinCode** [ClosedXML/ClosedXML#296] opened 2017-05-04 12:49 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**
All cells are given a style when when saving a workbook. This causes a bug in the IsEmpty method, and a performance penalty.

When saving a workbook every cell is checked if it is empty. The method 

``` public Boolean IsEmpty(Boolean includeFormats)``` 

in class XLCell creates a XLStyle for every cell in the if-statement 

```if (!Style.Equals(Worksheet.Style) || IsMerged() || HasComment || HasDataValidation)```

because the "getter" for Style creates one 
```
private IXLStyle GetStyle()
{
    if (_style != null)
        return _style;
    return _style = new XLStyle(this, Worksheet.Workbook.GetStyleById(_styleCacheId));
}
 ```

the following if-statement will never be true 

```
if (_style == null)
{
    XLRow row;
    if (Worksheet.Internals.RowsCollection.TryGetValue(Address.RowNumber, out row) && !row.Style.Equals(Worksheet.Style))
        return false;

    XLColumn column;
        if (Worksheet.Internals.ColumnsCollection.TryGetValue(Address.ColumnNumber, out column) && !column.Style.Equals(Worksheet.Style))
        return false;
}
```

***Code listing of method***
```
public Boolean IsEmpty(Boolean includeFormats)
{
    if (InnerText.Length > 0)
        return false;

    if (includeFormats)
    {
        if (!Style.Equals(Worksheet.Style) || IsMerged() || HasComment || HasDataValidation)
            return false;

        if (_style == null)
        {
            XLRow row;
            if (Worksheet.Internals.RowsCollection.TryGetValue(Address.RowNumber, out row) && !row.Style.Equals(Worksheet.Style))
                return false;

            XLColumn column;
            if (Worksheet.Internals.ColumnsCollection.TryGetValue(Address.ColumnNumber, out column) && !column.Style.Equals(Worksheet.Style))
                return false;
        }

        if (Worksheet.ConditionalFormats.Any(cf => cf.Range.Contains(this)))
            return false;
    }
    return true;
}
```

***Performance considerations***
Here is a performance breakdown of saving one of my workbooks. The IsEmpty method is looking expensive:

![closedxmlperformance](https://cloud.githubusercontent.com/assets/28390344/25703293/4a37765a-30d5-11e7-8e85-3271e2b1193a.PNG)

Creating styles and checking for data validations are expensive operations.

**Comment by igitur** [comment] 2017-05-04 13:47
The performance issue is a known issue. Let's park that first.

Please post code to reproduce the bug that you're speaking of. Small, minimal test code to reproduce the bug, please. Even better if you can submit a unit test.

**Comment by SmokinCode** [comment] 2017-05-04 15:04
Please read comment 1. and 2. in the code below. The code is from XLCell.cs.

```csharp
public Boolean IsEmpty(Boolean includeFormats)
{
    if (InnerText.Length > 0)
        return false;

    if (includeFormats)
    {  
        // 1. See line below. Accessing the Style property will set the backing propery _style != null 
        if (!Style.Equals(Worksheet.Style) || IsMerged() || HasComment || HasDataValidation)
            return false;

        if (_style == null) // 2. this is impossible
        {
            XLRow row;
            if (Worksheet.Internals.RowsCollection.TryGetValue(Address.RowNumber, out row) && !row.Style.Equals(Worksheet.Style))
                return false;

            XLColumn column;
            if (Worksheet.Internals.ColumnsCollection.TryGetValue(Address.ColumnNumber, out column) && !column.Style.Equals(Worksheet.Style))
                return false;
        }

        if (Worksheet.ConditionalFormats.Any(cf => cf.Range.Contains(this)))
            return false;
    }
    return true;
}
```

Based on comment nr. 1 we have two bad things happening:

A. This is not possible: `_style == null`, ref comment nr 2 i the code.

B. The method `XLCell.IsEmpty(Boolean includeFormats)` has the side effect of creating a **Style** object for the cell. During `Woorkbook.SaveAs()` _IsEmpty(true)_ is called for every cell. Why do all empty cells in a workbook have to have a style? Creating a **Style** object for every cell takes ages.

**Comment by igitur** [comment] 2017-05-04 15:31
Give me code that I can copy and paste and just run. I'm looking at these issues during my coffee breaks.

**Comment by Pankraty** [comment] 2018-05-19 21:49
Styles were redesigned completely and since no sample code has been provided there is no way to check if the original issue has gone now. I have no other option but close it.

**Closed by Pankraty** 2018-05-19 21:49 UTC
