### ISSUE TITLE
CloxedXML 0.96.0 will no longer run in AWS Lambda due to a breaking change from Microsoft

### ISSUE THREAD

**Issue by genifycom** [ClosedXML/ClosedXML#1870] opened 2022-10-11 01:02 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.96.0

**What is the current behavior?**

Because Microsoft marked System.Drawing.Common 6.0.0 as Windows only, ClosedXML will no longer run on Linux (or AWS Lambda).

**What is the expected behavior or new feature?**

ClosedXLM should run in both Windows and Linux

**Is this a regression from the previous version?**

No, this is due to a breaking change from Microsoft documented here:

https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
Since ClosedXML references System.Drawing.Common (according to Nuget Transitive references) when running the same project under AWS Lambda, the logs now say

`---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.`

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment] 2022-10-11 10:27
Hi, this is a duplicate of #1805. Before I close it as a duplicate, could you please try the packages from a PR that replaces System.Drawing.Common on AWS Lambda? 

They are here: https://ci.appveyor.com/project/ClosedXML/closedxml/builds/45030495/artifacts
Documentation is here, you will have to `LoadOptions.DefaultGraphicsEngine = DefaultGraphicEngine.Embedded.Value;`
https://github.com/ClosedXML/ClosedXML/wiki/Graphic-Engine

**Comment by genifycom** [comment] 2022-10-11 15:12
Thanks for the reference. I note in:
https://github.com/ClosedXML/ClosedXML/wiki/Graphic-Engine

"You can install the engine by adding a ClosedXML.SixLabors nuget package". 
This package does not show up in Visual Studio 2022 17.3.5 under Browse (with or without Include prerelease).

What am I missing?

**Comment by genifycom** [comment] 2022-10-11 15:20
Does this mean a different code path for AWS vs Windows?

**Comment by jahav** [comment] 2022-10-11 17:08
> Thanks for the reference. I note in: https://github.com/ClosedXML/ClosedXML/wiki/Graphic-Engine
> 
> "You can install the engine by adding a ClosedXML.SixLabors nuget package". This package does not show up in Visual Studio 2022 17.3.5 under Browse (with or without Include prerelease).
> 
> What am I missing?

Version 0.96.1 isn't published yet, even replacement is only on CI build from PR(bot yet merged yet), so it's not on nuget, it's only an artifact on appveyor for now. Documentation is for the upcoming version, so I have it done when I do release.

**Comment by jahav** [comment] 2022-10-11 22:55
Closing as a duplicate of #1805

**Closed as not planned by jahav** 2022-10-11 22:55 UTC
