### ISSUE TITLE
Faster way to load an xlsx-file into an XLWorkbook instance?

### ISSUE THREAD

**Issue by v-olin** [ClosedXML/ClosedXML#2109] opened 2023-06-21 07:07 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.100.3 / 0.101.0 / 0.102.0-rc

**What is the current behavior?**

I have a pretty large Excel-file (.xlsx) that I want to load into memory to read an write from.
I am currently opening a filestream on it with read/write access and passing it to the `XLWorkbook` constructor.
The file is ~5.1 MB and takes between 9-10 seconds to load into memory with a filestream (both in debug and release)
The library in itself works great, I'm just wondering if there is a faster way to do this?

| ClosedXML Version | 0.100.3 | 0.101.0 | 0.102.0-rc |
| --------------------- | ---------| -------- | ---------- |
| Debug Avg | 7328 ms | 7644 ms | 8245 ms |
| Release Avg | 7321 ms | 7703 ms | 7933 ms |

**What is the expected behavior or new feature?**

Faster load time (if possible).

**Is this a regression from the previous version?**

The load times are a bit slower in the newer versions but not measurably so.

## Reproducibility
Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    var file = @"C:\my\large\file.xlsx"; // roughly 5.1 MB in size
    XLWorkbook workbook;

    using (var bookStream = new FileStream(file, FileMode.Open, FileAccess.ReadWrite, FileShare.ReadWrite))
    {
        workbook= new XLWorkbook(bookStream);
    }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
Unfortunately I can't share a sample spreadsheet due to confidentiality, but thanks in advance.

**Comment by jahav** [comment] 2023-06-21 08:24
Sorry, there is no faster way to load a worksheet at the moment..

**Comment by jahav** [comment] 2023-06-21 08:31
Duplicate of #1996

**Closed as not planned by jahav** 2023-06-21 08:31 UTC
