### ISSUE TITLE
SUMIF doesn't consider only first column

### ISSUE THREAD

**Issue by Pekshev** [ClosedXML/ClosedXML#2041] opened 2023-03-30 13:52 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.100.3
(Installed via nuget.org using NuGet package manager)

**What is the current behavior?**

When reading a complex file with lots of formulas and links, it gives wrong formula calculation results

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

No special actions are needed: just open the attached file and take the value of cell (13, 9) from the first sheet as an example

Value in file:
![image](https://user-images.githubusercontent.com/12638819/228858137-b5aeb2c2-8a1b-48c3-9747-2dee9c7f69ea.png)

The value produced by the code:
![image](https://user-images.githubusercontent.com/12638819/228858303-14bb57dc-cb21-4a82-987d-a3266ef8a936.png)

**Code to reproduce problem:**
```c#
using (var fs = new FileStream(@"E:\Temp\Расчёт гидравлики СНТ Вишня.xlsx", FileMode.Open, FileAccess.Read))
{
    var workbook = new XLWorkbook(fs);
    var worksheet = workbook.Worksheet(1);
    var xlCell = worksheet.Cell(13, 9);
    xlCell.InvalidateFormula();
    MessageBox.Show(xlCell.Value.ToString());
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Расчёт гидравлики СНТ Вишня.xlsx](https://github.com/ClosedXML/ClosedXML/files/11112243/default.xlsx)

**Comment by jahav** [comment] 2023-03-30 14:49
Please provide a smaller sample, minimal would be best.

The workbook has 35 worksheets with a large amount of data and formulas are across many worksheets, in an alphabet I am not familiar with (i.e. checking where references go across worksheets is an excercise - does this looks similar). Also, my Excel will say that it needs to repair the file on load, likely because I use English version.

**Comment by Pekshev** [comment] 2023-03-30 14:56
That's the problem - I can't reproduce this problem myself. A user sent me this file and it is exactly the problem.
For the sake of experiment I tried to read it through EPPlus and it managed, giving the correct result.
Then I tried to recalculate all formulas on all sheets and got the error about cyclic dependency. I'll take another look at this file as much as I can

**Comment by jahav** [comment] 2023-04-08 20:42
I have trimmed it down a lot, but it is still massive.
The cell `I13` uses `INDEX` function and indexes from two `MATCH` functions. I have separated it to individual cells (`A1`, `B1` and `C1`). The indexes are correctly evaluated, but the `INDEX` function doesn't return the correct value.

Trimmed file (still massive): [default7.xlsx](https://github.com/ClosedXML/ClosedXML/files/11184211/default7.xlsx)

**Comment by jahav** [comment] 2023-04-12 12:09
@Pekshev Please track the call to a function/feature that doesn't work (i.e. go deeper and deeper into the call chain of the workbook and verify that ClosedXML gives the different result than Excel for the arguments/cell). Minimum verifiable example is a requirement for bugs.

I am closing the issue in the meantime. When you do that, reopen the issue.

**Comment by igitur** [comment] 2023-04-12 18:13
I managed to trace the cause. On a different sheet, there is a `SUMIF` function that is passed a matrix range, not array. Excel considers only the first column, but ClosedXML was treating it differently.

**Comment by igitur** [comment] 2023-04-12 18:17
Example of culprit: in the original attached workbook.
`'Расчёт гидравл.'!K120` has the formula: `=SUMIF($C65:I$119,"суммарный*",K$65:K119)`. Notice that the first parameter is a multi-dimensional range (matrix).

**Closed as completed** 2023-04-14 21:13 UTC
