### ISSUE TITLE
Excel workbook Last Modified By = D3l3t3M3 and cannot be changed or updated by Excel

### ISSUE THREAD

**Issue by dougclavell** [ClosedXML/ClosedXML#2073] opened 2023-04-25 19:03 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by dougclavell** [comment] 2023-04-25 19:11
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FlashWeb.Models.DB;
using FlashWeb.Models;
using ClosedXML.Excel;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;
using FlashWeb.Enumerations;
using FlashWeb.Reporting;



namespace FlashWeb.Controllers
{
    public class FlashReportController : Controller
    {
        private readonly ILogger _logger;
       //public FlashReportController(ILogger<FlashReportController> logger)
       // {
       //     _logger = logger;
       // }

        private readonly FlashBudgetContext _context;
        private GlobalCalDate globalCalDate = new GlobalCalDate();
        private DateLookBack dateLookBack= new DateLookBack();

        private const string FLASHFOLDER = XXXX
        //private const string FLASHFOLDER = XXXX
        //private const string FLASHFOLDER = XXXX
        //private const string FLASHFOLDER = XXXX
        private const string FLASHTEMPLATE = "FlashReportTemplateBudget.xlsx";
        private const string FLASHREPORTNAME = "FlashReport_";
        private const string FLASHREPORTEXT = ".xlsx";


        //public FlashReportController(FlashBudgetContext context)
        public FlashReportController(FlashBudgetContext context,ILogger<FlashBudgetContext> logger)
        {
            _logger = logger;
           // _context = new FlashBudgetContext();
            _context = context;
        }

        [HttpGet]
        public IActionResult Index(string? CalDate)
        {
            ReportFlashModel reportFlashModel = new ReportFlashModel();
            reportFlashModel.CalDate = DateOnly.FromDateTime(Convert.ToDateTime(CalDate));

            GlobalCalDate globalCalDate = new GlobalCalDate();
            globalCalDate.CalDate = CalDate;
            reportFlashModel.CalDateFormatted = globalCalDate.CalDateFormatted;
            reportFlashModel.Audience = "Audit";
            return View(reportFlashModel);
        }


        [HttpPost]
       // public IActionResult Index(ReportFlashModel model)
        public IActionResult BuildAndSendReport([Bind("CalDateUrl, CalDateFormatted, CalDate, Audience", "SendAudience")] ReportFlashModel reportFlashModel)
        //public IActionResult BuildAndSendReport(ReportFlashModel reportFlashModel)
        {
            //     then call routines to populate each section of the report - passing in the worksheet
            //     saves the worksheet with date in the name
            //     returns view notifying user that FLASH report is complete

            try
            {
                _logger.LogInformation("Just testing the logger");

                globalCalDate = new GlobalCalDate();
                //globalCalDate.CalDate = _calDate;
                globalCalDate.CalDate = reportFlashModel.CalDate.ToString();
                dateLookBack.CalDate = globalCalDate.CalDateOnly;
                ViewBag.CalDate = globalCalDate.CalDate;


                var dtReportDate = Convert.ToDateTime(reportFlashModel.CalDate.ToString());

                Array Audiences = Enum.GetValues(typeof(Enums.AudienceEnum));

                foreach (Enums.AudienceEnum audience in Audiences)
                {


                    // New  up the FLASH Excel template
                    //XLWorkbook restBook = new XLWorkbook("XXX");
                    XLWorkbook restBook = new XLWorkbook(FLASHFOLDER + "FlashReportTemplateBudget.xlsx");
                    //restBook.Worksheets.Add(1);
                    IXLWorksheet restSheet = restBook.Worksheet("WithBudget");

                    ExcelReport excelReport = new ExcelReport(_context, _logger);


                                     

                    // Call eac report section populaton routine.
                    // Everyone gets stats and patron counts
                    excelReport.PopulateHeaderSection(ref restSheet, globalCalDate.CalDateOnly);
                    excelReport.PopulatePatronCountBudget(ref restSheet, globalCalDate.CalDateOnly);


                    switch (audience)
                    {
                        case Enums.AudienceEnum.FlashBingo:
                            excelReport.PopulateBingoReport(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateBingoBudgetReport(ref restSheet, globalCalDate.CalDateOnly);

                            restBook.SaveAs(FLASHFOLDER + FLASHREPORTNAME + Enums.AudienceEnum.FlashBingo.ToString() + dtReportDate.ToString("MMddyyyy") + FLASHREPORTEXT);
                            break;

                        case Enums.AudienceEnum.FlashExec:
                            excelReport.PopulateSlots(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateSlotsBudgetReport(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateTableGames(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateTableGamesBudget(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateBingoReport(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateBingoBudgetReport(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateHotelReport(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateHotelBudgetReport(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateFnBReport(ref restSheet, globalCalDate.CalDateOnly);    // This also populates the Banquets FnB section (Below FnB)
                            excelReport.PopulateBanguets(ref restSheet, globalCalDate.CalDateOnly);     // Also knownas NON FNB BANQUETS
                            excelReport.PopulateBanquetsBudget(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateFnBBudget(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateGiftGallery(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateGiftGalleryBudget(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateSPA(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateSpaBudget(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateFNBPatronCounts(ref restSheet, globalCalDate.CalDateOnly);

                            restBook.SaveAs(FLASHFOLDER + FLASHREPORTNAME + Enums.AudienceEnum.FlashExec.ToString() + dtReportDate.ToString("MMddyyyy") + FLASHREPORTEXT);

                            break;

                        case Enums.AudienceEnum.FlashFnB:
                            excelReport.PopulateFnBReport(ref restSheet, globalCalDate.CalDateOnly);    // This also populates the Banquets FnB section (Below FnB)
                            excelReport.PopulateBanguets(ref restSheet, globalCalDate.CalDateOnly);     // Also knownas NON FNB BANQUETS
                            excelReport.PopulateBanquetsBudget(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateFnBBudget(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateFNBPatronCounts(ref restSheet, globalCalDate.CalDateOnly);

                            restBook.SaveAs(FLASHFOLDER + FLASHREPORTNAME + Enums.AudienceEnum.FlashFnB.ToString() + dtReportDate.ToString("MMddyyyy") + FLASHREPORTEXT);

                            break;

                        case Enums.AudienceEnum.FlashHositality:
                            excelReport.PopulateHotelReport(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateHotelBudgetReport(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateBanguets(ref restSheet, globalCalDate.CalDateOnly);     // Also knownas NON FNB BANQUETS
                            excelReport.PopulateGiftGallery(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateGiftGalleryBudget(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateSPA(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateSpaBudget(ref restSheet, globalCalDate.CalDateOnly);

                            restBook.SaveAs(FLASHFOLDER + FLASHREPORTNAME + Enums.AudienceEnum.FlashHositality.ToString() + dtReportDate.ToString("MMddyyyy") + FLASHREPORTEXT);

                            break;

                        case Enums.AudienceEnum.FlashTableGames:
                            excelReport.PopulateTableGames(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateTableGamesBudget(ref restSheet, globalCalDate.CalDateOnly);

                            restBook.SaveAs(FLASHFOLDER + FLASHREPORTNAME + Enums.AudienceEnum.FlashTableGames.ToString() + dtReportDate.ToString("MMddyyyy") + FLASHREPORTEXT);

                            break;

                        case Enums.AudienceEnum.FlashSlots:
                            excelReport.PopulateSlots(ref restSheet, globalCalDate.CalDateOnly);
                            excelReport.PopulateSlotsBudgetReport(ref restSheet, globalCalDate.CalDateOnly);

                            restBook.SaveAs(FLASHFOLDER + FLASHREPORTNAME + Enums.AudienceEnum.FlashSlots.ToString() + dtReportDate.ToString("MMddyyyy") + FLASHREPORTEXT);

                            break;


                        default:
                            //Rut Row
                            break;

                    }
                    //excelReport.PopulateSlots(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateSlotsBudgetReport(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateTableGames(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateTableGamesBudget(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateBingoReport(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateBingoBudgetReport(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateHotelReport(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateHotelBudgetReport(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateFnBReport(ref restSheet, globalCalDate.CalDateOnly);    // This also populates the Banquets FnB section (Below FnB)
                    //excelReport.PopulateBanguets(ref restSheet, globalCalDate.CalDateOnly);     // Also knownas NON FNB BANQUETS
                    //excelReport.PopulateBanquetsBudget(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateFnBBudget(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateGiftGallery(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateGiftGalleryBudget(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateSPA(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateSpaBudget(ref restSheet, globalCalDate.CalDateOnly);
                    //excelReport.PopulateFNBPatronCounts(ref restSheet, globalCalDate.CalDateOnly);
                    




                    // Save Excel to file
                    //using (MemoryStream stream = new MemoryStream())
                    //{

                    //    restBook.SaveAs(stream);
                    //    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "FlashWeb.xlsx");
                    //}
                }

                //return Ok(header);
            }
            catch (Exception ex)
            {
                _logger.Log(LogLevel.Error, ex.Message + " in FlashReportController.Index");
                Problem(ex.Message + " FlashReportController Index");
                ViewBag.Message = ex.Message;
            }

            //return View();
            return RedirectToAction("Index", "SendFlash",  reportFlashModel );
        }
    }
}

**Comment by dougclavell** [comment] 2023-04-25 19:12
Spreadsheet contains financial data so not attached.

**Comment by dougclavell** [comment] 2023-04-25 19:27
![ModifiedBy_B](https://user-images.githubusercontent.com/131811476/234382098-00601b92-ced4-496d-97c6-a0d5ecffb3ee.png)

**Comment by dougclavell** [comment] 2023-04-25 19:28
The above screenshot is what we see after a user's modifies the worksheet.

**Comment by jahav** [comment] 2023-04-26 14:53
I am closing this, because it is missing basically everything from template, current behaviour, expected behaviour, minimum reproducible sample I can run.

**Closed as not planned by jahav** 2023-04-26 14:53 UTC

**Comment by dougclavell** [comment] 2023-04-26 15:09
OK.
No worries.
I apologize for taking up your time needlessly.
The whole issue is errant anyway due to miscommunication with user community.
I had planned to communicate that to you shortly.

Have a lovely day, Jahav!  😊


Doug Clavell | IT Database Developer
Umpqua Indian Development Corporation
146 Chief Miwaleta Lane | Canyoneville, OR | 97417
O: TO BE ANNOUNCED | ***@***.******@***.***>
[Logo  Description automatically generated]

From: Jahav ***@***.***>
Sent: Wednesday, April 26, 2023 7:54 AM
To: ClosedXML/ClosedXML ***@***.***>
Cc: Doug Clavell - UIDC - IT Database Admin/Developer ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL EMAIL]Re: [ClosedXML/ClosedXML] Excel workbook Last Modified By = D3l3t3M3 and cannot be changed or updated by Excel (Issue #2073)


I am closing this, because it is missing basically everything from template, current behaviour, expected behaviour, minimum reproducible sample I can run.
