### ISSUE TITLE
Worksheet with shape keeps original sheet xml

### ISSUE THREAD

**Issue by bwainscott-prolink** [ClosedXML/ClosedXML#2080] opened 2023-05-01 22:36 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.101.0

**What is the current behavior?**

When newing up the XLWorkbook with a stream, then immediately writing the file back to disk, the file has been changed unexpectedly.

**What is the expected behavior or new feature?**

The file is not modified.

**Is this a regression from the previous version?**

Yes, when the same operation is performed on 0.97.0, the file is not modified, as expected.  Then, it was tested with 0.100.0 all the way up to latest,  0.101.0.

## Reproducibility

**Code to reproduce problem:**
```c#

public class LoadingTests
{
...
    [Test]
    public void CanLoadFileFromStreamAndSaveBackWithoutCorruption()
    {
        Stream str = TestHelper.GetStreamFromResource(TestHelper.GetResourcePath(@"TryToLoad\BeforeUsingClosedXML.xlsx"));
    
        using (var file = new XLWorkbook(str))
        {
            file.SaveAs(@"C:\temp\AfterUsingClosedXML.xlsx");
        }
    }
```
}

Wrote the above unit test in the ClosedXml.Test project to repro the issue.
Excel --> Loading --> LoadingTests.cs
Copy in test and add attached file to the Resources --> TryToLoad folder and run.

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[BeforeUsingClosedXML.xlsx](https://github.com/ClosedXML/ClosedXML/files/11368470/BeforeUsingClosedXML.xlsx)

**Comment by renatogontijo** [comment] 2023-06-12 16:16
I'm having problems opening with 0.101 version of ClosedXML.

File to test:
[spreadsheet2-test.xlsx](https://github.com/ClosedXML/ClosedXML/files/11725550/spreadsheet2-test.xlsx)

**Code to Reproduce:**
```
    public void SpreadsheetWorkbook_OpenWorkbookFileStream_ShouldOpenSpreadsheetFile2()
    {
        // Arrange
        var fs = new FileStream(".\\Resources\\spreadsheet2-test.xlsx", FileMode.Open);

        // Act
        var workbook = new ClosedXML.Excel.XLWorkbook(fs);

        // Assert
        Assert.NotNull(fs);
        Assert.NotNull(workbook);
    }

```
Error occurs when loading a workbook using stream `new ClosedXML.Excel.XLWorkbook(fs);`.

**StackTrace Exception:**
An exception of type 'System.NullReferenceException' occurred in ClosedXML.dll but was not handled in user code: 'Object reference not set to an instance of an object.'
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
   at ClosedXML.Excel.XLWorkbook.Load(Stream stream)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream, LoadOptions loadOptions)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream)
   at AgroHUB.Sume.Infra.Data.File.Spreadsheet.Tests.SpreadsheetWorkbookTest.SpreadsheetWorkbook_OpenWorkbookFileStream_ShouldOpenSpreadsheetFile2() in c:\Users\Usuário\OneDrive\Documentos\Projects\AgroHUB.Sume\test\AgroHUB.Sume.Infra.Data.File.Spreadsheet.Tests\SpreadsheetWorkbookTest.cs:line 26
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by bwainscott-prolink** [comment] 2023-06-19 22:38
Happens in version 0.102 as well.

**Comment by jahav** [comment] 2023-06-20 10:52
@renatogontijo That is duplicate of #2096. Fixed in 0.102 (has rc nuget package out).

**Comment by jahav** [comment] 2023-06-20 11:00
@bwainscott-prolink There is no guarantee nor will ever be that the output file is same as input file. Output must conform to ISO29500 and can be opened by Excel (Excel has precedence when there is a difference between standard and implementation). That's all.

Whether it is something benign like adding non-implicit namespace to xml 
![image](https://github.com/ClosedXML/ClosedXML/assets/7634052/f44f0acf-15c8-4ef2-b729-75b8f0fde105)

or that ClosedXML uses some properties of OOXML standard. E.g. NPOI doesn't write *Normal* style to stylesheet, but both Excel and ClosedXML does (that is why there was the exception of mentioned @renatogontijo ). As another point of difference is that ClosedXML adds page setup (there are likely many others).
![image](https://github.com/ClosedXML/ClosedXML/assets/7634052/7fa1af5e-7d47-493e-9340-f8943673c316)

**Comment by bwainscott-prolink** [comment] 2023-06-20 16:35
@jahav - I understand there will be many changes to the file, but this flat out scrambles the sheet.

The cell values are completely different after new-ing up a workbook then immediately saving the workbook like in the above test.  As you can see in the screenshot below, starting with A4 and below.

![image](https://github.com/ClosedXML/ClosedXML/assets/84459993/ea3e02af-6c62-4f57-9e45-66675233b8c6)

**Comment by jahav** [comment] 2023-06-20 18:02
I see it wasn't clear from the issue template.
Anyway, it seems that it is caused by the shape at line 11.
![image](https://github.com/ClosedXML/ClosedXML/assets/7634052/839d0052-a46b-44fd-8139-7106b1bef5cc)

If I remove the shape, the text is correct. 

The saving code is writing correct xml, but for some reason it isn't actually written to the zip package and the sheet contains original data (with original ids of shared string), but shared string table is updated = ids don't match and different is displayed.

**Closed as completed** 2023-06-20 19:38 UTC

**Comment by bwainscott-prolink** [comment] 2023-06-20 22:01
@jahav Thank you!  I have run the test against the latest develop branch and it works!
