### ISSUE TITLE
Huge range in conditional formatting: OutOfMemoryException

### ISSUE THREAD

**Issue by shyronosov** [ClosedXML/ClosedXML#366] opened 2017-06-22 15:18 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**What is the current behavior?**

When a worksheet contains conditional formatting outside a table, then during inserting a row into the table the entire conditional format range is getting converted into new conditional formats, so that the ClosedXML creates objects for each cell in that range and OutOfMemoryException thrown. For example, if we have a rule that is applied to "=$A:$Z", the library tries to create objects for 26 million cells.

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
public void Main()
{
    // the Excel file has a worksheet with a conditional formatting, that is applied to "=$A:$Z".
    var workbook = new XLWorkbook(@"D:\test.xlsx");
    var table = workbook.Worksheets.First().Tables.First();
    var dataRange = table.DataRange;

    // on the next line we have OutOfMemoryException
    var insertedRows = dataRange.InsertRowsBelow(1);
}
```
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1095259/test.xlsx)

**Comment by igitur** [comment] 2017-06-22 15:38
Duplicate of #86

**Closed by igitur** 2017-06-22 15:38 UTC
Labels: duplicate
