### ISSUE TITLE
[Bug] The given key was not present in the dictionary

### ISSUE THREAD

**Issue by Baseline86** [ClosedXML/ClosedXML#327] opened 2017-05-31 11:18 UTC
When i start my application and create an Excel report everything goes fine. When i create that same Excel report a second/third/fourth time everything stills works as intendent.

However, when i first create a different Excel report and then try to create that first Excel Report i always get the following error: The given key was not present in the dictionary.

Any idea what i'm doing wrong?

_Stacktrace:_
```
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ClosedXML.Excel.XLWorkbook.GenerateWorkbookStylesPartContent(WorkbookStylesPart workbookStylesPart, SaveContext context) in C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 2749
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document) in C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 266
   at ClosedXML.Excel.XLWorkbook.CreatePackage(Stream stream, Boolean newStream, SpreadsheetDocumentType spreadsheetDocumentType, Boolean validate) in C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 130
   at ClosedXML.Excel.XLWorkbook.SaveAs(Stream stream, Boolean validate) in C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 547
   at ClosedXML.Excel.XLWorkbook.SaveAs(Stream stream) in C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 528
```

The code of the first excel (giving the error)

```c#
Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-US");
var workbook = new XLWorkbook();
var worksheet = workbook.Worksheets.Add("LSMW");

worksheet.Column(1).Width = 10.00;
worksheet.Column(2).Width = 10.00;
worksheet.Column(3).Width = 10.00;
worksheet.Column(4).Width = 10.00;
worksheet.Column(5).Width = 10.00;
worksheet.Column(6).Width = 10.00;
worksheet.Column(7).Width = 10.00;
worksheet.Column(8).Width = 10.00;
worksheet.Column(9).Width = 10.00;
worksheet.Column(10).Width = 10.00;
worksheet.Column(11).Width = 10.00;
worksheet.Column(12).Width = 10.00;

worksheet.Column(1).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;
worksheet.Column(2).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;
worksheet.Column(3).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;
worksheet.Column(4).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;
worksheet.Column(5).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;
worksheet.Column(6).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;
worksheet.Column(7).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;
worksheet.Column(8).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;
worksheet.Column(9).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;
worksheet.Column(10).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;
worksheet.Column(11).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;
worksheet.Column(12).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Right;

worksheet.Cell(1, 1).SetValue("KSCHL");
worksheet.Cell(1, 2).SetValue("VKORG");
worksheet.Cell(1, 3).SetValue("VTWEG");
worksheet.Cell(1, 4).SetValue("SPART");
worksheet.Cell(1, 5).SetValue("KUNNR");
worksheet.Cell(1, 6).SetValue("MATNR");
worksheet.Cell(1, 7).SetValue("KBETR");
worksheet.Cell(1, 8).SetValue("DATAB");
worksheet.Cell(1, 9).SetValue("DATBI");
worksheet.Cell(1, 10).SetValue("KONWA");
worksheet.Cell(1, 11).SetValue("KPEIN");
worksheet.Cell(1, 12).SetValue("KMEIN");

worksheet.Cell(1, 1).Style.Fill.BackgroundColor = XLColor.FromArgb(234, 234, 234);
worksheet.Cell(1, 2).Style.Fill.BackgroundColor = XLColor.FromArgb(234, 234, 234);
worksheet.Cell(1, 3).Style.Fill.BackgroundColor = XLColor.FromArgb(234, 234, 234);
worksheet.Cell(1, 4).Style.Fill.BackgroundColor = XLColor.FromArgb(234, 234, 234);
worksheet.Cell(1, 5).Style.Fill.BackgroundColor = XLColor.FromArgb(234, 234, 234);
worksheet.Cell(1, 6).Style.Fill.BackgroundColor = XLColor.FromArgb(234, 234, 234);
worksheet.Cell(1, 7).Style.Fill.BackgroundColor = XLColor.FromArgb(234, 234, 234);
worksheet.Cell(1, 8).Style.Fill.BackgroundColor = XLColor.FromArgb(234, 234, 234);
worksheet.Cell(1, 9).Style.Fill.BackgroundColor = XLColor.FromArgb(234, 234, 234);
worksheet.Cell(1, 10).Style.Fill.BackgroundColor = XLColor.FromArgb(234, 234, 234);
worksheet.Cell(1, 11).Style.Fill.BackgroundColor = XLColor.FromArgb(234, 234, 234);
worksheet.Cell(1, 12).Style.Fill.BackgroundColor = XLColor.FromArgb(234, 234, 234);

worksheet.Cell(1, 1).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
worksheet.Cell(1, 2).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
worksheet.Cell(1, 3).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
worksheet.Cell(1, 4).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
worksheet.Cell(1, 5).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
worksheet.Cell(1, 6).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
worksheet.Cell(1, 7).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
worksheet.Cell(1, 8).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
worksheet.Cell(1, 9).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
worksheet.Cell(1, 10).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
worksheet.Cell(1, 11).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
worksheet.Cell(1, 12).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;

var httpResponse = Response;

httpResponse.Clear();
httpResponse.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
httpResponse.AddHeader("content-disposition",
    $"attachment;filename=\"VB LSMW - {DateTime.Now:dd-MM-yyyy hh:mm:ss}.xlsx\"");


using (MemoryStream memoryStream = new MemoryStream())
{
    workbook.SaveAs(memoryStream);
    memoryStream.WriteTo(httpResponse.OutputStream);
    memoryStream.Close();
}

httpResponse.End();
```

**Comment by igitur** [comment] 2017-05-31 12:34
I can't reproduce the problem. Try with the latest code from the `develop` branch from the repository.

**Comment by Baseline86** [comment] 2017-05-31 13:13
Same issue, error on the following code:

`                var numberFormatId = xlStyle.NumberFormat.NumberFormatId >= 0
                    ? xlStyle.NumberFormat.NumberFormatId
                    : allSharedNumberFormats[xlStyle.NumberFormat].NumberFormatId;`

Values: 

xlStyle.NumberFormat.NumberFormatId = -1
xlStyle.NumberFormat = "#,##0.00\\%"
allSharedNumberFormats = empty

**Comment by igitur** [comment] 2017-05-31 13:36
Please post code that I copy and paste into a Console application that will reproduce the error.

**Comment by cgd2** [comment] 2017-06-06 09:17
I get the same error in another situation - 'The given key was not present in the dictionary.'
Create a blank spreadsheet from Excel, insert a comment into one of the cells, and save as Macro enabled. In code simply open and save to cause the error.
string FilePath = "C:\Temp\SampleSheet.xlsm";
var workBook = new XLWorkbook(FilePath);
workBook.Save(false);

**Comment by igitur** [comment] 2017-06-06 09:25
@cgd2 Again, I cannot reproduce this. Attach the file, please.

**Comment by cgd2** [comment] 2017-06-06 12:39
Sample Excel Spreadsheet
[SampleSheet.zip](https://github.com/ClosedXML/ClosedXML/files/1055008/SampleSheet.zip)

**Comment by cgd2** [comment] 2017-06-06 12:50
Sample code:-

using ClosedXML.Excel;

namespace TestClosedXMLSave
{
    class Program
    {
        static void Main(string[] args)
        {
            string filePath = @"C:\Temp\SampleSheet.xlsm";
            var workBook = new XLWorkbook(filePath);
            workBook.Save(false);
        }
    }
}

**Comment by cgd2** [comment] 2017-06-06 12:51
Closed XML version 0.87.0.0 - runtime v4.0.30319

**Comment by cgd2** [comment] 2017-06-06 12:55
An unhandled exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in mscorlib.dll

Additional information: The given key was not present in the dictionary.

**Comment by igitur** [comment] 2017-06-06 13:02
@cgd2 Thanks, I can reproduce this now. This was fixed in #310

**Comment by igitur** [comment] 2017-06-06 13:03
Duplicate of #307

**Closed by igitur** 2017-06-06 13:03 UTC

**Comment by christopher-persinger** [comment] 2022-12-15 19:32
This is a long shot, but is there a work around to fix this issue without updating the package?

**Comment by vbjay** [comment] 2022-12-15 20:00
Why would you ask this. A nuget package has an issue. A fix is pushed and nuget version is released. To get the functionality....you have to bump up. 

You have 2 options:

- Pull nuget update
- Pull source and apply a backport fix to the version you are using.

**Comment by christopher-persinger** [comment] 2022-12-15 20:05
Because I am working within a system with enough technical debt where updating the packages is just feasible, and this issue kinda just randomly appeared after years of it working without issue. 

I am rather new to the world of nuget packages. Did not know that I could pull source, and apply a backported fix. 
I appreciate that idea thank you very much!

**Comment by vbjay** [comment] 2022-12-15 20:13
1. https://github.com/ClosedXML/ClosedXML#extensions note report and other items
1. Pull repo and use https://github.com/ClosedXML/ClosedXML/releases to find which commit. Release are tagged so you should see tags in repo too.

**Comment by vbjay** [comment] 2022-12-15 20:19
The problem with backport option:. You are now responsible for getting your custom version to work and will have to manage all the customizations and fixes you apply.  If you ask for help with your custom repo here..your issue would be looked at but we may just have to say you applied too much custom work and no longer is our code so you will have to figure out. I'd hope we could still help but we can't support custom versions of the project.
