### ISSUE TITLE
Uanble to parse formala with named ranges starting with a field address

### ISSUE THREAD

**Issue by schmelnik** [ClosedXML/ClosedXML#1885] opened 2022-10-24 14:31 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.97.0

**What is the current behavior?**
Starting with the latest release, any access to the value of a cell referencing a named range having a name starting like a cell address (A1 format) ends up in an exception:
ClosedXML.Excel.CalcEngine.ExpressionParseException : Unable to parse formula 'W1.':
Location 0:2 - Syntax error, expected: CellToken, NameToken, NamedRangeCombinationToken, VRangeToken, HRangeToken, RefErrorToken, UDFToken, [, FileNameEnclosedInBracketsToken, (, ExcelRefFunctionToken, ExcelConditionalRefFunctionToken, SheetNameToken, ', FileNameNumericToken, FilePathToken, MultipleSheetsToken

So any named range with a name starting with 1 or zwo characters followed by 1 or more digits and followed by some more characters makes a valid name for named references in Excel, but are causing an exception in ClosedXML.

**What is the expected behavior or new feature?**
Access is possible and returns the correct value (like in previous versions)

Complete this.

**Is this a regression from the previous version?**
Yes, accessing a value of a cell containing a formular with named ranges in the described form had been working in 0.96.0
Anyway there are additional problems with such named ranges in both versions: Assigning the same formula to a range of cells in multiple lines including access to similar named named ranges will result in incrementing the numbers of the names in the named ranges.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
            string namedRange = "W1.";
            var wb = new XLWorkbook();
            IXLWorksheet ws = wb.Worksheets.Add("Sheet1");
            ws.NamedRanges.Add(namedRange, "$A$1");
            ws.Cell("A1").SetValue<double>(1);
            ws.Cell("B1").FormulaA1 = namedRange;
            Assert.AreEqual(1, ws.Cell("B1").Value);
}

just changing the name from "W1." to e.g. "W.1" makes the test pass

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment] 2022-10-24 17:10
I analyzed the issue and made a PR fix to the XLParser (https://github.com/spreadsheetlab/XLParser/issues/165). 
I am closing this, because the issue is a bug in the dependency, not ClosedXML. I will update the dependency version of the ClosedXMl package when a new version of XLParser will be released.

**Closed as completed** 2022-10-24 17:12 UTC

**Comment by schmelnik** [comment] 2023-01-24 06:28
> I analyzed the issue and made a PR fix to the XLParser ([spreadsheetlab/XLParser#165](https://github.com/spreadsheetlab/XLParser/issues/165)). I am closing this, because the issue is a bug in the dependency, not ClosedXML. I will update the dependency version of the ClosedXMl package when a new version of XLParser will be released.

Any idea when you are updating the reference to XMLParser? It looks like your changes have been merged already a while ago
