### ISSUE TITLE
In some files, pictures with 'Move and don't size with cell' property are in a wrong position after save.

### ISSUE THREAD

**Issue by J-Sanna** [ClosedXML/ClosedXML#1898] opened 2022-10-28 13:38 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [X] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.97.0

**What is the current behavior?**

When saving a workbook containing a picture inserted within excel, with placement mode 'Move but don't size with cells' and double anchors, picture position maybe messed upon save.

**What is the expected behavior or new feature?**

Image should stay at initial position when saving file.

**Is this a regression from the previous version?**

This is not a regression. Bug was present in 0.92.0 already.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
	var filePath = "C:\Tests\Example.xlsx"
	var workbook = new XLWorkbook(filePath);
	workbook.SaveAs(filePath + ".test.xlsx");
}
```

- [] I attached a sample spreadsheet.  (You can drag files on to this issue)

Sorry I have no exemple for this one. It comes from a customer spreadsheet and I couldn't reproduce the configuration. Replacing images fixes the issue.
I see the issue happens in ClosedXML.Excel.XLWorkbook.LoadDrawings method, where the case 'type= TwoCellAnchor' along with 'EditAs = OneCellEdit' ends up ignoring the 'to' anchor.
It does not seem so easy to resolve, as MoveTo signature with From and To implies setting the Placement property on MoveAndSize, so fixing here changes the picture properties shown to user.

**Comment by jahav** [comment] 2022-10-30 15:34
I am closing the issue due to lack of reproducibility. Dev time resources are scarce and there are hundreds of issues, thus reproducibility is a requirement.

**Closed as not planned by jahav** 2022-10-30 15:34 UTC
