### ISSUE TITLE
emergency： not compatible with newest openxml

### ISSUE THREAD

**Issue by jismyname** [ClosedXML/ClosedXML#2370] opened 2024-07-18 03:03 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [*] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ *] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.102.2

DocumentFormat.OpenXml 3.0.2

**What is the current behavior?**

export excel

**What is the expected behavior or new feature?**

success

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{  
            DataTable dataTable = new DataTable();
            dataTable.Columns.Add("ID", typeof(int));
            dataTable.Columns.Add("Name", typeof(string));
            dataTable.Columns.Add("Age", typeof(int));

            dataTable.Rows.Add(1, "John", 25);
            dataTable.Rows.Add(2, "Alice", 30);
            dataTable.Rows.Add(3, "Bob", 40);
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Sheet1");
                worksheet.FirstCell().InsertTable(dataTable);
                workbook.SaveAs("D:\\tableDemo.xlsx");
            }
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment] 2024-07-19 14:40
Duplicate of #2220

**Closed as not planned by jahav** 2024-07-19 14:40 UTC
