### ISSUE TITLE
Cell formatting lost for empty cells on SaveAs after v0.92.1

### ISSUE THREAD

**Issue by CodingChristian** [ClosedXML/ClosedXML#1147] opened 2019-02-19 09:15 UTC
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.92.1 and 0.93.0

**What is the current behavior?**

In 0.92.1, cell formatting on empty cells is preserved after SaveAs, from 0.93.0 forwards it is lost.

**What is the expected behavior or new feature?**

Not really sure what the "correct" behaviour is. Any explanation is very welcome, could not find anything in the docs or change log.

**Did this work in previous versions of our tool?  Which versions?**

Yes v0.92.1

## Reproducibility

If the code is run with v0.92.1, the Date, Number and Currency formatted cells (whole columns A-C) is still present in the output.xlsx.
If the code is run with v0.93.0 or greater, the formatting is gone for all empty cells (rows > 2) and these have "General" formatting.

[format_trial.xlsx](https://github.com/ClosedXML/ClosedXML/files/2879245/format_trial.xlsx)

**Code to reproduce problem:**
```c#
        static void Main(string[] args) {
            var xlfile = @"format_trial.xlsx";
            var workbook = new XLWorkbook(xlfile);
            workbook.SaveAs(@"output.xlsx");
        }
```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by CodingChristian** [comment] 2019-02-19 09:19
Might not be an actual bug, but I couldn't find a "question" tag.

**Comment by CodingChristian** [comment] 2019-02-19 10:17
Even if I set the formatting explicitly, it is removed:

```C#
        static void Main(string[] args) {
            var xlfile = @"E:\format_trial.xlsx";
            var workbook = new XLWorkbook(xlfile);
            workbook.Worksheets.First().Cell("A3").SetDataType(XLDataType.DateTime);
            workbook.Worksheets.First().Cell("A4").DataType = XLDataType.DateTime;
            workbook.SaveAs(@"E:\output.xlsx");
        }
```

**Comment by igitur** [comment] 2019-02-20 10:42
Still checking further, but in the meantime, I can see the style id from the columns are not being saved anymore.

Before:
```xml
<col min="1" max="1" width="15.109375" style="2" customWidth="1"/>
```

After:
```xml
<col min="1" max="1" width="15.109375" style="0" customWidth="1"/>
```

**Comment by igitur** [comment] 2019-02-20 11:05
The number format ID is set on an `XLColumns` collection, but the format isn't propagated through to the child `XLColumn` elements. @Pankraty We had an issue about the propagation of styles to child elements, right? I can't find it now.

**Comment by igitur** [comment] 2019-02-20 11:06
https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML/Excel/XLWorkbook_Load.cs#L1916

**Comment by Pankraty** [comment] 2019-02-20 11:10
This one #1135

**Comment by igitur** [comment] 2019-02-20 11:11
Oh, it's a PR! Thanks.

**Comment by igitur** [comment] 2019-02-20 11:12
Yes, this issue looks like a duplicate of #961

**Comment by igitur** [comment] 2019-02-20 11:36
```c#
static void Main(string[] args) {
            var xlfile = @"E:\format_trial.xlsx";
            var workbook = new XLWorkbook(xlfile);
            workbook.Worksheets.First().Cell("A3").SetDataType(XLDataType.DateTime);
            workbook.Worksheets.First().Cell("A4").DataType = XLDataType.DateTime;
            workbook.SaveAs(@"E:\output.xlsx");
        }
```

@CodingChristian By the way, that's not a solution. Data types are related, but not the same as cell styles.

A workaround would be:
```c#
workbook.Worksheets.First().Column(1).Style.NumberFormat.SetNumberFormatId(14);
```
or
```c#
workbook.Worksheets.First().Column(1).Style.NumberFormat.Format = "yyyy-MM-dd";
```

**Comment by igitur** [comment] 2019-02-20 11:47
Fixed by #1135

**Comment by CodingChristian** [comment] 2019-02-20 12:02
@igitur When I try the two workarounds, only the first one (setting the format id) works.
The second one 
`workbook.Worksheets.First().Column("E").Style.NumberFormat.Format = "TT. MMM JJ";`
gives an exception when "SaveAs" is called:

```
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at ClosedXML.Excel.XLWorkbook.GenerateWorkbookStylesPartContent(WorkbookStylesPart workbookStylesPart, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)
   at ClosedXML_Trials_3.ClosedXML_Trials_3_Main.Main(String[] args) in C:\Users\████████████████\ClosedXML_Trials_3_Main.cs:line 22
```

**Comment by CodingChristian** [comment] 2019-02-20 13:04
I would also consider this to be a duplicate of #961 . I first thought it was about the saving, but it actually is the loading, that's going wrong.

**Closed** 2019-02-21 09:10 UTC
Labels: bug
