### ISSUE TITLE
Getting Out of memory exception while Adding datatable  with 100000+ records

### ISSUE THREAD

**Issue by shravandivity** [ClosedXML/ClosedXML#1752] opened 2022-01-14 19:01 UTC
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.95.4

**What is the current behavior?**
I am getting System out of memory exception while adding datatable with 100000+ records to excel workbook at below line
XLWorkbook wb = new XLWorkbook();
wb.Worksheets.Add(datatable , "Sheet1");

I am using ClosedXML version 0.95.4

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
XLWorkbook wb = new XLWorkbook();
var ws = wb.Worksheets.Add(datatable, "Sheet1");
ws.Table(0).ShowAutoFilter = false;
ws.Table(0).Theme = XLTableTheme.None;
}
```

I am getting out of memory exception at var ws = wb.Worksheets.Add(datatable, "Sheet1");

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by vbjay** [comment] 2022-01-15 02:00
You didn't provide complete example. Write the code to create the datable
and does without a database. We can't run your code.

**Comment by shravandivity** [comment] 2022-01-15 09:32
public void Main()
{
DataTable dt = new DataTable();
DataColumn dc1 = new DataColumn("A", typeof(String));
DataColumn dc2 = new DataColumn("B", typeof(String));
DataColumn dc3 = new DataColumn("C", typeof(String));
DataColumn dc4 = new DataColumn("D", typeof(String));
DataColumn dc5 = new DataColumn("E", typeof(String));
DataColumn dc6 = new DataColumn("F", typeof(String));
DataColumn dc7 = new DataColumn("G", typeof(String));
DataColumn dc8 = new DataColumn("H", typeof(String));
DataColumn dc9 = new DataColumn("I", typeof(String));
DataColumn dc10 = new DataColumn("J", typeof(String));
DataColumn dc11 = new DataColumn("K", typeof(String));
DataColumn dc12 = new DataColumn("L", typeof(String));
DataColumn dc13 = new DataColumn("M", typeof(String));
DataColumn dc14 = new DataColumn("N", typeof(String));
DataColumn dc15 = new DataColumn("O", typeof(String));
DataColumn dc16 = new DataColumn("P", typeof(String));
DataColumn dc17 = new DataColumn("Q", typeof(String));
DataColumn dc18 = new DataColumn("R", typeof(String));
DataColumn dc19 = new DataColumn("S", typeof(String));
DataColumn dc20 = new DataColumn("T", typeof(String));
DataColumn dc21 = new DataColumn("U", typeof(String));
DataColumn dc22 = new DataColumn("V", typeof(String));
DataColumn d23 = new DataColumn("W", typeof(String));
DataColumn d24 = new DataColumn("X", typeof(String));
DataColumn d25 = new DataColumn("Y", typeof(String));
DataColumn d26 = new DataColumn("Z", typeof(String));

dt.Columns.Add(dc1);
dt.Columns.Add(dc2);
dt.Columns.Add(dc3);
dt.Columns.Add(dc4);
dt.Columns.Add(dc5);
dt.Columns.Add(dc6);
dt.Columns.Add(dc7);
dt.Columns.Add(dc8);
dt.Columns.Add(dc9);
dt.Columns.Add(dc10);
dt.Columns.Add(dc11);
dt.Columns.Add(dc12);
dt.Columns.Add(dc13);
dt.Columns.Add(dc14);
dt.Columns.Add(dc15);
dt.Columns.Add(dc16);
dt.Columns.Add(dc17);
dt.Columns.Add(dc18);
dt.Columns.Add(dc19);
dt.Columns.Add(dc20);
dt.Columns.Add(dc21);
dt.Columns.Add(dc22);
dt.Columns.Add(dc23);
dt.Columns.Add(dc24);
dt.Columns.Add(dc25);
dt.Columns.Add(dc26);

for(int i = 0; i < 300000; i++)
{
   DataRow dr = dt.NewRow();
   dr[0] = "Sample text to test";
dr[0] = "Sample text to test";
}
XLWorkbook wb = new XLWorkbook();
var ws = wb.Worksheets.Add(dt, "Sheet1");
ws.Table(0).ShowAutoFilter = false;
ws.Table(0).Theme = XLTableTheme.None;
}

**Comment by shravandivity** [comment] 2022-01-15 09:38
> public void Main() { DataTable dt = new DataTable(); DataColumn dc1 = new DataColumn("A", typeof(String)); DataColumn dc2 = new DataColumn("B", typeof(String)); DataColumn dc3 = new DataColumn("C", typeof(String)); DataColumn dc4 = new DataColumn("D", typeof(String)); DataColumn dc5 = new DataColumn("E", typeof(String)); DataColumn dc6 = new DataColumn("F", typeof(String)); DataColumn dc7 = new DataColumn("G", typeof(String)); DataColumn dc8 = new DataColumn("H", typeof(String)); DataColumn dc9 = new DataColumn("I", typeof(String)); DataColumn dc10 = new DataColumn("J", typeof(String)); DataColumn dc11 = new DataColumn("K", typeof(String)); DataColumn dc12 = new DataColumn("L", typeof(String)); DataColumn dc13 = new DataColumn("M", typeof(String)); DataColumn dc14 = new DataColumn("N", typeof(String)); DataColumn dc15 = new DataColumn("O", typeof(String)); DataColumn dc16 = new DataColumn("P", typeof(String)); DataColumn dc17 = new DataColumn("Q", typeof(String)); DataColumn dc18 = new DataColumn("R", typeof(String)); DataColumn dc19 = new DataColumn("S", typeof(String)); DataColumn dc20 = new DataColumn("T", typeof(String)); DataColumn dc21 = new DataColumn("U", typeof(String)); DataColumn dc22 = new DataColumn("V", typeof(String)); DataColumn d23 = new DataColumn("W", typeof(String)); DataColumn d24 = new DataColumn("X", typeof(String)); DataColumn d25 = new DataColumn("Y", typeof(String)); DataColumn d26 = new DataColumn("Z", typeof(String));
> 
> dt.Columns.Add(dc1); dt.Columns.Add(dc2); dt.Columns.Add(dc3); dt.Columns.Add(dc4); dt.Columns.Add(dc5); dt.Columns.Add(dc6); dt.Columns.Add(dc7); dt.Columns.Add(dc8); dt.Columns.Add(dc9); dt.Columns.Add(dc10); dt.Columns.Add(dc11); dt.Columns.Add(dc12); dt.Columns.Add(dc13); dt.Columns.Add(dc14); dt.Columns.Add(dc15); dt.Columns.Add(dc16); dt.Columns.Add(dc17); dt.Columns.Add(dc18); dt.Columns.Add(dc19); dt.Columns.Add(dc20); dt.Columns.Add(dc21); dt.Columns.Add(dc22); dt.Columns.Add(dc23); dt.Columns.Add(dc24); dt.Columns.Add(dc25); dt.Columns.Add(dc26);
> 
> for(int i = 0; i < 300000; i++) { DataRow dr = dt.NewRow(); dr[0] = "Sample text to test"; dr[1] = "Sample text to test"; dr[2] = "Sample text to test"; dr[3] = "Sample text to test"; dr[4] = "Sample text to test"; dr[5] = "Sample text to test"; dr[6] = "Sample text to test"; dr[7] = "Sample text to test"; dr[8] = "Sample text to test"; dr[9] = "Sample text to test"; dr[10] = "Sample text to test"; dr[11] = "Sample text to test"; dr[12] = "Sample text to test"; dr[13] = "Sample text to test"; dr[14] = "Sample text to test"; dr[15] = "Sample text to test"; dr[16] = "Sample text to test"; dr[17] = "Sample text to test"; dr[18] = "Sample text to test"; dr[19] = "Sample text to test"; dr[20] = "Sample text to test"; dr[21] = "Sample text to test"; dr[22] = "Sample text to test"; dr[23] = "Sample text to test"; dr[24] = "Sample text to test"; dr[25] = "Sample text to test"; dt.Rows.Add(dr); }
> 
> XLWorkbook wb = new XLWorkbook(); var ws = wb.Worksheets.Add(dt, "Sheet1"); ws.Table(0).ShowAutoFilter = false; ws.Table(0).Theme = XLTableTheme.None; }

@vbjay Please find the complete code below

public void Main()
{
DataTable dt = new DataTable();
DataColumn dc1 = new DataColumn("A", typeof(String));
DataColumn dc2 = new DataColumn("B", typeof(String));
DataColumn dc3 = new DataColumn("C", typeof(String));
DataColumn dc4 = new DataColumn("D", typeof(String));
DataColumn dc5 = new DataColumn("E", typeof(String));
DataColumn dc6 = new DataColumn("F", typeof(String));
DataColumn dc7 = new DataColumn("G", typeof(String));
DataColumn dc8 = new DataColumn("H", typeof(String));
DataColumn dc9 = new DataColumn("I", typeof(String));
DataColumn dc10 = new DataColumn("J", typeof(String));
DataColumn dc11 = new DataColumn("K", typeof(String));
DataColumn dc12 = new DataColumn("L", typeof(String));
DataColumn dc13 = new DataColumn("M", typeof(String));
DataColumn dc14 = new DataColumn("N", typeof(String));
DataColumn dc15 = new DataColumn("O", typeof(String));
DataColumn dc16 = new DataColumn("P", typeof(String));
DataColumn dc17 = new DataColumn("Q", typeof(String));
DataColumn dc18 = new DataColumn("R", typeof(String));
DataColumn dc19 = new DataColumn("S", typeof(String));
DataColumn dc20 = new DataColumn("T", typeof(String));
DataColumn dc21 = new DataColumn("U", typeof(String));
DataColumn dc22 = new DataColumn("V", typeof(String));
DataColumn d23 = new DataColumn("W", typeof(String));
DataColumn d24 = new DataColumn("X", typeof(String));
DataColumn d25 = new DataColumn("Y", typeof(String));
DataColumn d26 = new DataColumn("Z", typeof(String));

dt.Columns.Add(dc1);
dt.Columns.Add(dc2);
dt.Columns.Add(dc3);
dt.Columns.Add(dc4);
dt.Columns.Add(dc5);
dt.Columns.Add(dc6);
dt.Columns.Add(dc7);
dt.Columns.Add(dc8);
dt.Columns.Add(dc9);
dt.Columns.Add(dc10);
dt.Columns.Add(dc11);
dt.Columns.Add(dc12);
dt.Columns.Add(dc13);
dt.Columns.Add(dc14);
dt.Columns.Add(dc15);
dt.Columns.Add(dc16);
dt.Columns.Add(dc17);
dt.Columns.Add(dc18);
dt.Columns.Add(dc19);
dt.Columns.Add(dc20);
dt.Columns.Add(dc21);
dt.Columns.Add(dc22);
dt.Columns.Add(dc23);
dt.Columns.Add(dc24);
dt.Columns.Add(dc25);
dt.Columns.Add(dc26);

for(int i = 0; i < 300000; i++)
{
DataRow dr = dt.NewRow();
dr[0] = "Sample text to test";
dr[1] = "Sample text to test";
dr[2] = "Sample text to test";
dr[3] = "Sample text to test";
dr[4] = "Sample text to test";
dr[5] = "Sample text to test";
dr[6] = "Sample text to test";
dr[7] = "Sample text to test";
dr[8] = "Sample text to test";
dr[9] = "Sample text to test";
dr[10] = "Sample text to test";
dr[11] = "Sample text to test";
dr[12] = "Sample text to test";
dr[13] = "Sample text to test";
dr[14] = "Sample text to test";
dr[15] = "Sample text to test";
dr[16] = "Sample text to test";
dr[17] = "Sample text to test";
dr[18] = "Sample text to test";
dr[19] = "Sample text to test";
dr[20] = "Sample text to test";
dr[21] = "Sample text to test";
dr[22] = "Sample text to test";
dr[23] = "Sample text to test";
dr[24] = "Sample text to test";
dr[25] = "Sample text to test";
dt.Rows.Add(dr);
}

XLWorkbook wb = new XLWorkbook();
var ws = wb.Worksheets.Add(dt, "Sheet1");
ws.Table(0).ShowAutoFilter = false;
ws.Table(0).Theme = XLTableTheme.None;
}

**Comment by vbjay** [comment] 2022-01-15 14:27
@shravandivity  Does it still happen if you use a filestream instead of memorystream?

**Comment by shravandivity** [comment] 2022-01-15 17:28
@vbjay WIth the code example i shared with you i am getting error at wb.SaveAs(ms). But in my actual code where i am fetching data from database, i am getting exception at wb.Worksheets.Add(Datatable, "Sheetname") 

I am not able to understand why its giving out memory exception as soon as record count exceeds around 120K

**Comment by vbjay** [comment] 2022-01-16 05:46
> @vbjay WIth the code example i shared with you i am getting error at wb.SaveAs(ms). But in my actual code where i am fetching data from database, i am getting exception at wb.Worksheets.Add(Datatable, "Sheetname") 
> 
> I am not able to understand why its giving out memory exception as soon as record count exceeds around 120K



- excel is not a dbms. It is not designed for a crazy amount of records.  Look into only loading what data is needed from the data. 
- ClosedXML creates a lot of objects per cell/row/column. Each instance takes up memory.

**Comment by Pitterling** [comment] 2022-01-16 10:52
Seems like you did not search for already existing issues
[is:issue memory ](https://github.com/ClosedXML/ClosedXML/issues?q=is%3Aissue+memory+)

I bet you are also using 32bit.

**Comment by jahav** [comment] 2022-12-18 21:33
Duplicate of #1753

**Closed by jahav** 2022-12-18 21:33 UTC
